### ISSUE TITLE
0.8.2拖动时窗口自动变大

### ISSUE THREAD

**Issue by zhouzhou84** [CopyTranslator/CopyTranslator#100]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
0.8.2拖动时窗口自动变大，是越拖动越大

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.2.0 x86 版
 - 出现问题时的模式：MainMode
 - 操作系统：win10 64位
 - 阅读器：福昕阅读器

**如何复现这个问题**
重现行为的步骤：
1. 拖动时窗口

**问题出现时，当时的CopyTranslator的设置截图**
![TIM截图20190422132322](https://user-images.githubusercontent.com/33458022/56484387-ea318f80-6501-11e9-998e-1522903bd838.png)

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
0.6.0

**Comment by elliottzheng** [comment]
用回0.0.8 RC5吧，小伙子，只能说兼容性问题
