### ISSUE TITLE
[Features]加入腾讯翻译君的翻译

### ISSUE THREAD

**Issue by fcmy-yao** [CopyTranslator/CopyTranslator#103]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
     是否可以加入腾讯翻译君的翻译，本人受他人安利，使用之后，确实在论文翻译的方面，效果不错，从使用体验来看好于google翻译

**Comment by elliottzheng** [comment]
会考虑的

**Comment by elliottzheng** [comment]
已加入
