### ISSUE TITLE
Ctrl+L 快捷键被占用

### ISSUE THREAD

**Issue by mike-ocean** [CopyTranslator/CopyTranslator#104]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**描述问题**
一旦打开本软件，Ctrl+L快捷键就会无效。由于Ctrl+L相信在很多人的日常使用中有很重要的地位（linux清屏、聚焦地址栏），希望能够解除对该快捷键的独占。或者能够自定义快捷键。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.2.0
 - 出现问题时的模式：MainMode
 - 操作系统：如win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 开启监听剪贴板、自动显示、自动隐藏、自动净化、总是置顶
2. 使用快捷键Ctrl+L 只会由本软件响应，并弹出翻译结果

**Comment by elliottzheng** [comment]
可以自己改快捷键，看这里 [自定义全局快捷键](https://copytranslator.gitee.io/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by mike-ocean** [comment]
@elliottzheng 感谢！
