### ISSUE TITLE
窗口大小Bug

### ISSUE THREAD

**Issue by ZQRui** [CopyTranslator/CopyTranslator#105]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**窗口大小无法正常调节BUG**

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.2.0 x64 版
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：如win10 64位
 - 阅读器：any
 - 出现问题的文档：any
 - 出现问题的段落：any

**如何复现这个问题**
重现行为的步骤：
1.  长按或者拖拽窗口顶部
2.  窗口会像下面动图中一样不断扩大

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![copyTranslator window size bug](https://user-images.githubusercontent.com/16930652/56874913-cfb26580-6a6f-11e9-9adf-7fb392859025.gif)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都不能用

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
[v0.0.8-Zouwu-RC5](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v0.0.8-Zouwu-RC5)
这个版本没有这个bug

**本机的其他配置：**
- 操作系统名称	Microsoft Windows 10 专业版
 - 版本	10.0.17134 版本 17134
 - 系统类型	基于 x64 的电脑
 - 处理器	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz，1800 Mhz，4 个内核，8 个逻辑处理器
 - 双显示器：
  - 分辨率	1920 x 1080
 -  分辨率	2560 x 1640
 - **但是拔掉一个显示器之后也不好用**

**Comment by elliottzheng** [comment]
已知问题，可以先回退到RC5

**Comment by elliottzheng** [comment]
已经修复了，待新版本发布可以在三种标题栏中切换，自行根据兼容性选择使用
