### ISSUE TITLE
可否不提示更新到最新版哈？

### ISSUE THREAD

**Issue by strivebo** [CopyTranslator/CopyTranslator#106]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.7-Kylin-RC1 版
 - 出现问题时的模式：无
 - 操作系统：win7 64位

建议哈：

> 我更新过到 v8.2.0 版本，觉得还是用之前版本 0.0.7 版本好，或许是习惯了，但是每次开机软件也随着启动，就提示更新到最新版。想请作者麻烦能关掉这个吗？哈哈，还算习惯0.0.7版本哈。谢谢！

**Comment by elliottzheng** [comment]
刚发布了 v7.2.0 Kylin Ultimate 解决了这个问题

**Comment by strivebo** [comment]
@elliottzheng 谢谢！这个版本对我来说够用，不错，使用快捷键方式 shift+f1、shift+f2 还是很方便的。目前还有几点，好像之前我有提过(*￣︶￣)，比如 
1. 点击 x 能最小化到底部托盘而不是直接关闭应用；
2. 希望增加一个简单易懂小白也能轻松掌握的设置菜单，我记得之前用过最新版貌似设置快捷键我还没清楚（这也是我没用最新版原因之一），比如像「开机自启」的这样的设置，可以放在专门「设置」菜单，目前的版本没找到这个设置，还有比如快捷键的设置，也可以放在专门的「设置」菜单统一设置

**Comment by elliottzheng** [comment]
第一点：远古版本是缩小到底部托盘，而后有人建议改为关闭应用，这个是个人喜好问题，但是并不是很关键的问题。我不会再添加新功能到v7版本，如果您有需求，可以加入我们，负责python版本的维护和开发。
第二点：设置界面有考虑过，后面会加上。但其实新版本设置快捷键也并不难，看下使用指南，可以试着修改下。

**Comment by strivebo** [comment]
@elliottzheng 嗯嗯。那没事。还是要说声谢谢以及辛苦了。
