### ISSUE TITLE
找不到shortcut.json

### ISSUE THREAD

**Issue by smartnikocj** [CopyTranslator/CopyTranslator#115]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v7.2.0-Kylin-Ultimate
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：win 7 64位

之前用的版本会自动在“c:\users\你的用户名”目录下生成copytranlator文件夹，今天更新到v7.2.0-Kylin-Ultimate并没有自动生成copytranlator文件，只生成了copytranslator.json单个文件，找不到shortcut.json。想自定义快捷键找不到文件。谢谢！

**Comment by elliottzheng** [comment]
当前存在两个不同大版本，v7/v0.0.7是旧的python实现的，现在的官网的说明文档是针对v8/v0.0.8的electron实现的，两个很不一样，v7.2.0 应该是v7的最后一次更新。
![image](https://user-images.githubusercontent.com/22427645/57120623-3ce23580-6da5-11e9-954f-f3af9fb2c743.png)

**Comment by smartnikocj** [comment]
谢谢您的回答。那现在v7/v0.0.7是不能自定shortcut吗？谢谢！

**Comment by smartnikocj** [comment]
哦哦。我明白了。因为我之前装过v8，原来是以前的文件夹。谢谢。
