### ISSUE TITLE
最新版拖动窗口移动时，窗口大小也会自动改变

### ISSUE THREAD

**Issue by Boomhyomin** [CopyTranslator/CopyTranslator#116]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
最新版，拖动窗口移动时，窗口大小也会改变（缓慢变大）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：最新版 x64 版
 - 出现问题时的模式：所有模式
 - 操作系统：win10 64位
 - 阅读器：adobe acrobat reader DC（https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html）

**如何复现这个问题**
重现行为的步骤：
1. 打开软件
2. 拖动窗口，改变其位置
3. 拖动过程中窗口大小会自动改变

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都有此问题

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
之前只能在窗口固定位置拖动，并没有出现此问题

**Comment by elliottzheng** [comment]
Duplicate of #105 
修复了，还没发布

**Comment by Boomhyomin** [comment]
> Duplicate of #105
> 修复了，还没发布

perfect！
