### ISSUE TITLE
似乎访问谷歌翻译

### ISSUE THREAD

**Issue by windsOne** [CopyTranslator/CopyTranslator#117]
**系统环境（请填写以下信息）：**
 - CopyTranslator版本：V8.2.0
 - 出现问题时的模式：谷歌翻译 无效 
 - 操作系统：win10 64位
 - 阅读器： chrome浏览器

**如何复现这个问题**
重现行为的步骤：
1. 选择任意内容 
2. ctr+c 
![image](https://user-images.githubusercontent.com/14890297/57516585-96b7a200-7347-11e9-890a-81a1a13f57a1.png)

**Comment by elliottzheng** [comment]
请到[gitter](https://gitter.im/CopyTranslator/Lobby)询问使用上的问题，这不是bug, 红色偶尔出现是正常现象，如果复制的东西太长，如果一直出现请检查网络连接
