### ISSUE TITLE
[Features]希望可以增加通知功能

### ISSUE THREAD

**Issue by catcherxuefeng** [CopyTranslator/CopyTranslator#119]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。
使用笔记本，屏幕太小，专注模式也占用空间，希望可以将翻译结果放在任务栏，或者复制后弹出通知
**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
选择后任务栏输出翻译，复制后通知中心通知翻译结果，双击任务栏小图标呼出主界面
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
QTranser 可以实现任务栏显示翻译
**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
你说的是下面这样？
![image](https://user-images.githubusercontent.com/22427645/57597103-91916780-7580-11e9-9eb4-52d8025e64b5.png)
![](https://s2.ax1x.com/2019/04/22/EkSGUe.gif)

**Comment by catcherxuefeng** [comment]
是这样，但是我在你的软件里没有找到相应的设置，贴边隐藏也没有效果

**Comment by elliottzheng** [comment]
在设置里有，另外可以尝试删除配置文件夹 后重启软件，[配置文件夹文件夹在哪里](https://copytranslator.github.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C)
