### ISSUE TITLE
win10安装后无反应

### ISSUE THREAD

**Issue by godchenghao** [CopyTranslator/CopyTranslator#120]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - 从百度网盘下载的CopyTranslator-setup-8.2.0.exe
 - 出现问题时的模式：安装后打开界面无反应，已经等了一会了，占cpu资源。
 - 操作系统：win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![图片](https://user-images.githubusercontent.com/45276259/57827288-6190d100-77d9-11e9-9741-10059403b1c5.png)
任务管理器：
![图片](https://user-images.githubusercontent.com/45276259/57827296-6ce3fc80-77d9-11e9-975c-ed35f7720d96.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by Ash1One** [comment]
我也是同样的问题，8.2.0版本安装后打开一直处于 `无响应` 状态。

**Comment by cibiluozu** [comment]
试一下复制一个空的字符串再打开？ 我也有这种情况，有可能是复制的内容太多了。

**Comment by Ash1One** [comment]
> 试一下复制一个空的字符串再打开？ 我也有这种情况，有可能是复制的内容太多了。

@cibiluozu 正解！谢谢😀

**Comment by Ash1One** [comment]
但是又出现了这个问题https://github.com/CopyTranslator/CopyTranslator/issues/116#issue-442017650 😂

**Comment by Au3C2** [comment]
给程序管理员权限
