### ISSUE TITLE
[F复制译文后，软件会再次进行翻译

### ISSUE THREAD

**Issue by ObrienCC** [CopyTranslator/CopyTranslator#124]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.6.1 x86 版
 - 出现问题时的模式：MainMode/ FocusMode或者说对照模式或专注模式
 - 操作系统：如win10 64位/win 7 32位
 - 阅读器：如 chrome浏览器/福昕阅读器，最好附上下载地址
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 打开监听剪切板
2. 翻译一段话
3. 复制译文
4. 此时软件会再次自动翻译译文

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by ZhuBaohe** [comment]
更新到最新的v8.2.0，应该没这个问题了

**Comment by elliottzheng** [comment]
你没有提供足够多的的信息，我无法复现这个问题

**Comment by ObrienCC** [comment]
> 你没有提供足够多的的信息，我无法复现这个问题

第三步没说清除。
3.使用CTRL+C 复制一部分译文后，软件会自动翻译译文

**Comment by elliottzheng** [comment]
。。。复制一部分译文，当然会自动翻译了，剪贴板的内容又不一样

**Comment by ObrienCC** [comment]
> 。。。复制一部分译文，当然会自动翻译了，剪贴板的内容又不一样

我在用的过程中有如下困扰，有可能只对我算是个问题吧。
1.我需要分几次复制对我有意义的译文，不好进行操作。
2.假如德文翻成英文，有个英文单词我不知道意思，我复制这个单词到其他翻译器翻译，然后就。。。
当然，这只是对我来说这点不好，希望对你们有所帮助。

**Comment by elliottzheng** [comment]
你可以在设置页面关闭智能互译，这样就不会把翻译目标语言了，应该会有所帮助
