### ISSUE TITLE
[Features]希望能够在后台运行

### ISSUE THREAD

**Issue by gttwork** [CopyTranslator/CopyTranslator#127]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
感谢作者能够开发出如此优秀的免费软件！我一般用于其他软件中，场景是直接用译文替换英文，不需要任何窗口，只需在后台工作即可，希望能够考虑增加这个功能。

**描述您考虑过的替代方案**

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
我想这样子，下一个版本你可以通过这个方式来实现后台运行，第一步，将隐藏方向设置为 Minify，然后双击标题栏，就可以最小化到托盘了。
