### ISSUE TITLE
[Features]添加谷歌生物医学翻译

### ISSUE THREAD

**Issue by snailgc** [CopyTranslator/CopyTranslator#131]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
添加谷歌医学生物专业翻译

**描述您想要的解决方案**
现有版本对生物医学翻译还不是很好

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
这个不太可能单独为生物医学做，那每个学科都来，怎么可能呢

**Comment by snailgc** [comment]
现在有个类似的软件叫 知云 有这个功能，我试用了一下，翻译的准确程度的确比较高，主要是生物医学的词汇比较偏门啊，一般的翻译准确率的确是不高。

在 2019-06-18 16:56:11，"Elliott Zheng" <notifications@github.com> 写道：


这个不太可能单独为生物医学做，那每个学科都来，怎么可能呢

**Comment by elliottzheng** [comment]
我做的是通用的，现在主要任务是将软件正常使用的问题解决，这个得到后期才有可能做，后期做也是提供给用户类似 #32 的功能，而不会专门为生物医学做。没有软件是万能的，专门的软件做专门的事。

**Comment by jzq90** [comment]
其实这个功能还是很好的，把别的现成的专业词典拿过来用

**Comment by amongtheflowers** [comment]
请问谷歌生物医学翻译接口能告诉下么

**Comment by Baby-233** [comment]
知云那个，就是名字这样，实际上是用的腾讯翻译君  所以真没必要

**Comment by lmlm1995** [comment]
> 知云那个，就是名字这样，实际上是用的腾讯翻译君 所以真没必要

这样的？但是确实翻译出来的效果 比 百度的要好啊。我也是用 知云，而且选的是谷歌生物医药引擎。但是不知道是不是如你说的-知云实际调用了腾讯翻译君。

**Comment by Baby-233** [comment]
> 

是的，这个我没必要说假话，懂一点的抓包或者逆向一下软件就知道了，我也是感觉挺好的所以找了一下对应的网站，想要自己也能用，结果发现是腾讯翻译君

**Comment by Baby-233** [comment]
> > 知云那个，就是名字这样，实际上是用的腾讯翻译君 所以真没必要
> 
> 这样的？但是确实翻译出来的效果 比 百度的要好啊。我也是用 知云，而且选的是谷歌生物医药引擎。但是不知道是不是如你说的-知云实际调用了腾讯翻译君。



> > 知云那个，就是名字这样，实际上是用的腾讯翻译君 所以真没必要
> 
> 这样的？但是确实翻译出来的效果 比 百度的要好啊。我也是用 知云，而且选的是谷歌生物医药引擎。但是不知道是不是如你说的-知云实

> > 知云那个，就是名字这样，实际上是用的腾讯翻译君 所以真没必要
> 
> 这样的？但是确实翻译出来的效果 比 百度的要好啊。我也是用 知云，而且选的是谷歌生物医药引擎。但是不知道是不是如你说的-知云实际调用了腾讯翻译君。
是的，这个我没必要说假话，懂一点的抓包或者逆向一下软件就知道了，我也是感觉挺好的所以找了一下对应的网站，想要自己也能用，结果发现是腾讯翻译君

**Comment by Baby-233** [comment]
> > 知云那个，就是名字这样，实际上是用的腾讯翻译君 所以真没必要
> 
> 这样的？但是确实翻译出来的效果 比 百度的要好啊。我也是用 知云，而且选的是谷歌生物医药引擎。但是不知道是不是如你说的-知云实际调用了腾讯翻译君。

是的，这个我没必要说假话，懂一点的抓包或者逆向一下软件就知道了，我也是感觉挺好的所以找了一下对应的网站，想要自己也能用，结果发现是腾讯翻译君
