### ISSUE TITLE
windows10专业版下，翻译器Youdao无法切换成其他模式

### ISSUE THREAD

**Issue by binjf** [CopyTranslator/CopyTranslator#132]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

无法切换翻译器，翻译器为 Youdao，切换其他翻译器如 Google（其他翻译器也一样），保存后仍然为 Youdao。尝试过语言选择为 English，把可以打开的选项全部关闭，还是不能解决问题。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.3.0 b9cdd17 
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：如win10专业版 64位
 - 阅读器：chrome浏览器

**如何复现这个问题**
重现行为的步骤：
1. 打开设置，此时翻译器为 Youdao
2. 选择 Google 翻译器
3. 软件跳动一下保存，但是翻译器仍然为 Youdao

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/23567092/59336223-bd933a80-8d30-11e9-872c-2fb57ad8b160.png)

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by ZhuBaohe** [comment]
同样是win10 64位，v8.3.0版本，翻译器切换到Google弹出错误框
![a](https://user-images.githubusercontent.com/35796307/59477037-09a3c380-8e86-11e9-835f-0fdf2330326d.jpg)
