### ISSUE TITLE
字体出现随意变化现象

### ISSUE THREAD

**Issue by maud711** [CopyTranslator/CopyTranslator#133]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）
当翻译界面并没有显示在桌面最顶层，即没有选中软件时，不需要按住ctrl键，仅鼠标滚轮就会使字体变得很大，所以当选取了需要复制的文字后，点开软件字体会变得很大或者很小

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.3.0 x64版
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位
 - 阅读器：word，Adobe Acrobat DC
 - 出现问题的文档：使用时皆有
 - 出现问题的段落：使用时皆有

**如何复现这个问题**
重现行为的步骤：
1. 复制需要翻译的文字
2. 点开copytranslator
3. 字体会变得很大
4. ctrl+滚轮并不是每次都有用

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
如果出现这种情况，再按一下ctrl就行
