### ISSUE TITLE
在macOS下窗口无法释放的问题

### ISSUE THREAD

**Issue by Lettino** [CopyTranslator/CopyTranslator#135]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
在mac下打开软件后，有极大几率（并非100%）拖动窗口时，无法释放窗口，窗口将一直跟着鼠标，只能强制退出（command+q）
已经设置授权（仍然会提示需要授权）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：8.2.0
 - 出现问题时的模式：对照模式
 - 操作系统：mac OS 10.14
 - 阅读器：//
 - 出现问题的文档：//
 - 出现问题的段落：//

**如何复现这个问题**
重现行为的步骤：
1. 打开软件
2. 直接拖动窗口

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/17498937/59970993-2044cb80-95a6-11e9-8df6-0c7233c4ead2.png)
![image](https://user-images.githubusercontent.com/17498937/59971065-2a1afe80-95a7-11e9-9af0-55c348519976.png)

请截取主模式窗口
![image](https://user-images.githubusercontent.com/17498937/59971000-3ce10380-95a6-11e9-9251-835a7cde14ba.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
//

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
//

**Comment by elliottzheng** [comment]
v8.3.0在设置界面将 标题栏改为native

**Comment by char1eslu** [comment]
macOS下，该app占用奇高，经常50%以上
