### ISSUE TITLE
切换翻译源出错

### ISSUE THREAD

**Issue by Tcwxc** [CopyTranslator/CopyTranslator#136]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.3.0 x64 版
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 软件界面设置中切换翻译源会闪烁一下，然后选择无效（自动跳回Google），右下角图标右键选择后会跳这个错误
A JavaScript error occurred in the main
process
Uncaught Exception:
undefined:undefined

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**Comment by elliottzheng** [comment]
Duplicate of #132
