### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by lengmo1996** [CopyTranslator/CopyTranslator#137]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**
![QQ截图20190705153820](https://user-images.githubusercontent.com/40485465/60705956-f9d64700-9f3a-11e9-81f7-14e3288b2af8.png)

**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.3.0.0 x64 版
 - 出现问题时的模式：MainMode
 - 操作系统：如win10 64位

**如何复现这个问题**
重现行为的步骤：
1. double click the copytranslator.exe
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
Sorry, I can't reproduce the issue by double click the icon on the taskbar, but I did fix some bugs that might cause the js error. If the issue occurs again in the incoming version, feel free to reopen the issue.

**Comment by lengmo1996** [comment]
Thanks!
Although I don’t know what happened, this problem no longer appears in the
past few days.

Elliott Zheng <notifications@github.com> 于2019年7月14日周日 下午10:02写道：
