### ISSUE TITLE
搜狗翻译接口与线上结果不一致

### ISSUE THREAD

**Issue by cibiluozu** [CopyTranslator/CopyTranslator#140]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）
搜狗翻译接口内容与线上结果不一致
![image](https://user-images.githubusercontent.com/10922425/62105318-abfff500-b2d4-11e9-8e9e-f83c15573a2a.png)
![image](https://user-images.githubusercontent.com/10922425/62105341-b7532080-b2d4-11e9-8886-fc0de59fc9b6.png)
![image](https://user-images.githubusercontent.com/10922425/62105361-c1751f00-b2d4-11e9-968d-b010532c8a57.png)

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.3.0 x86 版
 - 出现问题时的模式：MainMode/ FocusMode都出现
 - 操作系统：win10 64位
 - 阅读器：chrome浏览器
 - 出现问题的文档：for the sake of simplicity
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 粘贴for the sake of simplicity即可出现

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/10922425/62105436-f1242700-b2d4-11e9-88de-ad0e7de703ce.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
未知

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
未知

**Comment by elliottzheng** [comment]
![图片](https://user-images.githubusercontent.com/22427645/62106619-3dbd3180-b2d8-11e9-9f80-106db1e8a60c.png)
![图片](https://user-images.githubusercontent.com/22427645/62106653-588fa600-b2d8-11e9-8db8-b2eff0aae52e.png)
已经定位到问题，由于你上面勾选了检测语言，而我是使用的百度翻译检测的语言，而好巧不巧这句话被检测成丹麦语，而丹麦语条件下搜狗翻译将它翻译为 敬简单之酒。下个版本就会修复这个问题。

**Comment by cibiluozu** [comment]
原来如此，谢谢~

**Comment by elliottzheng** [comment]
fixed by opentranslate/opentranslate#2
