### ISSUE TITLE
请求增加显示单词音标功能

### ISSUE THREAD

**Issue by zeronlee** [CopyTranslator/CopyTranslator#142]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
当我翻译单词的时候（专注模式），没有显示音标，专注模式字体过大。

**描述您想要的解决方案**
显示美英式音标，专注模式支持字体设置。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
![image](https://user-images.githubusercontent.com/6701474/62274357-4ea1aa80-b472-11e9-8683-7779120a3f05.png)

**Comment by elliottzheng** [comment]
1. 单词的音标，目前只有用百度翻译英文单词才可能有.
2. ctrl + 滚轮可以设置字体大小，使用指南里写得很明白了，请在提issue前先看使用指南，更高级的设置见[进阶设置](https://copytranslator.github.io/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%95%8C%E9%9D%A2%E6%A0%B7%E5%BC%8F-%E9%A3%8E%E6%A0%BC)

**Comment by zeronlee** [comment]
切换翻译器选项到百度的时候，应用界面刷新，跳回默认google,无法实现切换。

**Comment by elliottzheng** [comment]
已修复，尚未发布
