### ISSUE TITLE
v8.4.0有道翻译引擎仍然不能用

### ISSUE THREAD

**Issue by ZhuBaohe** [CopyTranslator/CopyTranslator#145]
**描述问题**
看了v8.4.0的更新说明，
“更新translation.js 修复 有道引擎无法使用的问题”
但是我这里仍然不能用，而在有道官网翻译没有问题。见下图：

![1](https://user-images.githubusercontent.com/35796307/63067002-78150880-bf3f-11e9-85fd-4e9b90916e30.jpg)

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.4.0
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位
 - 阅读器：chrome浏览器
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
以前版本也不能用

**Comment by elliottzheng** [comment]
opentranslate/opentranslate#2
