### ISSUE TITLE
[Features] 增加多种翻译结果对比功能

### ISSUE THREAD

**Issue by WangShanpeng** [CopyTranslator/CopyTranslator#150]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
无

**描述您想要的解决方案**
同样一段原文，使用不同的翻译平台同时翻译，然后将结果并排显示出来。
因为有的时候，单一的翻译结果可能不太准确，多个平台通过对比之后，会更加便于理解。

**描述您考虑过的替代方案**
无

**附加背景**
无

**Comment by happyangry** [comment]
支持

**Comment by xiaohuihui1024** [comment]
http://ixysoft.top/2019/07/15//translate/

**Comment by everxq** [comment]
双语对照标记 https://github.com/CopyTranslator/CopyTranslator/issues/459
