### ISSUE TITLE
CopyTranslator 8.4.0 搜狗翻译无反应

### ISSUE THREAD

**Issue by cibiluozu** [CopyTranslator/CopyTranslator#151]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：copytranslator-setup-8.4.0.exe
 - 出现问题时的模式：MainMode
 - 操作系统：如win10 64位
 - 阅读器：如 chrome浏览器，与浏览器无关，随便复制都会有
 - 出现问题的文档：与文本无关，随便复制都会有
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 下载copytranslator-setup-8.4.0.exe
2. 选择搜狗翻译，随便粘贴一句话 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![image](https://user-images.githubusercontent.com/10922425/63941726-c3cac480-ca9e-11e9-99ad-c965a796e92b.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都不能使用

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
没有，未再次测试旧版本

**Comment by cibiluozu** [comment]
额，请问作者是调用API的问题吗？好像这个问题一直没有得到修复.....

**Comment by elliottzheng** [comment]
一时半会修复不了，因为没空，还请见谅，先用其他的引擎吧，本身就是白嫖的，哪有可能保证稳定

**Comment by elliottzheng** [comment]
fixed by opentranslate/opentranslate#2
