### ISSUE TITLE
右键托盘图标，点击其他地方，菜单不消失

### ISSUE THREAD

**Issue by happyTonakai** [CopyTranslator/CopyTranslator#152]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
右键托盘图标激活设置菜单，点击系统的其他地方，菜单仍然存在，只有再次右键托盘图标才会消失

**描述您想要的解决方案**
在其他地方单击，激活菜单应该自动消失

**描述您考虑过的替代方案**
无

**附加背景**
无

**Comment by elliottzheng** [comment]
v10中已修复
