### ISSUE TITLE
styles.css中无法修改专注模式中的智能词典

### ISSUE THREAD

**Issue by happyangry** [CopyTranslator/CopyTranslator#154]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

修改styles.css中focus模式的字体，对智能词典中的字体无效

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：8.4.0
 - 出现问题时的模式：FocusMode
 - 操作系统：如win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 修改styles.css中专注模式的字体如下
```
.focusText {
    /*modify the style of the focus result textarea*/
    font-family: "CMU Serif", "微软雅黑";
}
```
2. 复制一个单词，激活智能词典

**问题出现时，当时的CopyTranslator的设置截图**

复制一段话的时候：
![TIM截图20190903193731](https://user-images.githubusercontent.com/21305646/64170298-61007100-ce82-11e9-83a7-fa8fd85c240e.jpg)

可以看到中英文均按照设置的字体正常显示

 复制一个单词的时候：
![TIM截图20190903193758](https://user-images.githubusercontent.com/21305646/64170312-68277f00-ce82-11e9-84a3-0c1a70fd6c59.jpg)

字体又变回默认了

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
无

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
未知

**Comment by elliottzheng** [comment]
词典的样式请 使用
.dict{
    font-family: "CMU Serif", "微软雅黑";
}
