### ISSUE TITLE
[Features]自动隐藏必须要先获取焦点再移开才可以隐藏

### ISSUE THREAD

**Issue by niuerbao** [CopyTranslator/CopyTranslator#155]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
复制后自动显示翻译结果,然后需要鼠标点击翻译窗口后移开,窗口才会自动隐藏.

**描述您想要的解决方案**
我只是想看下翻译结果,不想移动鼠标去点击窗口.能否在其他应用窗口点击鼠标后,翻译窗口就自动隐藏

**描述您考虑过的替代方案**
无。

**附加背景**
无。

**Comment by solgxb** [comment]
同求问题解决方案

**Comment by elliottzheng** [comment]
新版本应该是解决了，在自动显示之后，copytranslator会强制自动获取焦点，这样点下外面就会自动隐藏了。
