### ISSUE TITLE
增加最小化隐藏到任务栏右下角

### ISSUE THREAD

**Issue by winnie-weng** [CopyTranslator/CopyTranslator#158]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
当我点击关闭或最小化的时候，软件可以隐藏在任务栏右边的最小化图标里面，而不是在底边任务栏和最小化图标里同时出现。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
<img width="485" alt="微信图片_20190907155933" src="https://user-images.githubusercontent.com/55014192/64471814-847c3200-d188-11e9-84ae-06e73e56fdcb.png">

**Comment by elliottzheng** [comment]
设置->开关->隐藏任务栏

**Comment by winnie-weng** [comment]
非常感谢您的及时回复！谢谢设计了这款优秀的软件！

**Comment by hantaotaohan** [comment]
> 设置->开关->隐藏任务栏

ububtu18 i3wm 无法最小化到系统任务栏，求修复！另跨虚拟桌面的问题已经靠tray来解决了
