### ISSUE TITLE
腾讯电脑管家检测v8.4有病毒

### ISSUE THREAD

**Issue by zhouzhou84** [CopyTranslator/CopyTranslator#159]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
下载v8.4.exe后腾讯管家提示有病毒，要求删除

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v8.4.0 .4.0 window版

 - 操作系统：如win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 下载

**Comment by elliottzheng** [comment]
1. 从官网下载，没有病毒
2. 从别的地方，不知道
3. 没有病毒，反正我信了
