### ISSUE TITLE
对照模式，原文译文框高度可调

### ISSUE THREAD

**Issue by hqyyqh** [CopyTranslator/CopyTranslator#16]
**您的功能请求是否与问题有关？请描述一下.**

对于 TODO 下一步计划 第五点：**译文离原文有点远**，提供一个建议。

**问题描述**：原文框的高度最小值太大，在不需要大篇幅翻译的时候 (如下图)，原文框留白太多
[![1.jpg](https://i.loli.net/2018/12/11/5c0fa7931c7ec.jpg)](https://i.loli.net/2018/12/11/5c0fa7931c7ec.jpg)

**考虑的方案**：可以通过调节两个框的高度比，或者采用高度自适应的方式。
我觉得这个插件布局就很不错， Chrome 翻译扩展 [https://github.com/crimx/ext-saladict](https://github.com/crimx/ext-saladict)
[![3.jpg](https://i.loli.net/2018/12/11/5c0fa8fc3352f.jpg)](https://i.loli.net/2018/12/11/5c0fa8fc3352f.jpg)

[![5.jpg](https://i.loli.net/2018/12/11/5c0faa13bc7b8.jpg)](https://i.loli.net/2018/12/11/5c0faa13bc7b8.jpg)
[![4.jpg](https://i.loli.net/2018/12/11/5c0faa13a104b.jpg)](https://i.loli.net/2018/12/11/5c0faa13a104b.jpg)

**Comment by elliottzheng** [comment]
已加入 v0.0.8 计划中
