### ISSUE TITLE
怎么调整专注模式下的显示字体大小？

### ISSUE THREAD

**Issue by M1ddlzh** [CopyTranslator/CopyTranslator#161]
专注模式下字体太大了，请问怎么调小一点？

**Comment by elliottzheng** [comment]
@M1ddlzh ctrl+滚轮

**Comment by elliottzheng** [comment]
https://copytranslator.gitee.io/guide/8.4.0.html#双模式具体描述

两个模式均可通过Ctrl+滚轮进行字体缩放。@M1ddlzh
