### ISSUE TITLE
[Features]增加暗黑模式

### ISSUE THREAD

**Issue by Andrew-Pei** [CopyTranslator/CopyTranslator#164]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
https://medium.com/missive-app/make-your-electron-app-dark-mode-compatible-c23dcfdd0dfa

**Comment by elliottzheng** [comment]
新版本将支持暗黑模式
![image](https://user-images.githubusercontent.com/22427645/78625919-e720e200-78bf-11ea-885a-261a1b47614d.png)

**Comment by Andrew-Pei** [comment]
thanks so much



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Elliott Zheng <notifications@github.com&gt;
发送时间: 2020年4月7日 11:07
收件人: CopyTranslator/CopyTranslator <CopyTranslator@noreply.github.com&gt;
抄送: Andrew-Pei <2844490052@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CopyTranslator/CopyTranslator] [Features]增加暗黑模式 (#164)





 
新版本将支持暗黑模式
