### ISSUE TITLE
打开软件出现无响应问题

### ISSUE THREAD

**Issue by guoguoguilai** [CopyTranslator/CopyTranslator#166]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
当打开copytranlator的时候，提示无响应

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.4，v9.0
 - 出现问题时的模式：都打不开
 - 操作系统：如win10 64位
 - 阅读器：还没到阅读器那一步
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 打开软件后，就提示无响应
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

![image](https://user-images.githubusercontent.com/47267017/68603752-e5571c00-04e3-11ea-8dd8-bb2feb91489b.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都不可以

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
v8.4，v9.0都出现了这个问题，v8.3没有，但v8.3无法更改翻译器，每次改完之后刷新都会返回Google翻译

**Comment by tzhou2018** [comment]
遇到同样的问题

**Comment by ChangchaoXi** [comment]
我也遇到同样的问题了，求解！！！！

**Comment by ChangchaoXi** [comment]
> 我也遇到同样的问题了，求解！！！！
我刚刚重启了一下，就可以用了

**Comment by ChangchaoXi** [comment]
> 我也遇到同样的问题了，求解！！！！
我刚刚重启了一下电脑，就可以用了

**Comment by elliottzheng** [comment]
软件近乎重写，无法复现问题，如果新版本发布后有同样的问题欢迎重新打开issue
