### ISSUE TITLE
mac版本使用会无端端CPU占用过高，然后卡死

### ISSUE THREAD

**Issue by TKH666** [CopyTranslator/CopyTranslator#167]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
在使用中，会无端端的CPU占用很高，但是此时并没有复制文本，然后就打字很卡，此时只能退出软件

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：mac 版 8.4
 - 出现问题时的模式：专注模式
 - 操作系统：如mac catalina 10.15.1 (19B88)
 - 阅读器：PDF expert
 - 出现问题的文档：任何文档
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 不清楚
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

![image](https://user-images.githubusercontent.com/50897234/68730099-b84f5a00-0606-11ea-9619-76d7159ff1b3.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都是一样，好像是更新系统之前也有这个情况，会无端端CPU占用过高

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
这个是我第一次使用的版本，还不清楚之前的版本

**Comment by TKH666** [comment]
我发现了，原来是复制图片和一些文件的时候，监听模式下会cpu占用过高

**Comment by Lettino** [comment]
我也感觉是如这样  长时间使用 这个现象会愈发明显  是否存在内存泄漏的情况？windows下没有这样的情况

**Comment by elliottzheng** [comment]
软件近乎重写，无法复现问题，如果新版本发布后有同样的问题欢迎重新打开issue

**Comment by shelfofclub** [comment]
win平台，版本10.0.0和10.2.4也出现复制图片后十分卡顿。
软件处于专注模式+监听剪贴板+总是置顶
系统为win10 21h2 19044.2251
在启动本软件前使用win+shift+s，截图和草图，进行截图，截图保存在剪贴板中。
启动软件后，软件十分卡顿，任务栏图标右键菜单可以正常退出，从任务栏的窗口的右上角的叉也可以关闭。

另外，顺带问下，软件界面右上角没有关闭按钮，只有最小化的横杠，右键点击最小化的横杠可以关闭软件，不知这是正规的关闭方法，还是触发了bug导致软件崩溃？

**Comment by elliottzheng** [comment]
> win平台，版本10.0.0和10.2.4也出现复制图片后十分卡顿。 软件处于专注模式+监听剪贴板+总是置顶 系统为win10 21h2 19044.2251 在启动本软件前使用win+shift+s，截图和草图，进行截图，截图保存在剪贴板中。 启动软件后，软件十分卡顿，任务栏图标右键菜单可以正常退出，从任务栏的窗口的右上角的叉也可以关闭。
> 
> 另外，顺带问下，软件界面右上角没有关闭按钮，只有最小化的横杠，右键点击最小化的横杠可以关闭软件，不知这是正规的关闭方法，还是触发了bug导致软件崩溃？

@shelfofclub 
1. 这是bug，剪贴板里有图片时会导致这个问题，我在未发布的新版本里已经修复了。
2. 这是正规关闭方法，希望您在使用前先看下[使用指南](https://copytranslator.gitee.io/guide/10.2.4.html#%E7%95%8C%E9%9D%A2%E7%A4%BA%E6%84%8F%E5%9B%BE)，下个版本，软件会自带更多的使用提示以方便用户使用。

**Comment by shelfofclub** [comment]
谢谢回复。抱歉升级后没细看文档。 @elliottzheng
