### ISSUE TITLE
希望能够加入windows ink以及surface触控笔支持

### ISSUE THREAD

**Issue by wwjjhh1995** [CopyTranslator/CopyTranslator#17]
**surface平板看文献取词一直都是个非常让人头疼的问题。不知能否给您的工具适配一下surface pen的相关取词功能。**

**其具体实现方法类似于您的“点按复制”逻辑，surface pen可以方便的大范围选词，悬停于屏幕，然后就跳出翻译结果。（如果能适配surface pen的按钮功能就更棒了**

**如果能登陆Windows store就更更棒了**

**Comment by elliottzheng** [comment]
您好，我没有surface，听你这么说有点疑惑，是说在surface运行CopyTranslator不能通过surface pen来取词？还是现有软件有什么不足吗？还有就是可以冒昧地问下您从何处得知CopyTranslator的吗？

**Comment by liangTHU** [comment]
您好，感谢您开发这款软件，我使用surface pro4设备，surface主打的surface pen由于可以直接在pdf阅读器上书写对于做笔记非常方便，但是对于外文文献的阅读，单纯用surface pen移动触控点是不能像鼠标一样取词的（针对一般的软件，比如欧路词典，有道词典等），如下图
![image](https://user-images.githubusercontent.com/46717217/51192107-c9fd9d80-1920-11e9-871c-84600b961bd4.png)
surface pen是电磁笔，在移动的时候显示的是一个小十字，而非鼠标箭头，我不太懂这个和鼠标有什么本质上的区别导致其不能鼠标停留选词，如果CopyTranslator能解决这个问题就好了；
另外，surface pen上有一个按钮（适配surface pro4及更新版本的surface设备）此按钮使用情况多数是在触控笔激活到字迹书写状态（区别于选择文字状态），按住按钮在书写区域划圈可以以封闭曲线方式选中已经写的字迹，如果能在surface pen的使用中，将此功能转换为按住该按钮并在文中划动可以选择pdf文字进而直接调用CopyTranslator翻译（类似划词翻译），而不按住按钮仅仅是直接做笔记这样的使用体验就很好。不知1楼提出的想法是不是我说的这种情况。谢谢！

**Comment by elliottzheng** [comment]
两位，这个需求经过简单调研之后，发现似乎有一定的方法能够选中复制和黏贴，我无法测试，如果可以的话，您可以协助研究清楚吗。
而且由于我这边硬件条件的限制，难以开发这类应用，这类功能也并不是非常适合集成到CopyTranslator当中，也许可以单独拿出来做一个应用。（可能已经有人写过了也说不定）
当前我的主要任务是重写及重新设计CopyTranslator，个人精力优先，所以我将这项需求置于优先级比较低的，后续如果有时间的话，才会考虑。至于形式，可能会集成也可能会作为插件提供。
