### ISSUE TITLE
Mac8.4v无法从专注模式切回并调整设置

### ISSUE THREAD

**Issue by JayFu** [CopyTranslator/CopyTranslator#170]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
Mac切换至专注模式后无法切回对照模式

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.4.0版
 - 出现问题时的模式：专注模式
 - 操作系统：macOS Catalina 10.15
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 切换专注模式

**Comment by elliottzheng** [comment]
右键点击专注模式右下角的圆圈会出菜单可以切回去
