### ISSUE TITLE
不可用问题

### ISSUE THREAD

**Issue by Derryxu** [CopyTranslator/CopyTranslator#172]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.0, 8.4.0, 8.3.0 版
 - 出现问题时的模式：MainMode, FocusMode
 - 操作系统：win10 64位
 - 阅读器：Microsoft edge
 - 出现问题的文档：打开了好几篇论文都不可以
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 下载开始一直不能使用，自动复制或是手动复制都不可以用；
2. 8.3.0模式的时候有时候是复制不同的内容，翻译显示的一直都是一句话，其他时候就是没反应

在浏览器上都不可以用

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
试一下这个 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v9.0.0-beta2

**Comment by Derryxu** [comment]
可以用了，谢谢。
