### ISSUE TITLE
无法关闭窗口

### ISSUE THREAD

**Issue by happyTonakai** [CopyTranslator/CopyTranslator#173]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
右上角点关闭/在任务栏图标右键关闭/`Alt+F4` 都只能将窗口最小化，只有在系统托盘处右键关闭才能退出

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.0 beta2
 - 出现问题时的模式：所有模式
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 右上角点关闭
2. 在任务栏图标右键关闭
3. Alt+F4

**问题出现时，当时的CopyTranslator的设置截图**
N/A

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
N/A

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
v9.0.0 beta 无此问题

**Comment by elliottzheng** [comment]
这个是因为beta2里面 关闭即退出的选项默认为关闭，其实应该为打开，这个可以在 设置->开关里更改，新版本里 默认会是打开的
