### ISSUE TITLE
对照模式下的三个按钮无反应

### ISSUE THREAD

**Issue by happyTonakai** [CopyTranslator/CopyTranslator#174]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
对照模式下三个按钮”专注模式“、”翻译“、”设置“均无反应

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.0 beta2
 - 出现问题时的模式：MainMode
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 对照模式下点击“专注模式”
2. 点击“设置”
3. 修改文本框中文字，点击”翻译“

**问题出现时，当时的CopyTranslator的设置截图**
![微信截图_20191204210103](https://user-images.githubusercontent.com/21305646/70144956-fe657e00-16d9-11ea-967c-96b48c4dc192.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
N/A

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
v9.0.0 beta 无此问题

**Comment by elliottzheng** [comment]
是否重置了配置文件，如果没有重置，请尝试重置一下

**Comment by happyTonakai** [comment]
安装前只删除了`copytranslator.json`，这次全部删除后没有问题了。

另外还有一个问题，多次点击设置会出现多个设置窗口，无论是从对照模式中点击设置，还是从系统托盘处点击设置
![TIM截图20191204210923](https://user-images.githubusercontent.com/21305646/70145397-ee01d300-16da-11ea-9041-340a68f3ff63.png)

**Comment by elliottzheng** [comment]
这是特性（滑稽）
