### ISSUE TITLE
希望提供OCR翻译功能

### ISSUE THREAD

**Issue by suyin-long** [CopyTranslator/CopyTranslator#175]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
1.支持OCR翻译
2.用户可以自行选择安装位置

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
1.希望提供OCR翻译功能，有些东西是不能复制的，不如软件安装界面，这时候如果可以通过截屏，然后识别截屏的文字内容并加以翻译就完美了。
2.希望可以用户可以选择软件安装位置

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
OCR翻译链接：https://www.52pojie.cn/thread-860382-1-1.html

**Comment by elliottzheng** [comment]
第一，OCR功能，其实8.4就已经提供了这个功能，你可以打开设置，OCR设置，**里面填上百度文字识别的API KEY**,设置好后可以
![](https://s2.ax1x.com/2019/12/10/Q0oLUf.gif)
调用QQ或任意截图工具的截图功能，copytranslator检测到剪贴板变化，会从剪贴板读取图片，进行翻译

第二，9.0.0 版本已经可以选择安装路径，现在已经开放用户测试

**Comment by suyin-long** [comment]
多谢回复！给你star！

**Comment by suyin-long** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        还有个问题，怎么设置让它翻译后自动显示到最上层。
        比如：截屏后自动翻译，然后弹出翻译后内容，让人可以直接看到，而不是去点击软件查看。试了一下总是置顶这个功能，不太理想，想要的是平时在后台，识别到内容后置顶。比如：检测到复制，然后将翻译的内容置顶；检测到截屏，将OCR识别的内容翻译后置顶！
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                jn15168896730
                            
                    
                        
                            
                                    jn15168896730@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年12月10日 08:58，Elliott Zheng<notifications@github.com> 写道： 


Closed #175.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by elliottzheng** [comment]
看下自动隐藏，自动显示 https://copytranslator.gitee.io/guide/8.4.0.html#%E8%AE%BE%E7%BD%AE-%E9%80%89%E9%A1%B9%E6%8F%8F%E8%BF%B0，希望在提问前要看文档，不然沟通很低效

**Comment by suyin-long** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        看到了，它弹出来的比较慢，所以没等它他出来我就点击打开软件了，因此没看效果。
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                jn15168896730
                            
                    
                        
                            
                                    jn15168896730@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年12月10日 15:58，Elliott Zheng<notifications@github.com> 写道： 


看下自动隐藏，自动显示 https://copytranslator.gitee.io/guide/8.4.0.html#%E8%AE%BE%E7%BD%AE-%E9%80%89%E9%A1%B9%E6%8F%8F%E8%BF%B0，希望在提问前要看文档，不然沟通很低效



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
