### ISSUE TITLE
Windows10中用ALT+TAB切换窗口后copytranslator的窗口位置会有微弱的偏移

### ISSUE THREAD

**Issue by paopjian** [CopyTranslator/CopyTranslator#176]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.4.0 x86 版
 - 出现问题时的模式：对照模式与专注模式
 - 操作系统：win10 64位
 - 阅读器：不清楚
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 最大化 CopyTranslator 窗口
2. 使用任意其他软件窗口到前端
3. ALT+TAB切换到CopyTranslator
4. CopyTranslator会"向下还原" 但窗口大小不变,总体向左上方偏移20像素左右

**问题出现时，当时的CopyTranslator的设置截图**
无法
请截取主模式窗口
![image](https://user-images.githubusercontent.com/20377352/70472551-2cc2cf00-1ac7-11ea-8d86-6aa40c10720b.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
无

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
没用过

**Comment by jingboxjtu** [comment]
我也发现有这个情况。  今天的9.0.0正式版，和以前的beta2都有。   
每次需要自己挪动一下，不然内容第一个字被挡住了。

**Comment by ravenxrz** [comment]
@elliottzheng 我也发现了这个问题。下面是我录制的gif，CopyTranslator会逐渐将左边adobe的"x"盖住，希望能够修复，感谢。
![](https://pic.downk.cc/item/5e8ef5cd504f4bcb044b8010.gif)

**Comment by elliottzheng** [comment]
v10中暂未发现此问题，如果新版本发布后有这个问题欢迎重新打开issue

**Comment by paopjian** [comment]
经过测试,问题仍然存在

**Comment by elliottzheng** [comment]
> 经过测试,问题仍然存在,请继续修复

已经说了是v10里面没发现，v9不会再修复。
