### ISSUE TITLE
9.0.0 beta2 有 macOS 版本吗？

### ISSUE THREAD

**Issue by lzw429** [CopyTranslator/CopyTranslator#177]
9.0.0 beta2 的版本更新说明中有 macOS 版本的描述，但实际上 GitHub 仓库的 release 中并没有 dmg 文件。
请问 9.0.0 beta2 有对应的 macOS 版本吗，或者是否有其他下载渠道？谢谢。

**Comment by elliottzheng** [comment]
实际上beta版本都不会放出mac版本

**Comment by elliottzheng** [comment]
不过，这两天正式版就会出来了，只差文档没有完善了
