### ISSUE TITLE
启动报错A javaScript error occurred in the main process

### ISSUE THREAD

**Issue by pjgao** [CopyTranslator/CopyTranslator#179]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
启动即报错，A javaScript error occurred in the main process，syntaxError: unexpected token < in JSON at position 0。公司内网环境。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v9.0.0 x64 版
 - 出现问题时的模式：全部
 - 操作系统：如win10 64位
 - 阅读器：全局
 - 出现问题的文档：全局
 - 出现问题的段落：全局

**如何复现这个问题**
重现行为的步骤：
1. 打开copytranslator即出现

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/22350313/70903226-6486c500-2039-11ea-96eb-1b60a639e977.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
全部都是
**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
没有

**Comment by elliottzheng** [comment]
9.0.0 正式版未发布，过时的预览版本问题不再处理

**Comment by pjgao** [comment]
经测试，下载了8.3版本的和v0.0.8-Zouwu-RC5，都出现类似的问题。
![image](https://user-images.githubusercontent.com/22350313/70997093-2fe53d00-210f-11ea-9383-5f11d546aaf4.png)
