### ISSUE TITLE
对含有i.e.文本，不能监听剪切板并翻译。

### ISSUE THREAD

**Issue by jingboxjtu** [CopyTranslator/CopyTranslator#180]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.0-beta2
 - 出现问题时的模式：MainMode
 - 操作系统：win10 64位
 - 阅读器：阅读器是福昕，但没关系，从任意地方复制出来都是
 - 出现问题的文档：
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 复制一段普通的英文例如“i'm fine”,软件检测剪切板，并正确翻译出结果。
2. 尝试复制‘’i.e. i'm not fine‘’,发现软件没有反应。
3. 复制任意一段论文，如果中间夹杂有i.e.，不能自动检测剪切板并翻译。

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/48880729/70994039-463bca80-2108-11ea-93dd-a4521695a4c5.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
已经修复

**Comment by jingboxjtu** [comment]
大佬牛逼~

Elliott Zheng <notifications@github.com> 于2019年12月18日周三 下午7:42写道：
