### ISSUE TITLE
更新版本时，新版本安装包已停止工作

### ISSUE THREAD

**Issue by frigee** [CopyTranslator/CopyTranslator#183]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
从8.4.0版本更新至9时，软件在专注模式下打开9.0安装包，显示：Foreign language assisted reading and translation solution 已停止工作 ，软件无法打开，并且使用8.3安装包也无法安装

问题事件名称:	APPCRASH
  应用程序名:	copytranslator-setup-9.0.0.exe
  应用程序版本:	9.0.0.0
  应用程序时间戳:	5a6fed7c
  故障模块名称:	System.dll
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5a6fed15
  异常代码:	c0000005
  异常偏移:	00001581
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：8.3.0
 - 出现问题时的模式：专注模式
 - 操作系统：win 7 64位

**如何复现这个问题**
重现行为的步骤：
1.  打开9.0安装包

**Comment by elliottzheng** [comment]
试着先卸载旧版本，然后再重新下载安装，要么下载.exe 安装，要么直接下载zip解压打开copytranslator.exe

https://github.com/CopyTranslator/CopyTranslator/releases/tag/v9.0.0

**Comment by frigee** [comment]
您好，我是在卸载之后安装的，右侧是安装不上的软件，左侧是刚刚下载的exe文件，可以安装，但是安装上后双击软件，指针转两圈之后就没有反应了，无法运行
在更新前，8.3.0版本运行无问题，但进入专注模式后右下角只有小绿点，我不知道怎么返回主界面。这时我更新了9.0版本，软件就显示出故障了（我记不清具体是什么了），弹出了个对话框，这时8.3和9.0版本都无法打开了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elliott Zheng"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 晚上6:49
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com&gt;; 
抄送: "lixagon"<136152190@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 更新版本时，新版本安装包已停止工作 (#183)




试着先卸载旧版本，然后再重新下载安装，要么下载.exe 安装，要么直接下载zip解压打开copytranslator.exe
 
https://github.com/CopyTranslator/CopyTranslator/releases/tag/v9.0.0

**Comment by elliottzheng** [comment]
两版本不可共存，你把旧的删了，安装新的。
刚才都说了，打不开.exe 你就下载zip解压直接打开软件。
都是靠猜的来用软件的，我写了好久的使用说明可以麻烦您看一眼吗？

**Comment by frigee** [comment]
老哥，我已经把旧的软件8.3和9.0版本卸载了，解压了9.0的zip，直接运行exe文件，鼠标会转圈，但是软件打不开


ps：非常感谢老哥的帮助，copytranslater真的很好用，9.0出了之后非常期待能用上新版本
使用说明我没找到在哪里。。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elliott Zheng"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 晚上7:12
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com&gt;; 
抄送: "lixagon"<136152190@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 更新版本时，新版本安装包已停止工作 (#183)




两版本不可共存，你把旧的删了，安装新的。
 刚才都说了，打不开.exe 你就下载zip解压直接打开软件。
 都是靠猜的来用软件的，我写了好久的使用说明可以麻烦您看一眼吗？

**Comment by elliottzheng** [comment]
确保杀毒软件是关闭的
先删除 c:/users/你的用户名/copytranslator

CMD到安装目录下，然后copytranslator.exe 然后把命令行的输出贴到这里来

如何找到使用说明，我随便列举几个位置吧：

![image](https://user-images.githubusercontent.com/22427645/71172115-61d6da80-229a-11ea-9510-41eda2313023.png)
![image](https://user-images.githubusercontent.com/22427645/71172184-892da780-229a-11ea-8968-1930a59d38ad.png)
![image](https://user-images.githubusercontent.com/22427645/71172152-787d3180-229a-11ea-825c-3e54c1568a78.png)
![image](https://user-images.githubusercontent.com/22427645/71171875-cc3b4b00-2299-11ea-92fa-033bb976ca3d.png)
![image](https://user-images.githubusercontent.com/22427645/71171960-fab92600-2299-11ea-92df-029be02ad389.png)
![image](https://user-images.githubusercontent.com/22427645/71171983-0d335f80-229a-11ea-8354-1622151e84ae.png)
![image](https://user-images.githubusercontent.com/22427645/71172072-4cfa4700-229a-11ea-987d-bb204014d4b0.png)

**Comment by frigee** [comment]
那个。。 使用说明里并没有看到要先卸载原来的软件再装啊，也没看到和我的问题相关的信息





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elliott Zheng"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 晚上8:08
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com&gt;; 
抄送: "lixagon"<136152190@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 更新版本时，新版本安装包已停止工作 (#183)




确保杀毒软件是关闭的
 先删除 c:/users/你的用户名/copytranslator
 
CMD到安装目录下，然后copytranslator.exe 然后把命令行的输出贴到这里来
 
如何找到使用说明，我随便列举几个位置吧：

**Comment by elliottzheng** [comment]
我想帮你，但是请你给点有用的信息，让我来帮你解决这个问题。请按照我上一条回复说的来做，把输出贴到这里来。
我说你不看使用说明，是因为你说你不知道怎么切换回对照模式，不是因为使用说明里有你不能用的解决方案。

**Comment by frigee** [comment]
我这样做可以吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elliott Zheng"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 上午10:23
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com&gt;; 
抄送: "lixagon"<136152190@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 更新版本时，新版本安装包已停止工作 (#183)




我想帮你，但是请你给点有用的信息，让我来帮你解决这个问题。请按照我上一条回复说的来做，把输出贴到这里来。
 我说你不看使用说明，是因为你说你不知道怎么切换回对照模式，不是因为使用说明里有你不能用的解决方案。

**Comment by elliottzheng** [comment]
![image](https://user-images.githubusercontent.com/22427645/71230925-87a9c100-2326-11ea-8730-8ce1e6857ce2.png)
你说什么

**Comment by frigee** [comment]
[我是用qq邮箱回复的，前两次都贴了图片，但没有显示
![QQ截图20191220102941](https://user-images.githubusercontent.com/47060020/71242373-c94b6380-2348-11ea-964e-a936be784825.png)

**Comment by elliottzheng** [comment]
看不出啥来，如果可以使用旧版本的话可以删除掉 c:/users/你的用户名/copytranslator，继续使用旧版本
