### ISSUE TITLE
专注模式翻译结果错误,与对照模式不同

### ISSUE THREAD

**Issue by paopjian** [CopyTranslator/CopyTranslator#184]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.0 x86
 - 出现问题时的模式：专注模式
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：" more generic solution "

**如何复现这个问题**
重现行为的步骤：
1. 使用对照模式翻译这句话
2. 使用专注模式翻译这句话
3. 专注模式只翻译了more

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![image](https://user-images.githubusercontent.com/20377352/71308631-01a97b00-23f7-11ea-827d-0efa29ce6af7.png)
![image](https://user-images.githubusercontent.com/20377352/71308637-0b32e300-23f7-11ea-9714-096d370e19d1.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
仅新版本

**Comment by elliottzheng** [comment]
智能词典会自动在小于等于三个词的英文时自动启用，专注模式里会显示查词引擎的结果，而对照模式里依然显示翻译引擎的结果，查词引擎和翻译引擎查出来的结果不同是正常现象，如果你不想查词，请到设置-》开关里关闭智能词典。
而查词引擎只查询了more这个确实是问题，我会再看下。

**Comment by elliottzheng** [comment]
新版本未发现此问题，如果出现，可以重新打开此issue
![image](https://user-images.githubusercontent.com/22427645/119917084-68da4000-bf98-11eb-94bc-44f6924c1305.png)
