### ISSUE TITLE
在shortcuts.json中设置完快捷键后再打开会失效

### ISSUE THREAD

**Issue by lc461184174** [CopyTranslator/CopyTranslator#185]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.0
 - 出现问题时的模式：两种模式
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
在shortcuts.json中设置完快捷键后，第二次打开软件，快捷键绑定失效，shortcuts.json中的设置消失。安装版和绿色版都会这样。

**问题出现时，当时的CopyTranslator的设置截图**
无

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
在9.0.0之前没有这个问题

**Comment by elliottzheng** [comment]
已经修复了，等一下这个issue关闭之后，会放一个9.0.1 到github release，因为有些标识符改了，你需要查看[动作系统](https://copytranslator.github.io/guide/9.0.0.html#%E5%8A%A8%E4%BD%9C%E7%B3%BB%E7%BB%9F) 来了解最新的动作标识符
