### ISSUE TITLE
windows安装包被windows defender认为是不安全文件

### ISSUE THREAD

**Issue by Revan-github** [CopyTranslator/CopyTranslator#186]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
下载安装包后，edge insider浏览器认为安装包有害。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.1&9.0.0
 - 出现问题时的模式：并非使用问题
 - 操作系统：win10 64位
 - 阅读器：edge insider
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
选择信任，或者不要使用。
