### ISSUE TITLE
macOS版精簡模式下無法縮放字體大小

### ISSUE THREAD

**Issue by JamesLi0623** [CopyTranslator/CopyTranslator#193]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.4.0
 - 出现问题时的模式：FocusMode
 - 操作系统：macOS 10.15 64bit
 - 阅读器：all environment 
 - 出现问题的文档：無關
 - 出现问题的段落：無關

**如何复现这个问题**
重现行为的步骤：
1. 於macOS中開啟 CopyTranslator v8.4.0
2. 切換至精簡模式
3. 選取任一段文字進行翻譯
4. 於 CopyTranslator 視窗中點擊譯文，嘗試使用「'cmd' + '+'or'滾輪'」與「'control' + '+'or'滾輪'」均無法正常縮放字體

**问题出现时，当时的CopyTranslator的设置截图**
<img width="1536" alt="截圖 2020-01-15 下午10 42 35" src="https://user-images.githubusercontent.com/35157744/72442916-566ac680-37e8-11ea-8ae3-72b53af5f1e4.png"> 
<img width="1536" alt="截圖 2020-01-15 下午10 41 32" src="https://user-images.githubusercontent.com/35157744/72442839-33d8ad80-37e8-11ea-833d-0259e4368cd9.png">

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
與瀏覽器環境無關，但透過自行修改 "/Users/userName/copytranslator/copytranslator.json" 可成功調整字體大小，故非嚴重影響的問題，建議可暫時在使用說明新增mac版透過修改JSON檔的方式方便其他使用者調整大小

開發者們辛苦了，感謝您們提供這麼好的工具，期待 v9.0 的mac版早日release

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
会新加一个局部快捷键ctrl+,ctrl- 缩放文本大小
