### ISSUE TITLE
[Bugs]升级时本地化设置重置

### ISSUE THREAD

**Issue by davidxuang** [CopyTranslator/CopyTranslator#195]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**描述问题**

在最近试图将软件推到 [scoop-extras](https://github.com/lukesampson/scoop-extras) 软件仓库时遇到了问题。由于仓库主要面向国际用户，所以要求软件能够识别系统默认语言或者默认以英语运行；但在尝试覆写配置文件修改 locale 的时候，发现每次升级时 locale 均会被重置，而配置文件中必需的 version 字段并不遵从一定的规律，这给安装脚本的编写带来了困难，仓库的自动维护脚本也无法处理这样的逻辑，也使软件的本地化形同虚设。在此请求，在升级时保留语言相关的设置项，或者在每次重置设置项的时候由系统语言判断显示语言（zh-SG→zh-CN; zh-MO, zh-HK→zh-TW; others→en）。附上尝试添加软件的 PR [链接](https://github.com/lukesampson/scoop-extras/pull/3449)。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.0 / 9.0.1
 - 出现问题时的模式：N/A
 - 操作系统：Windows 10 64bit
 - 阅读器：N/A
 - 出现问题的文档：N/A
 - 出现问题的段落：N/A

**如何复现这个问题**
重现行为的步骤：
1. 安装或升级软件时。
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
软件语言之后会是固定的，之前换是因为换了核心翻译库，为了省事就和那个保持一致了。
这个意思是说，只要我根据系统的语言设置默认语言就行喽，你也不需要写额外的东西是这样吗？

**Comment by davidxuang** [comment]
> 软件语言之后会是固定的，之前换是因为换了核心翻译库，为了省事就和那个保持一致了。
> 这个意思是说，只要我根据系统的语言设置默认语言就行喽，你也不需要写额外的东西是这样吗？

是的，这样就可以了。

**Comment by elliottzheng** [comment]
新版本区域设置将默认为auto，在auto状态下，语言将为系统默认语言。
