### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yishunxin** [CopyTranslator/CopyTranslator#196]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
启动copytranslator报错，缺少模块

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v.9.0.0
 - 出现问题时的模式：
 - 操作系统：win10 64位
 - 阅读器：
 - 出现问题的文档：
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 下载copytranslator-setup-9.0.0.exe
2. 安装完成
3. 启动copytranslator
4. 报错

**问题出现时，当时的CopyTranslator的设置截图**

![image](https://user-images.githubusercontent.com/26456177/72867224-134e9e80-3c93-11ea-8323-3aa986af294e.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
不知道

**Comment by elliottzheng** [comment]
安装路径不要带空格，可以尝试直接安在C盘根目录下

**Comment by elliottzheng** [comment]
参看 #235
