### ISSUE TITLE
8.3.0版本未能彻底卸载且不能再次安装

### ISSUE THREAD

**Issue by qq1962572025** [CopyTranslator/CopyTranslator#199]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v8.3.0  x86 版
 - 出现问题时的模式：卸载时出现问题
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 安装9.0.1版本后，8.3.0版本仍然在控制面板中可见，且不能卸载。在注册表中也找不到对应数据
2. 同时也无法再次安装8.3.0版本
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

![image](https://user-images.githubusercontent.com/40595559/73229295-322dc300-41b4-11ea-9122-99eeb0be9e06.png)

![image](https://user-images.githubusercontent.com/40595559/73229304-3ce85800-41b4-11ea-972f-67cf36e5f906.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
直接删除copytranslator的安装目录即可
