### ISSUE TITLE
复制翻译反应很慢，复制完后大概需要20秒才能翻译出来

### ISSUE THREAD

**Issue by PikakueNNZ** [CopyTranslator/CopyTranslator#202]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.1 x64 版
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：win10 64位
 - 阅读器：acrobat
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 选中一段文字
2. Ctrl+C
3. copytranslator没有变化
4. 大概20秒后，出现翻译

**问题出现时，当时的CopyTranslator的设置截图**

![Snipaste_2020-02-07_12-11-33](https://user-images.githubusercontent.com/40914469/74000420-0aeca800-49a3-11ea-87ab-057244b7904d.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

所有地方都存在问题

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by WiLngDo** [comment]
我也出现这个情况了，不知道是什么问题

**Comment by Yilifanghaishui** [comment]
我也是...突然就这样了。  而且重装也没用，最重要是设置点不开了

**Comment by Yilifanghaishui** [comment]
> 我也出现这个情况了，不知道是什么问题

你解决了吗，哥

**Comment by Yilifanghaishui** [comment]
切换其他引擎可以例如百度可以  google引擎很慢  卡住15秒

**Comment by WiLngDo** [comment]
和有道不兼容，关掉有道就好了


签名由网易邮箱大师定制
在2020年3月22日 08:51，Yilifanghaishui<notifications@github.com> 写道：

我也出现这个情况了，不知道是什么问题

你解决了吗，哥

**Comment by cikexintiaoub** [comment]
> 和有道不兼容，关掉有道就好了 签名由网易邮箱大师定制 在2020年3月22日 08:51，Yilifanghaishui<notifications@github.com> 写道： 我也出现这个情况了，不知道是什么问题 你解决了吗，哥 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

并不，我关闭了有道，依然有这个问题

**Comment by Wu-X** [comment]
可能和其他软件有冲突。我打开Veee但没有连接也出现了这种情况，关闭Veee后，复制文本就有翻译。
