### ISSUE TITLE
在文献中复制后，文字不会出现在软件中，且不能正常翻译

### ISSUE THREAD

**Issue by WiLngDo** [CopyTranslator/CopyTranslator#203]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.1 x64 版
 - 出现问题时的模式：MainMode
 - 操作系统：如win10 64位
 - 阅读器：Adobe acrobat

**如何复现这个问题**
重现行为的步骤：
1. 复制文献内容
2. copytranslator不识别，不能自动粘贴
3. 手动粘贴后，点击翻译，文字清空
4. 复制的文字任然是有格式的形式，不能去除格式

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![image](https://user-images.githubusercontent.com/45672157/74096360-db6fa400-4b38-11ea-9bcb-e30276d2cff9.png)
![image](https://user-images.githubusercontent.com/45672157/74096364-e7f3fc80-4b38-11ea-85b6-3dbdf83c6533.png)
![image](https://user-images.githubusercontent.com/45672157/74096366-f215fb00-4b38-11ea-9253-adacfe7894eb.png)
![image](https://user-images.githubusercontent.com/45672157/74096370-f80bdc00-4b38-11ea-916e-3b16befd6724.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

都不可以
**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
感觉比较大概率是您的网络问题，您可以切换其他引擎，或者是看一下专注模式里，翻译状态指示是否为红色，如果为红色，则有很大可能因为网络问题翻译失败
