### ISSUE TITLE
[Features]如果可能请加入百度翻译的专业领域垂直翻译API接口，像百度OCR那种，感谢你的作品！

### ISSUE THREAD

**Issue by Ricco-L** [CopyTranslator/CopyTranslator#204]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
您好，非常感谢您的作品！
       一些生物医药、计算机、水利工程的论文需要使用百度的专业垂直翻译引擎，多以能否添加这个功能使得翻译软件可以被更多的专业领域人士使用。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
      如果可以请添加百度OCR那样的百度翻译API接口，只需要填写APPID 、secretKey、domain。即可使用自己申请的专业领域翻译接口。
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
         如上所述，百度翻译开放平台有详细的垂直翻译API文档，由于我自己是生物医药方面的使用者，非常非常希望您可以添加此功能，如果您添加这个功能，您的软件将被大量专业人士使用，目前市面上没有替代品，没有翻译软件在用百度的垂直专业翻译接口。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
      再次感谢您的无私开源，您的软件真是我们看论文的神器！

**Comment by elliottzheng** [comment]
你好，我会尝试接入的

**Comment by Ricco-L** [comment]
非常感谢您！

发自我的iPhone

**Comment by elliottzheng** [comment]
https://github.com/OpenTranslate/OpenTranslate/pull/14

**Comment by SnailDove** [comment]
> 百度的专业垂直翻译引擎

附议+1
