### ISSUE TITLE
“总是置顶”选项重新打开时不起作用

### ISSUE THREAD

**Issue by M1ddlzh** [CopyTranslator/CopyTranslator#205]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
打开软件-设置为“总是置顶”-设置成功-关机重新启动-打开软件-总是置顶不起作用-但是“总是置顶”选项是打了对勾的。每次开机使用都需要手动关闭“总是置顶”，然后再勾选“总是置顶”才行。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.1 win zip版
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 打开软件并勾选“总是置顶”
2. 使用完后关闭电脑，并重开机
3. 打开软件
4. 打开另一个软件，此时总是置顶不起作用

**问题出现时，当时的CopyTranslator的设置截图**
无

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
无

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
之前的版本没有，如8.4.0

**Comment by woodenpi** [comment]
请问关闭该问题是因为已经解决了吗？我跟您遇到了相同的问题，如果您已解决，还麻烦分享一下解决办法，非常感谢~

**Comment by M1ddlzh** [comment]
> 请问关闭该问题是因为已经解决了吗？我跟您遇到了相同的问题，如果您已解决，还麻烦分享一下解决办法，非常感谢~

没有解决。有一天我使用的时候偶然可以正常置顶，还以为bug修复了，因此就关了，后来发现还是存在这个问题。QAQ
