### ISSUE TITLE
使用Edge打开PDF文件，随后使用CopyTranslator进行复制翻译时，出现单词间无空格

### ISSUE THREAD

**Issue by zxgm** [CopyTranslator/CopyTranslator#207]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**使用Edge打开PDF文件，随后使用CopyTranslator进行复制翻译时，出现单词间无空格**

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：copytranslator-setup-9.0.0.exe
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位
 - 阅读器：Edge浏览器
 - 出现问题的文档：无
 - 出现问题的段落：无
**如何复现这个问题**
重现行为的步骤：
1. 使用Edge打开PDF
2. 复制PDF的英文句子
3. 看CopyTranslator中单词间隔无空格

**问题出现时，当时的CopyTranslator的设置截图**
无

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
无

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
无

**Comment by happyTonakai** [comment]
使用 Edge Chromium 没有发现这个问题，你可以先试试粘贴一下复制的内容，说不定剪贴板里的内容本来就没有空格呢

**Comment by elliottzheng** [comment]
如果方便的话提供一下出错的PDF，以及出错的段落，方便我定位问题。
