### ISSUE TITLE
标题栏邮件后弹出菜单无法消除

### ISSUE THREAD

**Issue by huangqi412** [CopyTranslator/CopyTranslator#208]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
普通模式或专注模式，在软件菜单栏右键，会弹出移动&最小化&最大化&关闭，这个菜单会一直存在挡着后面，不会消失，也无法点选。

**系统环境（请填写以下信息）：**
 9.00版
对照模式和专注模式都会
WIN10 X64

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
Duplicate of #152
