### ISSUE TITLE
[Features] 请求加入在手动输入单词后回车自动查词的功能

### ISSUE THREAD

**Issue by Qm-jmz** [CopyTranslator/CopyTranslator#211]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。
今天在电脑上一边听网课一边查词，比如视频里出现了不认识的词，我这时不能够直接复制，所以需要手动输入。但是在我输入后总是需要按一下翻译的按钮，或者在旁边打开一个空白的文本文档输入单词然后ctrlA+C，整个过程会很繁琐。如果可以增加以回车代替按翻译键的功能，就可以简化一步操作，提升易用性

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
输入单词，回车，出现结果。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
如果可以增加以回车代替按翻译键的功能，就可以简化一步操作，提升易用性。
或者，利用listaray和everything之类的搜索框软件，实现对翻译器的调用 。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by Qm-jmz** [comment]
比如类似listrary调用goldendict的做法那样

**Comment by elliottzheng** [comment]
这个功能应该可以满足你的需求：
![image](https://user-images.githubusercontent.com/22427645/75400617-bfdb0a80-593a-11ea-9c8d-f0b2dad08764.png)
建议你提issue之前先看下使用说明

**Comment by Qm-jmz** [comment]
> 这个功能应该可以满足你的需求：
> ![image](https://user-images.githubusercontent.com/22427645/75400617-bfdb0a80-593a-11ea-9c8d-f0b2dad08764.png)
> 建议你提issue之前先看下使用说明

不好意思哈，谢谢了
