### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by imbaBBQ** [CopyTranslator/CopyTranslator#212]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
无法运行程序

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v9.0.0
 - 出现问题时的模式：运行时
 - 操作系统：如win10 64位
 - 阅读器： chrome浏览器,https://github.com/copytranslator/copytranslator/releases
 - 出现问题的文档：
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 运行程序
2. 出现弹窗
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**
![copy](https://user-images.githubusercontent.com/61608362/75599591-56e1c700-5ae1-11ea-8b8a-f1cec2ec0c84.png)

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
无

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
8.3.0

**Comment by elliottzheng** [comment]
你好，你先尝试一下v9.0.2的，安装路径中不要含有中文或空格，最好在安装之前关闭杀毒软件啥的，如果仍有问题，请将您的copytranslator安装文件夹压缩后发给我。
