### ISSUE TITLE
第一次下载使用异常卡顿

### ISSUE THREAD

**Issue by taoleee** [CopyTranslator/CopyTranslator#213]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
第一次使用，安装完成后打开发现软件性能异常，点击设置响应时间过长，无法正常使用。
拖动窗口也几乎无反应，非常的卡顿。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.1 预览版
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位
 - 阅读器：暂未使用
 - 出现问题的文档：第一次下载还未使用
 - 出现问题的段落：第一次下载还未使用

**如何复现这个问题**
重现行为的步骤：
1. 第一次下载安装完成后打开
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

第一次打开时的默认设置

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
提供的信息无法定位问题
