### ISSUE TITLE
快捷键编辑使用“translate”动作无效

### ISSUE THREAD

**Issue by aaron021512** [CopyTranslator/CopyTranslator#218]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
我在MainMode模式下，打中文不能直接翻译英文，要鼠标点击下“翻译”，所以准备设置一个快捷键Ctrl+Enter 触发"translate"动作，但是发现无论怎么改快捷键的组合，只要是"translate"动作加入脚本localShortcuts.json里，启动界面就不正常，而且快捷键也无效（见附件）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.1
 - 出现问题时的模式：MainMode/ FocusMode 都有
 - 操作系统：win10 64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 使用我提供的localShortcuts.json 脚本，启动程序即可
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![Image of Yaktocat](http://aaron.brandsh.cn/_20200320133004.png)

问题localShortcuts.json下载:
[下载](http://aaron.brandsh.cn/localShortcuts.json)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
与阅读器无关

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
只用过这个版本

**Comment by elliottzheng** [comment]
确实是个bug哈哈，我发现尽管我定义了translate这个标识符，但是实际上并没有对应的Action，下个版本会修复。
