### ISSUE TITLE
[Features] 请求增加对Latex公式的支持，翻译过程中能跳过不翻译

### ISSUE THREAD

**Issue by Oneliey** [CopyTranslator/CopyTranslator#221]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**

在需要翻译的部分中有公式时，就会出现许多乱码

**描述您想要的解决方案**

请求增加对Latex公式的支持
1. 过程中能跳过不翻译
2. 如果可以最好能渲染出来（可能有点难）

**描述您考虑过的替代方案**

**附加背景**

![image](https://user-images.githubusercontent.com/30212642/77604776-42f97b80-6f4e-11ea-9583-956a5ee2652e.png)

**Comment by elliottzheng** [comment]
这些公式有什么特征使得我可以识别出来么？

**Comment by Oneliey** [comment]
不好意思，我不太了解pdf对公式的编码，您现在的策略是什么样呢？直接从剪贴板复制文本吗？

**Comment by elliottzheng** [comment]
我只能访问剪贴板，如果这些公式复制出来没有任何特征，我是没有办法识别出来的，现在看来似乎公式和普通的文本没有任何区别。

**Comment by Oneliey** [comment]
嗯嗯，如果是这样的话有点困难，谢谢（请问现在Linux平台上移植情况如何呢？

**Comment by elliottzheng** [comment]
在搞了，进展还可以，有位老哥基本能运行能翻译了，就是有些小bug要查
