### ISSUE TITLE
win10系统缩放设置175%后，软件选项菜单超出页面，无法选取

### ISSUE THREAD

**Issue by aiyou9** [CopyTranslator/CopyTranslator#223]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**

win10系统缩放设置175%后，软件选项菜单超出页面，无法选取

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：9.0.1 x64
 - 出现问题时的模式：MainMode/ FocusMode
 - 操作系统：win10 64位
 - 阅读器：无关
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 设置win10系统显示缩放为175%
2. 打开软件的设置
3. 选择设置的选项菜单
4. 选项超出界面

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
[](url)
![](https://ftp.bmp.ovh/imgs/2020/04/c84812bed7edc022.png)
**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
界面问题，无关浏览器

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
新版本采用electron的界面布局问题，设置个滚动条，或者窗口相对布局，还得开发人员视软件整体风格而定。

**Comment by elliottzheng** [comment]
v10 新UI测试无此问题
