### ISSUE TITLE
v9.0.2 新版本安装后，启动不了

### ISSUE THREAD

**Issue by hunter0773** [CopyTranslator/CopyTranslator#224]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：V9.0.2
 - 出现问题时的模式：MainMode/ FocusMode
 - 操作系统：如win10 64位
 - 阅读器：
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1.  V9.0.2版在WIN10  #[x64上无法启动]
2. 
3. 
4.

**Comment by elliottzheng** [comment]
您提供的信息不足以复现问题，请补充更多细节，如之前的版本是否可用，出错时的截图

**Comment by elliottzheng** [comment]
安装路径中不要含有中文或空格，最好在安装之前关闭杀毒软件啥的，如果仍有问题，请将您的copytranslator安装文件夹压缩后发给我。
