### ISSUE TITLE
[Features] 句末单词附带逗号的处理

### ISSUE THREAD

**Issue by TheGentleChen** [CopyTranslator/CopyTranslator#225]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
  十分感谢您的作品，这真是一个十分实用的工具。我也希望提供一些反馈来帮助它，以便表现的更好。
  当我使用Adobe Acrobat Reader查看PDF文件时，我时常需要翻译一些单词，但当我双击复制一个句尾的单词时，末尾有时会附带一个逗号，所以在专注模式下，CopyTranslator会把它当做一个句子，只会对句意进行翻译，而不能提供更加详细的帮助（多种含义、英美发音等）。

**描述您想要的解决方案**
希望作者可以处理单个单词后跟随的逗号，这样会更加的方便。

**描述您考虑过的替代方案**
在预处理中去除句尾逗号即可，这样既不会影响句子的翻译，而且对于附带逗号的单词也能提供正确的翻译。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
已经处理
