### ISSUE TITLE
“自动隐藏”功能触发Win10自动分屏功能

### ISSUE THREAD

**Issue by Sephiroth0705** [CopyTranslator/CopyTranslator#229]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
开启“自动隐藏”功能后，拖拽主界面至屏幕边缘后触发Win10自动分屏功能

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.2
 - 出现问题时的模式：MainMode
 - 操作系统：win10 64位
 - 阅读器：不适用
 - 出现问题的文档：不适用
 - 出现问题的段落：不适用

**如何复现这个问题**
重现行为的步骤：
1. 点选“自动隐藏”功能
2. 拖拽主界面至屏幕边缘

**问题出现时，当时的CopyTranslator的设置截图**
_拖拽主界面至边缘_
![动作](https://user-images.githubusercontent.com/40844474/78473450-65bc3900-7773-11ea-97eb-9fc579d7f199.png)
_提示分屏选取_
![批注 2020-04-05 193058](https://user-images.githubusercontent.com/40844474/78473541-03b00380-7774-11ea-8fc7-a452d06d3280.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
不涉及浏览器及阅读器

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
暂无

**Comment by elliottzheng** [comment]
你的鼠标指针不要移出屏幕外。。。。你只需要让copytranslator的窗口的一部分到屏幕外即可。。

**Comment by Sephiroth0705** [comment]
> 
> 
> 你的鼠标指针不要移出屏幕外。。。。你只需要让copytranslator的窗口的一部分到屏幕外即可。。

明白(o´ω`o)ﾉ
