### ISSUE TITLE
划词翻译后，鼠标滚轮继续滚动，有时会触发放大缩小功能。

### ISSUE THREAD

**Issue by ravenxrz** [CopyTranslator/CopyTranslator#232]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：CopyTranslator v9.0.0
 - 出现问题时的模式：FocusMode
 - 操作系统：win10 64位
 - 阅读器：如 chrome浏览器/Adobe Reader
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：（概率问题，不一定能重现，但是的确有）
个人觉得是因为模拟了Ctrll+C, 而Ctrl+滚轮滑动就会放大缩小，产生了冲突。
1. 开启拖拽复制
2. 划词的同时，快速滚轮滑动
3. 可能会出现文档放大（adobe中），浏览器界面放大

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

chrome浏览器和adobe出现该问题。

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

未知。

**Comment by elliottzheng** [comment]
这个功能本来就是不稳定的，还有你划词的时候为什么要快速滑轮滚动。。。

**Comment by ravenxrz** [comment]
> 这个功能本来就是不稳定的，还有你划词的时候为什么要快速滑轮滚动。。。

我只是为了复现所以说的快速滚动，实际情况是，划词->翻译过程中同时滑动。

**Comment by elliottzheng** [comment]
按住鼠标的时候滑动滚轮是无所谓的，不要在释放的一瞬间滑动滚轮就行了
