### ISSUE TITLE
[Bug?] 运行提示A Javascript error in the main process: Uncaught Exception

### ISSUE THREAD

**Issue by aod321** [CopyTranslator/CopyTranslator#235]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.2
 - 出现问题时的模式：无
 - 操作系统：win10 专业教育版64位
 - 阅读器：无
 - 出现问题的文档：无
 - 出现问题的段落：无

**如何复现这个问题**
重现行为的步骤：
1. 从Github release下载https://github.com/CopyTranslator/CopyTranslator/releases/download/v9.0.2/copytranslator-9.0.2-win.zip
2. 解压
3. 打开copytranslator.exe
4. 出错
(PS: 下载安装版也是一样的)
**问题出现时，当时的CopyTranslator的设置截图**
无
请截取主模式窗口
![image](https://user-images.githubusercontent.com/16255068/78706399-9225b000-7941-11ea-9ef3-6d349cae4596.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
软件打不开，该项无效

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
v9.0.1也不行，v8.3.0正常,其他未测试

**Comment by elliottzheng** [comment]
你好，请按照这样的方式重新安装，安装路径中不要含有中文或空格，最好在安装之前关闭杀毒软件啥的，如果仍有问题，请将您的copytranslator安装文件夹压缩后分享给我。

**Comment by ziqiangxu** [comment]
> > 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
> > **描述问题**
> > （反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~复杂~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）
> 
> **系统环境（请填写以下信息）：**
> 
> * CopyTranslator版本：v9.0.2
> * 出现问题时的模式：无
> * 操作系统：win10 专业教育版64位
> * 阅读器：无
> * 出现问题的文档：无
> * 出现问题的段落：无
> 
> **如何复现这个问题**
> 重现行为的步骤：
> 
> 1. 从Github release下载https://github.com/CopyTranslator/CopyTranslator/releases/download/v9.0.2/copytranslator-9.0.2-win.zip
> 2. 解压
> 3. 打开copytranslator.exe
> 4. 出错
>    (PS: 下载安装版也是一样的)
>    **问题出现时，当时的CopyTranslator的设置截图**
>    无
>    请截取主模式窗口
>    ![image](https://user-images.githubusercontent.com/16255068/78706399-9225b000-7941-11ea-9ef3-6d349cae4596.png)
> 
> **是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
> 软件打不开，该项无效
> 
> **之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
> v9.0.1也不行，v8.3.0正常,其他未测试

这个缺文件的bug也许可以这样临时解决一下，把[这个文件里的iohook.node](https://github.com/wilix-team/iohook/releases/download/v0.6.2/iohook-v0.6.2-electron-v73-win32-x64.tar.gz)放过去 :rofl:

**Comment by elliottzheng** [comment]
现在主要是不知道是不是真的缺了，我自己这边没办法复现这个问题。感觉可能是被删了还是怎么样，被杀毒软件拦截了

**Comment by aod321** [comment]
感谢回复，我会去验证一下，然后在这里继续补充信息

**Comment by elliottzheng** [comment]
真是奇了怪了，你这个压缩包我下载下来解压之后是可以使用的，可以麻烦你命令行到那个目录下，然后执行copytranslator.exe 看下有啥输出么

**Comment by elliottzheng** [comment]
试一下这个可以用么 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v9.0.3

**Comment by aod321** [comment]
> 试一下这个可以用么 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v9.0.3

已测试正常了！辛苦了，非常实用，感谢！

![image](https://user-images.githubusercontent.com/16255068/78799492-c904d000-79ec-11ea-8a2d-e1b540e701fe.png)

**Comment by panjk0518** [comment]
Deepin Linux 表示同样有此问题，用的是Appimage

**Comment by ziqiangxu** [comment]
> Deepin Linux 表示同样有此问题，用的是Appimage

麻烦提供一下在终端运行的输出截图和弹窗截图

**Comment by Shimadaaaaa** [comment]
ubuntu 16.04 deb安装同样问题

**Comment by Shimadaaaaa** [comment]
![image](https://user-images.githubusercontent.com/48462439/79542934-210f9680-80bf-11ea-9f61-62b7079b84f0.png)

**Comment by elliottzheng** [comment]
试试安装libpng16-16，终端执行sudo apt install libpng16-16,再启动一下

**Comment by Shimadaaaaa** [comment]
可以了，十分感谢

**Comment by yuhlzu** [comment]
系统环境：

CopyTranslator版本：v9.0.2
操作系统：MacBookPro 10.15.4

重现行为的步骤：

填写百度OCR的三个内容，然后点确定，
> 顺便说一次，这三个填写的地方密钥什么的竟然不能复制粘贴，我手动输入的啊。。。。

(PS: 下载安装版也是一样的)
问题出现时，当时的CopyTranslator的设置截图

<img width="532" alt="截屏2020-04-28 上午11 52 22" src="https://user-images.githubusercontent.com/25719023/80445467-f20ee580-8946-11ea-9578-f5c74ea728fd.png">

其他版本未测试

**Comment by elliottzheng** [comment]
> 系统环境：
> 
> CopyTranslator版本：v9.0.2
> 操作系统：MacBookPro 10.15.4
> 
> 重现行为的步骤：
> 
> 填写百度OCR的三个内容，然后点确定，
> 
> > 顺便说一次，这三个填写的地方密钥什么的竟然不能复制粘贴，我手动输入的啊。。。。
> 
> (PS: 下载安装版也是一样的)
> 问题出现时，当时的CopyTranslator的设置截图
> 
> <img alt="截屏2020-04-28 上午11 52 22" width="532" src="https://user-images.githubusercontent.com/25719023/80445467-f20ee580-8946-11ea-9578-f5c74ea728fd.png">
> 
> 其他版本未测试
这个问题跟这个issue没啥关系了，大概率不会出现在新版本。

**Comment by CyrusYip** [comment]
在Kubuntu20.04下用appimage仍有这个错误。已安装libpng16-16。使用修复命令也不行。我是用AppImageLauncher把copytranslate整合到系统的。
```bash
➜  ~ sudo groupmens -g input $USER
[sudo] password for xx: 
sudo: groupmens: command not found
```
另外，软件没有图标。
![DeepinScreenshot_select-area_20200622145040](https://user-images.githubusercontent.com/60951091/85257102-dbdd5b80-b497-11ea-983d-f219e5682dfe.png)
![DeepinScreenshot_select-area_20200622145004](https://user-images.githubusercontent.com/60951091/85257106-de3fb580-b497-11ea-8acc-d0d2fd668eb2.png)

**Comment by Brycexxx** [comment]
![image](https://user-images.githubusercontent.com/23466003/85653865-2cdf9080-b6e0-11ea-808f-e7d65d67e294.png)
deepin15 启动错误

**Comment by ziqiangxu** [comment]
> ![image](https://user-images.githubusercontent.com/23466003/85653865-2cdf9080-b6e0-11ea-808f-e7d65d67e294.png)
执行 sudo groupmens -g input $USER，将当前用户添加到input组里。然后重新登录

**Comment by ziqiangxu** [comment]
> 在Kubuntu20.04下用appimage仍有这个错误。已安装libpng16-16。使用修复命令也不行。我是用AppImageLauncher把copytranslate整合到系统的。
> 
> ```shell
> ➜  ~ sudo groupmens -g input $USER
> [sudo] password for xx: 
> sudo: groupmens: command not found
> ```
> 
> 另外，软件没有图标。
> ![DeepinScreenshot_select-area_20200622145040](https://user-images.githubusercontent.com/60951091/85257102-dbdd5b80-b497-11ea-983d-f219e5682dfe.png)
> ![DeepinScreenshot_select-area_20200622145004](https://user-images.githubusercontent.com/60951091/85257106-de3fb580-b497-11ea-8acc-d0d2fd668eb2.png)

咱们到这里讨论吧：https://github.com/CopyTranslator/CopyTranslator/issues/259

**Comment by zhuliwen** [comment]
I encountered the same problem.
System: macOS Catalina 10.15.6


<img width="420" alt="WX20200810-100024@2x" src="https://user-images.githubusercontent.com/28001522/89747295-c2987900-daf0-11ea-98f0-429b1f6b3d66.png">

How can I fix it?

**Comment by MrGongqi** [comment]
windows10系统，安装后设置HOSTS时出现这个问题，我卸载后重试了无数遍，还是出现这个问题。但是另一台的win7电脑安装后就没问题，可以用google翻译了，而win10的这个就一直不行。求助！谢谢！
![image](https://user-images.githubusercontent.com/49467246/195021893-25a6de7a-7f73-437b-b8be-0d687252166f.png)

**Comment by xiaohui0929** [comment]
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at IncomingMessage.<anonymous> (/Applications/copytranslator.app/Contents/Resources/app.asar/background.js:239:32393)
at IncomingMessage.emit (events.js:200:13)
at addChunk (_stream_readable.js:294:12)
at readableAddChunk (_stream_readable.js:275:11)
at IncomingMessage.Readable.push (_stream_readable.js:210:10)
at HTTPParser.parserOnBody (_http_common.js:129:22)
at TLSSocket.socketOnData (_http_client.js:452:22)
at TLSSocket.emit (events.js:200:13)
at addChunk (_stream_readable.js:294:12)

**Comment by chumingqian** [comment]
系统环境（请填写以下信息）：

CopyTranslator版本：v9.1.0
出现问题时的模式：无
操作系统：ubuntu 18.04- 64位
已经安装过 libpng16-16

![image](https://user-images.githubusercontent.com/46816091/220322862-6abf8a85-a567-4135-8c19-869b1edfb922.png)


如何复现这个问题
重现行为的步骤：

![image](https://user-images.githubusercontent.com/46816091/220323410-2ac70031-8398-416c-a2de-37b2188b0711.png)

好像说的是，您需要重新调用Buffer() 的接口函数，
