### ISSUE TITLE
macOS 10.15.3 (19D76)存在无法监听剪切板的情况

### ISSUE THREAD

**Issue by ZDYYY** [CopyTranslator/CopyTranslator#236]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v9.0.2
 - 出现问题时的模式：MainMode
 - 操作系统：macOS 10.15.3 (19D76)
 - 阅读器：PDF except
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 某些时候会出现无法退出软件的问题
2. 某些时候会出现无法从剪切板中监听复制内容
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
1. 无法退出软件是指以什么方式无法退出软件，无法退出时的表现是什么，当时的设置是怎么样的，请截取。
2. 无法监听复制内容，某些时候有什么特征么？当时的设置是怎么样的，能不能稳定复现，是在什么阅读器上会出现这样的问题，在哪一个文件，哪一段？ 是否与翻译引擎有关？ 请切换到专注模式，查看复制后是否快速变黄，如果是快速变黄，但是黄色持续很久，则表明为网络问题。如果一直没有变黄，则说明是监听剪贴板的问题。

**Comment by GeniusYx** [comment]
冒昧打扰您，在macOS 10.15.4出现类似问题，在输入框无法使用任何快捷键，比如使用command+A全选文字，command+Q退出软件，command+c无法复制等等，但是可以往软件输入框里面输入文字。
