### ISSUE TITLE
请求增加DEEPL的翻译接口

### ISSUE THREAD

**Issue by lvximing** [CopyTranslator/CopyTranslator#237]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。
近日，一家名为 DeepL 的创业公司发布了自己的神经翻译工具 DeepL ，引起了业内关注。据称在盲测与 BELU 分数测试中，这款全新翻译系统的性能远超来自谷歌、微软和 Facebook 三家巨头的同类产品。
**您的功能请求是否与问题有关？请描述一下.**
该软件功能强大，是我阅读和翻译外文的利器，鉴于彩云翻译准确率较差且不常用
**描述您想要的解决方案**
真心推荐把目前翻译功能全面赶超谷歌和百度的DeepL（https://www.deepl.com/translator）翻译引擎加入翻译工具选项
**描述您考虑过的替代方案**
如果有可能把DeepL引擎和金山翻译引擎一起加入就更好了，期待copytranslator的功能愈发强大，期待您的团队再创佳绩！！！

**附加背景**
关于DeepL与其他翻译引擎的效果对比如下图，详见微文-神经翻译系统水平远超谷歌、微软，德国创业公司发布翻译器DeepL  https://mp.weixin.qq.com/s/dPEYME8_0zFw_xrawjae6A 
![image](https://user-images.githubusercontent.com/53170137/79066652-2601ce00-7cec-11ea-83bf-6fad92c48c33.png)
![image](https://user-images.githubusercontent.com/53170137/79066657-331ebd00-7cec-11ea-99d0-363eeddb81e3.png)

**Comment by DefetC** [comment]
我也希望能加入此功能。不知DEEPL有没有开放api。

**Comment by lvximing** [comment]
DEEPL有api接口，见https://www.deepl.com/en/docs-api/

**Comment by lvximing** [comment]
DeepL API

DeepL API可通过DeepL Pro订阅（DeepL API计划）访问。API是一个接口，允许其他计算机程序向我们的服务器发送文本并接收高质量的翻译。 这为全世界的开发者提供了一个全新的机会。 你可以想象到任何翻译产品都可以建立在DeepL卓越的翻译技术之上。

举几个例子：

内部通信：大公司可以将我们的翻译技术整合到他们的通信系统中。他们可以因此即时获得高质量的翻译。通过我们的数据保护保证，实现他们的信息保密。
计算机辅助翻译：领先的翻译工具提供商已授权DeepL的翻译集成到其软件中。每个译员现在都可以在他们最喜欢的翻译工具中使用DeepL令人难以置信的神经翻译。
实时翻译应用程序：最近，科技巨头和小型创业公司都宣布已开发出实时翻译的耳机，但只能提供传统翻译工具的质量。新的DeepL API让开发者可以利用DeepL的翻译技术构建实时翻译器，并减少错误。
增强现实（AR）翻译：将手机摄像头对准一个标志，就能得到准确的翻译。这样的应用可以由任何一个拥有DeepL Pro订阅的开发者开发。
操作系统： 直接在浏览器、聊天程序、邮件客户端或文字处理程序中进行翻译，只要开发者集成了我们的技术就能实现。

优雅的整合，高质量的翻译将成为新的标准。我们迫不及待地想看到开发人员创造出的令人难以置信的产品。他们与我们有着同样的愿景：在这个更加紧密联系的世界里，语言将不再是障碍。

https://www.deepl.com/zh/blog/20180305.html


| |
lvximing-vip
|
|
lvximing@vip.163.com
|
签名由网易邮箱大师定制
在2020年4月13日 20:22，Yukun Bo<notifications@github.com> 写道：

我也希望能加入此功能。不知DEEPL有没有开放api。

**Comment by LakeishaKowalczyk** [comment]
支持一个

**Comment by LakeishaKowalczyk** [comment]
@elliottzheng 
@ziqiangxu 

来呀，快活呀

**Comment by elliottzheng** [comment]
根据 https://www.deepl.com/pro.html#developer，deepl 有开放API，不过没有免费的试用计划，那么你们想自己填API KEY的话也得 起始付4.99美元，我个人认为会去申请的人不多，因此此ISSUE被列为低优先级。
![image](https://user-images.githubusercontent.com/22427645/80063739-252d2f80-8569-11ea-800e-0970f750941c.png)

**Comment by LakeishaKowalczyk** [comment]
@elliottzheng 
谢谢
有没有可能直接爬网页之类的
有一些软件里有 DeepL，但是不太稳．我发现 CopyTranslator 的彩云比其它软件的稳多了，想想作者能不能也降伏一下 DeepL

**Comment by BlurryLight** [comment]
@elliottzheng 
现在似乎有API的免费使用额度了。 500,000 chars 每月。
![图片](https://user-images.githubusercontent.com/14940338/115902043-8d706300-a494-11eb-994d-3d421bb4fbac.png)
