### ISSUE TITLE
v8.0.3-v9.0.2，安装程序异常，后台无响应

### ISSUE THREAD

**Issue by Ssrml** [CopyTranslator/CopyTranslator#239]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：v8.0.3-v9.0.3
 - 出现问题时的模式：对无
 - 操作系统：win 7 64位 
 - 安装路径:安装前：D:\Download\idm    安装后：默认的用户目录（Administrator）
 - 额外配置：无

### 如何复现这个问题
1.从Github release下载文件
2.---安装（出现问题）
3.---运行（出现问题）

详细描述问题的现象：
1.安装程序高概率无法运行
![install](https://user-images.githubusercontent.com/60307004/79302000-97749300-7f1d-11ea-943f-7775be2e350f.PNG)

2.安装后v8.0.3-v9.0.2版本无法正常运行

v8.0.3版本截图：
![803](https://user-images.githubusercontent.com/60307004/79301960-76ac3d80-7f1d-11ea-8b5b-3f29af0ca48c.PNG)

v9.0.2版本截图：
![run](https://user-images.githubusercontent.com/60307004/79301969-7c098800-7f1d-11ea-8f2b-7c49d03633a9.PNG)
![9 0 2](https://user-images.githubusercontent.com/60307004/79302010-a0656480-7f1d-11ea-81ae-bc469272b370.PNG)

###  请详细说明如何复现这个问题
1.从Github release下载文件
2.---运行安装程序（出现问题）：提示代码异常

3.---非安装版运行（出现问题）：
       v8.0.3什么都不显示
       v9.0.2后台异常，程序无响应，托盘无图标，程序主窗口不出现

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

v9.0.2配置文件目录(不知道对不对)：C:\Users\Administrator\AppData\Roaming\copytranslator
此目录无文件

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
其他非必要软件都关了，问题仍然存在

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
软件打不开，该项无效

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
软件打不开，该项无效

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
软件打不开，该项无效

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
v8.0.3-v9.0.3安装程序都有问题
v8.0.3-v9.0.2安装程序安装后无法运行
我只测试了v9.0.2的非安装版，非安装版也无法运行

v9.0.3安装后可以使用，
除了v9.0.3，一直降级到到v7.2.0版本才可使用

**Comment by elliottzheng** [comment]
v9.0.3可以用那就没啥好解决的
