### ISSUE TITLE
双屏问题

### ISSUE THREAD

**Issue by htfhxx** [CopyTranslator/CopyTranslator#240]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

## 描述问题
笔记本外接显示器的情况下，笔记本为主屏幕，显示器为副屏幕，软件放于副屏幕使用会使整个界面跳转到主屏幕。
### 系统环境（请填写以下信息）

 - CopyTranslator版本：9.2。0
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位 专业版
 - 安装路径:  D:\software\copytranslator-9.0.2-win
 - 额外配置：双屏

### 如何复现这个问题
详细描述重现问题的步骤：

1. 笔记本外接显示器的情况下，笔记本为主屏幕，显示器为副屏幕
2. 软件放于副屏幕使用
3. 点击pdf复制
4. 点击副屏幕上的软件页面，会使整个界面跳转到主屏幕

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/4507511/copytranslator.zip)

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by elliottzheng** [comment]
无法复现问题，如果新版本有这个问题欢迎重新打开issue

**Comment by elliottzheng** [comment]
新版本指的是v10

**Comment by mygoshi** [comment]
最新版本仍有此 BUG，复现方式同上所述。

**Comment by Darren-greenhand** [comment]
最新v10 stable仍有此bug，复现方式同上
