### ISSUE TITLE
添加 "translate":"Alt+X" 后启动后不能用

### ISSUE THREAD

**Issue by fesfseafefa** [CopyTranslator/CopyTranslator#243]
添加 "translate":"Alt+X" 后启动后不能用，这个translate是翻译选中的文本吗?因为习惯将翻译软件一直放后台运行，所以希望有快捷键翻译选中的功能

**Comment by elliottzheng** [comment]
Duplicate of #218 

> 添加 "translate":"Alt+X" 后启动后不能用，这个translate是翻译选中的文本吗?因为习惯将翻译软件一直放后台运行，所以希望有快捷键翻译选中的功能

这个是已知问题，已经在下一个版本修复
