### ISSUE TITLE
智能互譯在英語和繁體中文時無效

### ISSUE THREAD

**Issue by Mingw26** [CopyTranslator/CopyTranslator#245]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v8.4.0
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位 专业版
 - 安装路径: User\AppData\Local\Programs\copytranslator
 - 额外配置：無

### 如何复现这个问题
開啟智能互譯後，設置源語言為英文，目标語言為繁體中文，複制繁體中文時不會自動翻譯為英文。

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/4605702/copytranslator.zip)

**Comment by Ming0206** [comment]
![image](https://user-images.githubusercontent.com/9075911/81500546-69f4ec80-9305-11ea-9516-cc49c3e62c47.png)

**Comment by elliottzheng** [comment]
可能与 #215 是相同的原因，会尝试在下一版本修复

**Comment by elliottzheng** [comment]
Duplicate of #215

**Comment by elliottzheng** [comment]
应该是解决了，不过重复这个两个字，会被检测成日语，这个是引擎自己的问题了，目前没啥好的办法解决，不过大部分长的句子应该没问题。
![image](https://user-images.githubusercontent.com/22427645/95309097-4a1a2280-08bd-11eb-97c3-ac57a21aa683.png)
