### ISSUE TITLE
Mac#235问题求解决

### ISSUE THREAD

**Issue by ZL-GITHUB-ING** [CopyTranslator/CopyTranslator#247]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

## 描述问题
#235 9.0.2版本 之前用的好好的，今天突然出现的问题。
![截屏2020-05-15 18 27 23](https://user-images.githubusercontent.com/65397526/82042930-51a61880-96dd-11ea-9f95-690e80830928.png)

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v9.0.2
 - 出现问题时的模式：全部
 - 操作系统：macOS 10.15.4
 - 安装路径: application，不太清楚，反正苹果的安装就是超简单
 - 额外配置：无

### 如何复现这个问题

详细描述问题的现象：
![截屏2020-05-15 18 27 23](https://user-images.githubusercontent.com/65397526/82043175-ae093800-96dd-11ea-9957-f6187a2e326c.png)

详细描述重现问题的步骤：

1. 打开随便复制点什么就出现上述弹窗
2. 
4. 

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。
*
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/4633913/copytranslator.zip)
*

已知软件可能在某些环境下与某些软件存在冲突，
*请逐个退出其他非必要软件，测试问题是否仍然存在*和其它软件无关，入门级科研狗只开endnote和浏览器，该环境下一直运行优秀，没有copytranslator简直不能阅读文献，希望开发者大人能完善好该系统好让我续命，求求了。*

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

和阅读器无关，copy浏览器内容也一样

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
搜狗、有道、Google全部不能用

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
和文档无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
用过8.3好像，那时候没有出现问题，但是更新电脑系统后用的最新版9.0.2，一直使用良好，今天刚出现问题
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/4633935/copytranslator.zip)
![截屏2020-05-15 18 27 23](https://user-images.githubusercontent.com/65397526/82043852-da718400-96de-11ea-93ad-268a1560b42e.png)

**Comment by elliottzheng** [comment]
尝试在设置界面恢复默认设置后重新打开，看问题是否仍然存在

**Comment by ZL-GITHUB-ING** [comment]
第n次重装后又好了，不过反应变慢了，谢谢作者！



在 2020-05-16 10:06:41，"Elliott Zheng" <notifications@github.com> 写道：

尝试在设置界面恢复默认设置后重新打开，看问题是否仍然存在
