### ISSUE TITLE
增加OCR识别的语言种类

### ISSUE THREAD

**Issue by kabrate** [CopyTranslator/CopyTranslator#249]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
现有的OCR识别好像只有汉语和英语，我自己申请了百度ocr api，试了试识别日语，结果显示乱码。
**描述您想要的解决方案**
希望增加OCR识别的语言种类，例如韩语和日语。

**描述您考虑过的替代方案**
无

**附加背景**
无

**Comment by elliottzheng** [comment]
https://cloud.baidu.com/doc/OCR/s/zk3h7xz52

**Comment by elliottzheng** [comment]
#220
