### ISSUE TITLE
是否能设置一个代理模式

### ISSUE THREAD

**Issue by xuliexuan** [CopyTranslator/CopyTranslator#25]
**描述问题**
在公司网络中，内容翻译不了，怀疑是需要设置代理，是否有设置代理的功能

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v0.0.7-Kylin-RC1
 - 出现问题时的模式：MainMode/ FocusMode或者说对照模式或专注模式
 - 操作系统：win10 64位
 - 阅读器：
 - 出现问题的文档：
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

![image](https://user-images.githubusercontent.com/13869733/51008180-a683cd00-1585-11e9-8f06-62a671a4add1.png)

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
您好，照理说大部分地区都能正常使用而无需代理，请先检查一下您的网络连接，看一下能不能上http://dict.youdao.com，以及https://translate.google.cn
如果无法连接，请先使用系统级代理。
软件实现代理的话，得到下下个版本。

**Comment by yaukeywang** [comment]
我也是同样的问题，今天刚下载，无法翻译，属于公司内网，很多软件需要填写代理。

**Comment by xhufo** [comment]
公司网络确实需要代理，大家可以试试proxifier

**Comment by elliottzheng** [comment]
下一个版本将基于[OpenTranslate](https://github.com/OpenTranslate/OpenTranslate) 实现，代理访问的实现将成为可能

**Comment by wllzhk** [comment]
求代理功能
最近校园网暴毙，谷歌翻译基本连不上了

**Comment by yuesir137** [comment]
> 求代理功能
> 最近校园网暴毙，谷歌翻译基本连不上了
> ---------------更新--------------
> 用了proxifier，基本好使了
> 大家可以试试

nice, 困扰好久的问题解决了

**Comment by k3bc999** [comment]
受累还是添加一个代理模式吧，deepl经常无法连接
