### ISSUE TITLE
建议增加主页面侧边栏收起功能和自定义复制按键监听

### ISSUE THREAD

**Issue by sdc17** [CopyTranslator/CopyTranslator#252]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
相关，建议增加主页面侧边栏收起功能，和自定义复制按键监听

**描述您想要的解决方案**
1. 主页面侧边栏收起示意图见附件
2. 提供自定义的复制监听按键，例如可以选择连续按两次ctrl+c触发翻译，按一次时被认为是其他不需要翻译的复制任务

**描述您考虑过的替代方案**
无

**附加背景**
![image](https://user-images.githubusercontent.com/47023705/83828787-09927880-a714-11ea-8832-047bf00442b9.png)

**Comment by elliottzheng** [comment]
1. 下一个版本的界面已经提供了收起侧边栏的功能
2. Duplicate of #228 

![image](https://user-images.githubusercontent.com/22427645/83829390-5460c000-a715-11ea-9a8f-826aafeefe3f.png)
![image](https://user-images.githubusercontent.com/22427645/83829394-57f44700-a715-11ea-9f67-a2a9d7cf7662.png)
