### ISSUE TITLE
[Features]能否添加功能开关（如自动复制）的快捷键

### ISSUE THREAD

**Issue by sherlockbear** [CopyTranslator/CopyTranslator#258]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
我非常喜欢自动复制这一功能，可以让我在进行成段翻译时省去很多麻烦。然而这一功能并非在所有时候都很令人开心，当我仅仅单纯想要复制一段原文时，因为软件往往被放在后台，如果忘记关掉自动复制开关，粘贴时才发现变成了译文，很尴尬。尽管有时也记得要开关，然而从后台调出程序，关闭开关，再回到工作界面这样的操作流程是很繁琐的，与选择自动复制的初衷相悖。

**描述您想要的解决方案**
希望能够让用户设置功能开关的快捷键，这样当软件在后台运行而想要切换开关状态时，能够快速的进行。

**描述您考虑过的替代方案**
当然，如果能够让软件智能判断何时粘贴译文何时粘贴原文也是非常棒的，然而我相信这可能需要更大的工作量。

**附加背景**
![2020-06-24_Copytranslator_86](https://user-images.githubusercontent.com/20009607/85524444-c2284980-b63a-11ea-921b-55e66d3f0650.png)
希望这些功能开关能够被快捷键控制

**Comment by elliottzheng** [comment]
这个功能可以通过自定义全局快捷键实现

https://copytranslator.gitee.io/guide/9.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by sherlockbear** [comment]
wow, cool! 非常感谢，不过要是能在GUI界面进行配置可能会更好，对开发者可能还好，但对普通用户可能就不太友善了。

**Comment by elliottzheng** [comment]
[V11后引入单次增量复制](https://copytranslator.gitee.io/guide/11.0.0.html#%E5%8D%95%E6%AC%A1%E5%A2%9E%E9%87%8F%E5%A4%8D%E5%88%B6)
