### ISSUE TITLE
無法使用滑鼠滾輪放大縮小字體

### ISSUE THREAD

**Issue by noinget** [CopyTranslator/CopyTranslator#273]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v9.1.0
 - 出现问题时的模式：专注模式
 - 操作系统：win10 64位 
 - 安装路径: 安装路径中不含中文或空格

### 如何复现这个问题

我直接說明問題的原因。是copytranslator.json這個檔案中，focus的fontSize屬性被寫成了負值
舉例  
  "focus": {
        "x": -772,
        "y": -237,
        "width": 779,
        "height": 1207,
        "fontSize": -33
    },
 fontSize為-33
當成為負值，就無法滾動放大縮小翻譯字體。
現在都是發生問題就打開此檔修改負值，重啟解決。
可否禁止 fontSize 這個值為負？謝謝！

**Comment by elliottzheng** [comment]
存在出现负值的现象，不过依然可以使用滚轮缩放，多滚几下滚到正的就行了，在新版本会做处理。
