### ISSUE TITLE
[Features]请求在ORC识别时增加一个标识

### ISSUE THREAD

**Issue by luo-zi** [CopyTranslator/CopyTranslator#275]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.github.io/guide/)和项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
我使用win10的自带截图，在我使用OCR功能的时候感到非常的迷茫，他是不是没有得到图像，还是OCR一直没有回应导致没有翻译出现？
实际使用的时候两者都有，以至于我经常需要截图两次以上来保证软件获取到了我在剪切板上的图像，然后才能发现：原来是OCR一直没有回应啊，这太耗费时间也不符合设计的初衷了，软件的OCR这个功能就是为了不用打字而省下时间，而这种问题下，我等待OCR的时间长得足以让我手动输入，毫无疑问，体验极差

**描述您想要的解决方案**
增加一个提示使用户知道OCR是否正常运转
告诉我，软件是否已经把图像发送给OCR处理，以及有没有检查到剪贴板中的图像
**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
任何明显的提示都会极高的提高OCR功能的体验，例如你们并没有告诉用户OCR原来是要用截图并保存到剪贴板的
**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
![toast](https://user-images.githubusercontent.com/22427645/95302910-22bf5780-08b5-11eb-9b39-d0c73449a8a1.gif)
