### ISSUE TITLE
安装的9.1.0版本侧边栏缺失.

### ISSUE THREAD

**Issue by emily123456722** [CopyTranslator/CopyTranslator#291]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：9.1.0（官网今天打不开，从软件网站下载而来）
 - 出现问题时的模式：专注模式，侧边栏仅有专注模式，翻译，设置三个按钮且点击无效
 - 操作系统：win10 64位 专业版 
 - 安装路径: 不存在中午或空格
 - 额外配置：无

### 如何复现这个问题

 详细描述问题的现象：同一压缩包在另一台电脑上安装可成功使用，此电脑安装完成后侧边栏缺失

详细描述重现问题的步骤：

1. 双击压缩包
2. 双击应用程序
4.  跳出运行程序，但程序不完整
同样的压缩包和操作过程在另一台电脑上则一切ok

### 请回答以下问题

(###问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**)))
[

](url)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by emily123456722** [comment]
压缩包文件无法上传

**Comment by emily123456722** [comment]
![图片](https://user-images.githubusercontent.com/71453313/93495430-b0f08f80-f940-11ea-80cf-1e580eaffb8a.png)

**Comment by YangLs1996** [comment]
出现同样的问题，删除C:/users/我的用户名/copytranslator文件夹，重新打开软件后问题依旧，无法解决

**Comment by elliottzheng** [comment]
请尝试使用命令行cd到安装目录，执行copytranslator.exe, 把输出贴到这里来谢谢

**Comment by YangLs1996** [comment]
> 请尝试使用命令行cd到安装目录，执行copytranslator.exe, 把输出贴到这里来谢谢
![1](https://user-images.githubusercontent.com/41132530/95544455-b6b42f00-0a2d-11eb-946e-1ff85907ad40.png)

**Comment by elliottzheng** [comment]
试下10.0.0 beta2 吧 v9的问题不管了
