### ISSUE TITLE
英文论文复制出现小量的乱码问题

### ISSUE THREAD

**Issue by nicken** [CopyTranslator/CopyTranslator#30]
**描述问题**
在一篇英文文档中，但发现在复制部分之时，出现少量的乱码。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.7 x86 版
 - 出现问题时的模式：对照模式
 - 操作系统：如win10 64位
 - 阅读器：adobe acrobat pro(应该不是这个问题，我试过同一段文字，从微信中复制过去一样）
 -  出现问题的文档：[#论文地址](https://arxiv.org/abs/1809.00219)
 - 出现问题的段落：第三页第二段（含公式部分）（以有空两格开头的视为一段）

**如何复现这个问题**
重现行为的步骤：
0. (除了自动复制、增量复制、检测语言外其他都勾选了）
1.  选定那一段，CTRL + C

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口
![Aaron Swartz](https://raw.githubusercontent.com/nicken/CopyTranslator/master/one.PNG)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

不知道

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

不知道

注：问题是
1. 当遇到字符串‘fi’时，回自动转换为一个向上的箭头，在原文处；从原文复制出来，回复；翻译时无影响
2. 当遇到含有公式时，无法翻译，需手动删除公式。（做个判断？）

谢谢你的开发！！！

**Comment by elliottzheng** [comment]
您好，可以复现问题，可以确定是因为Adobe阅读器的问题，他复制出来的东西和别的阅读器不太一样，影响了翻译，在其他阅读器上均能正常工作。个人推荐使用gaaiho阅读器。下一版本我会尝试修复这个adobe的这个问题。

Adobe acrobat Reader DC （就是他的问题）
![image](https://user-images.githubusercontent.com/22427645/51163022-4e293400-18d3-11e9-82ef-5a3afe5a1994.png)

chrome的pdf阅读器
![image](https://user-images.githubusercontent.com/22427645/51162671-048c1980-18d2-11e9-9c37-ec0108f76741.png)
2345看图王pdf阅读器
![image](https://user-images.githubusercontent.com/22427645/51162710-30a79a80-18d2-11e9-9f00-891174a814e5.png)
Gahhio阅读器
![image](https://user-images.githubusercontent.com/22427645/51162800-7e240780-18d2-11e9-8371-271acc785042.png) 
福昕高级pdf编辑器
![image](https://user-images.githubusercontent.com/22427645/51162913-dd821780-18d2-11e9-823c-83379b1fbfd0.png)

**Comment by nicken** [comment]
好，明白了，感谢！！！

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SherryGIS** [comment]
你好，我今天刚刚下载copytranslator，但是欢乐了浏览器换了阅读器都不行，网页和PDF都无法翻译，请问是怎么回事？该如何解决？

**Comment by elliottzheng** [comment]
@SherryGIS 您好，issue不是这么用的，您的问题与本issue无关，不应该在此处回复。您的问题请看 issue #29
