### ISSUE TITLE
字体大小调节

### ISSUE THREAD

**Issue by lixus7** [CopyTranslator/CopyTranslator#307]
你好，我上次用的应该是9.0版本的，那时候按住CTRL+滚轮是可以进行字体调节的，更新后该功能消失。我觉得这个功能很有必要的呀，对于4K用户而言，不调节的话太小了字体。其他用户也是，如果方便的话加进来呗，也不影响不需要调节大小的用户。

**Comment by elliottzheng** [comment]
新版本是通过ctrl配合加号和减号来调节字体大小的

**Comment by lixus7** [comment]
啊谢谢回复！我发完了提示我看文档，然后搞定啦！谢谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elliott Zheng"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午5:18
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com&gt;; 
抄送: "尹渡"<784458472@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 字体大小调节 (#307)





 
新版本是通过ctrl配合加号和减号来调节字体大小的
