### ISSUE TITLE
【Bugs】MacOS Big Sur环境下，软件无法彻底关闭；同时无法使用快捷键

### ISSUE THREAD

**Issue by yzbrlan** [CopyTranslator/CopyTranslator#308]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：v9.1.0
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：MacOS Big Sur 11 Beta10
 - 安装路径:  /Applications/copytranslator.app
 - 额外配置：补充一些问题相关的配置如 双屏，4K屏，字体缩放尺寸等。

### 如何复现这个问题

详细描述问题的现象：
一共有两个问题：
第一个问题：软件无法在mac平台上彻底关闭，点击左上角的关闭按钮之后，在程序坞中显示没有关闭（已选择设置中关闭即退出的选项）

第二个问题：在mac中无法使用快捷键。 command+w或者command+q 快捷关闭等，command+c/v/A都不能用。

详细描述重现问题的步骤：

1. 打开软件，配置选择关闭即退出
<img width="362" alt="截屏2020-10-19 下午7 02 33" src="https://user-images.githubusercontent.com/22017571/96442880-6499b780-123e-11eb-8e34-c48de4f42100.png">

2. 点击关闭软件
<img width="925" alt="截屏2020-10-19 下午7 01 56" src="https://user-images.githubusercontent.com/22017571/96442950-7aa77800-123e-11eb-95df-4072c1f0a131.png">

3. 软件无法关闭，程序坞如图所示
<img width="502" alt="截屏2020-10-19 下午7 02 05" src="https://user-images.githubusercontent.com/22017571/96442994-872bd080-123e-11eb-9712-d5849dafc9c0.png">

1、打开软件，无法使用 command+w/q快捷关闭，无法使用command+v/c/A等
### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by yzbrlan** [comment]
4、强制关闭程序坞中的软件之后，直接报错。
<img width="286" alt="截屏2020-10-19 下午7 53 29" src="https://user-images.githubusercontent.com/22017571/96448282-b98cfc00-1245-11eb-82dc-d30b37ce79ac.png">
<img width="592" alt="截屏2020-10-19 下午7 53 36" src="https://user-images.githubusercontent.com/22017571/96448288-bbef5600-1245-11eb-8e67-eccaa127959b.png">

**Comment by alex520** [comment]
![截屏2021-01-13下午10 51 08](https://user-images.githubusercontent.com/19838914/104468004-ea38c380-55f1-11eb-9877-1b1bd7352ad6.png)
MacOS Catalina 10.15.1， Intel处理器。  右键-退出-弹窗显示如上故障。同楼反应一下问题！
版本 官网最新版

**Comment by lan-slot** [comment]
我的mac上 ，一点全屏就不能缩小了，不能正常退出，你的也是吗？

**Comment by yongquan-hu** [comment]
我也是类似的问题，无法正常关闭。每次只能点击强制退出，之后就会弹出这个发送问题报告提示。
