### ISSUE TITLE
baidu-domain api无法工作

### ISSUE THREAD

**Issue by sldtkl** [CopyTranslator/CopyTranslator#311]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：copytranslator-10.0.0-beta.2
 - 出现问题时的模式：对照模式和专注模式
 - 操作系统：win10 x64 v2004
 - 安装路径: C:\Program Files\copytranslator
 - 额外配置：已经赋予管理员权限，baidu-domain及baidu api已经申请

### 如何复现这个问题

详细描述问题的现象：
在选择baidu-domain时，无法翻译，出现toast：翻译完成：undefined→undefined
选择baidu及其他翻译引擎无上述问题

详细描述重现问题的步骤：

1. 复制段落翻译
2. 选择baidu-domain引擎

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]

配置文件夹为未经编辑，仅设置了baidu-ocr，baidu，baidu-domain api，baidu-ocr api正常工作，baidu api不知道是否工作
选择domain为medicine

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

其他引擎尚无问题，未发现冲突软件

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

无关

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

仅baidu-domain引擎不可应用

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

新版本功能

**Comment by elliottzheng** [comment]
因为百度垂直领域翻译是第一个只有收费的API,跟百度OCR比较类似，如果保持监听剪贴板，可能会导致用户的费用很高，目前这块的逻辑还不完善，我在想怎么让用户根据需要调用。
