### ISSUE TITLE
ArchLinux KDE 无法运行Appimage

### ISSUE THREAD

**Issue by violetu** [CopyTranslator/CopyTranslator#312]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本： v9.1.0
 - 出现问题时的模式：Appimage 无法运行
 - 操作系统：Arch linux x64 KDE
 - 安装路径: 运行的是appIage
 - 额外配置：kde桌面环境

### 如何复现这个问题

运行报错：
![image](https://user-images.githubusercontent.com/33022132/97078163-a5b61100-161c-11eb-8b48-4b4c83c8f355.png)

**Comment by ymm238** [comment]
same to me

**Comment by veritablevein** [comment]
建议下deb包后，用debtap转成tar.zst安装，我只测试了10.0.0beta2的，除了弹出一个报错外，可以正常运行
![10 0 0-beta2 error](https://user-images.githubusercontent.com/36351249/97823218-44b0cc00-1cf3-11eb-9eb1-606f6e390463.png)
![copytranslator成功使用](https://user-images.githubusercontent.com/36351249/97823230-4bd7da00-1cf3-11eb-84ab-6992309df1fa.png)

**Comment by violetu** [comment]
> 建议下deb包后，用debtap转成tar.zst安装，我只测试了10.0.0beta2的，除了弹出一个报错外，可以正常运行
> ![10 0 0-beta2 error](https://user-images.githubusercontent.com/36351249/97823218-44b0cc00-1cf3-11eb-9eb1-606f6e390463.png)
> ![copytranslator成功使用](https://user-images.githubusercontent.com/36351249/97823230-4bd7da00-1cf3-11eb-84ab-6992309df1fa.png)

多谢老哥，这样确实可以。
