### ISSUE TITLE
[Features]“增量复制”功能改进建议

### ISSUE THREAD

**Issue by VagetabIeBird** [CopyTranslator/CopyTranslator#316]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
1、增量复制功能按钮在菜单中，激活需要点开菜单--打开增量复制按钮--关闭菜单--重新选取第一段（因为按钮激活会清空当前已经选择部分）--再选取第二段。不需要使用时再重复操作关闭。使用时较为麻烦，建议改进。
2、另一个小问题，就是希望新打开软件可以记忆关闭时的窗口，每次打开是一个大窗口，需要调整不够友好。

**描述您想要的解决方案**
建议1：针对“拖拽复制”功能开启时，按住ctrl/shift/alt键+鼠标选取则进行增量复制，否则不增量复制。
建议2：“增量复制”功能开关切换时不清空当前已经选择的内容。

**描述您考虑过的替代方案**
将增量复制按钮固定到顶部栏，无需打开菜单也可减少操作步骤，提高效率。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
- [ ] 针对“拖拽复制”功能开启时，按住ctrl/shift/alt键+鼠标选取则进行增量复制，否则不增量复制。
- [ ] “增量复制”功能开关切换时不清空当前已经选择的内容。
