### ISSUE TITLE
关于项目许可证的问题

### ISSUE THREAD

**Issue by Ilgharkus** [CopyTranslator/CopyTranslator#319]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：N/A
 - 出现问题时的模式：N/A
 - 操作系统：N/A
 - 安装路径: N/A
 - 额外配置：N/A

### 如何复现这个问题

详细描述问题的现象：
该项目的Github Repo以及项目网站上注明本项目使用GPLv2许可证。
项目作者在README文件中写道：
“本软件免费开源，如果您发现有人在网上售卖此软件，请帮忙举报下”
“转发时请一定附上项目地址，未附上项目地址/软件官网的转载行为均构成侵权。”

但是GPLv2允许用户在复制以及分发的时候收取一定的补偿。
并且GPLv2只要求用户在复制以及分发程序的时候在显著位置显示正确的版权声明。

项目作者在README文件中这样规定是否可以认为是对于GPLv2许可证附加了其他限制？
因为这在GPLv2中是严格禁止的，并且会带来立即的许可证失效。

详细描述重现问题的步骤：

1. 
2. 
4. 

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
 N/A

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
N/A

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
N/A

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
N/A

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
N/A

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
N/A

**Comment by elliottzheng** [comment]
一切参照GPL V2 协议内容即可，用不着在这里问是不是。

**Comment by elliottzheng** [comment]
朋友，感谢你的提醒，如果你看到的话，请在gitter上与我交流
