### ISSUE TITLE
[Features]优化贴边隐藏和自动显示和隐藏

### ISSUE THREAD

**Issue by Vixb1122** [CopyTranslator/CopyTranslator#33]
**您的功能请求是否与问题有关？请描述一下.**
贴边隐藏和自动显示的体验不太好。

**描述您想要的解决方案**
对于贴边隐藏：如果鼠标指针移出专注模式的窗口后，直接隐藏，不露出一小部分。鼠标指针靠近隐藏的位置一段像素时，显示窗口（参考QQ勾选“停靠在桌面边缘时自动隐藏”的效果）
对于自动显示：触发自动显示时，鼠标在界面之外点击应该触发贴边隐藏。

**描述您考虑过的替代方案**
暂时没有替代方案

**附加背景**
想象中的整个操作流程如下：
1. 启用`贴边隐藏`、`自动显示`、`专注模式`
2. 移动专注模式窗口贴边，将鼠标移出专注窗口，窗口整个隐藏
3. 想要查看翻译内容时，鼠标靠近隐藏的位置，窗口显示出来，看完了之后将鼠标移出窗口，窗口隐藏
4. 复制待翻译文本，触发翻译，自动显示，鼠标在界面之外点击后自动隐藏

**Comment by elliottzheng** [comment]
您好，之前之所以需要点击专注模式，再点击其他地方才能收起自动显示之后的窗口，是因为使用python实现的原因，难以捕获到您讲述的这类事件，重写之后会优化整个交互逻辑。

**Comment by ZhuBaohe** [comment]
“鼠标在界面之外点击后自动隐藏”   这个要求不合理。
 有时候翻译不准，还要鼠标点击翻开原文，这时候要保持翻译界面显示，不能隐藏。

**Comment by ZhuBaohe** [comment]
@Vixb1122 
现在的逻辑是用户需要隐藏要点击两次，先点一下界面，然后在界面外再点击一下才会隐藏。或者直接双击彩条，也会隐藏。

所以用户只要不先点击界面，鼠标点击原文时（为了取消原文的选中状态），翻译界面仍旧保留的。这样就方便对照原文和翻译。

当然，如果不想对照原文，直接想隐藏界面，要点击两次就有点麻烦。

不知道 @elliottzheng 能不能增加这个隐藏逻辑：

显示翻译界面后，跟踪鼠标坐标，只要发现鼠标是从界面外移动到界面内然后再移出（右键选择菜单的移出不算），就隐藏界面。

这样就避免点击两次了，比较方便。

**Comment by elliottzheng** [comment]
感谢两位的建议，我都会纳入考虑的
