### ISSUE TITLE
增加“回车”翻译功能

### ISSUE THREAD

**Issue by DogeFlow** [CopyTranslator/CopyTranslator#336]

**Comment by elliottzheng** [comment]
请使用 ctrl+回车

**Comment by DogeFlow** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        ctrl+回车无效
        
    
        
        

        
    

    在2020年12月24日 09:19，Elliott Zheng<notifications@github.com> 写道： 




请使用 ctrl+回车
