### ISSUE TITLE
[Features]智能互译改进：提供第二目标语音

### ISSUE THREAD

**Issue by Vixb1122** [CopyTranslator/CopyTranslator#34]
**您的功能请求是否与问题有关？请描述一下.**
启用语言检测时的智能互译存在问题。

**描述您想要的解决方案**
提供第二目标语言，如果勾选`检测语言`开关时，所复制内容的语言是目标语言，那么自动将所复制文本翻译为第二目标语言。

**描述您考虑过的替代方案**
没有替代方案

**附加背景**
`检测语言` 和 `智能互译` 的场景重叠时，希望采用以上方案解决必须关闭 `检测语言` 才能智能互译成功的问题。

**Comment by elliottzheng** [comment]
您好，能描述一个这个功能实际的应用场景吗？

**Comment by elliottzheng** [comment]
好的，我会再研究下，应该在下下版本会加入。
