### ISSUE TITLE
Mac版本无法使用 始终提示A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Olivar326** [CopyTranslator/CopyTranslator#342]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：9.0.2.2.dmg   9.0.2-mac.zip
 - 出现问题时的模式：对照模式
 - 操作系统：MacOS 10.14.6 
 - 安装路径: 请确保安装路径中不含有中文或空格
 - 额外配置：补充一些问题相关的配置如 双屏，4K屏，字体缩放尺寸等。

### 如何复现这个问题

详细描述问题的现象：
在安装两个版本的CopyTranslator后，在运行时都会显示A JavaScript error occurred in the main process，但是二者提示的信息描述不一样（详情描述见下图）

详细描述重现问题的步骤：

1. 关闭杀毒软件，从官网下载安装mac两个版本的软件
2. 按照使用指南进行配置
3. 弹出A JavaScript error occurred in the main process对话框，无法正常使用

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

![屏幕快照 2021-01-22 10 55 33](https://user-images.githubusercontent.com/77820507/105443353-790aa780-5ca6-11eb-87f8-593ff0f4de8a.png)
![屏幕快照 2021-01-22 11 22 02](https://user-images.githubusercontent.com/77820507/105443396-84f66980-5ca6-11eb-8970-3ac253b4fd82.png)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

完全卸载，安装后问题依旧存在

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

无

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

无

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

无

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
只测试了官网提供的mac的最新的两个版本

**Comment by xin0107** [comment]
我也遇到了！卸载重装、清理软件清理copytranslator所有文件再重装新下载的软件都没用，一直跳出来，v9.0.2。

**Comment by xin0107** [comment]
另外，mac怎么缩放字体？
