### ISSUE TITLE
多个版本仅能使用百度、有道引擎，不能使用谷歌等其他引擎翻译

### ISSUE THREAD

**Issue by EVANGELION-Air** [CopyTranslator/CopyTranslator#344]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：v10.0.0 beta全部版本，v9.1.0正式版本
 - 出现问题时的模式：所有模式
 - 操作系统：win10 64位 企业版 
 - 安装路径: 我确保安装路径中不含有中文或空格
 - 额外配置：4K屏，200%缩放

### 如何复现这个问题

详细描述问题的现象：

目前无论是正式版还是beta版都无法使用谷歌翻译，只有百度与有道翻译可以使用，我确定我可以正常访https://translate.google.cn/ ，并且即便我开了全局代理，也无法使用谷歌翻译，此问题已经在gitter中被大量用户反馈

详细描述重现问题的步骤：

1. 无法使用谷歌翻译

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

我的设置就是软件默认初始设置，该问题与用户配置文件无关

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

无

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

所有程序都不能使用谷歌翻译

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

我确定，除了百度和有道，其余翻译引擎全部不可以使用

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

无

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

目前正式版9.1.0也有此问题

**Comment by ssfldsh** [comment]
存在这个问题

**Comment by bilibilibohe** [comment]
9.0.3版本也有这个问题

**Comment by Neight99** [comment]
存在这个问题

**Comment by Leezzxx** [comment]
v9.1.0正式版存在这个问题

**Comment by elliottzheng** [comment]
能不能提供一个PDF或者是一段文字复制之后能够稳定复现这个问题

**Comment by lafayatte** [comment]
V10 beta 也存在复制后 没反应或者反应很慢的问题，意思是翻译接口造成的。
我只想用一下这个格式化的功能，能不能设置只格式化句子就行了

**Comment by HUILINLIANG** [comment]
我想下载最新版本的，但是下载之后还是V9的版本，我想要会自动弹出右下角的通知，但是总是弄不了，有大神知道怎么弄吗？

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢
