### ISSUE TITLE
[Bug？]软件在后台运行，无法显示窗口

### ISSUE THREAD

**Issue by TexBlock** [CopyTranslator/CopyTranslator#356]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v10.0.0-bata3
 - 出现问题时的模式：无
 - 操作系统：win 7 旗舰版 64位 
 - 安装路径: C:\Users\Administrator\AppData\Local\Programs\copytranslator
 - 额外配置：无

### 如何复现这个问题

详细描述问题的现象：copytranslator-10.0.0-beta.3在后台运行，无法显示窗口，便携版相同
![Snipaste_2021-03-20_17-05-51](https://user-images.githubusercontent.com/65154269/111864923-ce112400-899e-11eb-92ab-c8532953d0e8.png)

详细描述重现问题的步骤：

1. 下载copytranslator-10.0.0-beta.3.exe
2. 双击CopyTranslator.exe
3. 双击后无窗口
4. 

https://user-images.githubusercontent.com/65154269/111865209-93a88680-89a0-11eb-8a86-1311506bda7a.mp4

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/6175194/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
是

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
未知

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
未知

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
未知

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
v9.1.0

**Comment by elliottzheng** [comment]
您好，我这边使用win7系统无法复现您的问题，请您提供更多的信息帮助我定位问题。

先删除 c:/users/你的用户名/copytranslator
CMD到安装目录下，然后copytranslator.exe 然后把命令行的输出贴到这里来

**Comment by block2333** [comment]
> 您好，我这边使用win7系统无法复现您的问题，请您提供更多的信息帮助我定位问题。
> 
> 先删除 c:/users/你的用户名/copytranslator
> CMD到安装目录下，然后copytranslator.exe 然后把命令行的输出贴到这里来

CMD输出：
```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator\AppData\Local\Programs\copytranslator>copytranslator.exe

C:\Users\Administrator\AppData\Local\Programs\copytranslator>
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 4 layouts.
refresh_locale_list [493]: Received 4 locales.

C:\Users\Administrator\AppData\Local\Programs\copytranslator>
```

**Comment by elliottzheng** [comment]
实在不好意思，如果9.1.0还能使用的话，请接着使用，我没有办法复现你的问题，命令行的输出也没有提供任何有效信息。
