### ISSUE TITLE
[Features]添加PDF阅读标注功能

### ISSUE THREAD

**Issue by ZekShawn** [CopyTranslator/CopyTranslator#358]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
希望软件本身能打开PDF，作为一个阅读与翻译一体的软件；

**描述您想要的解决方案**
阅读PDF与翻译文字，分在两个软件的体验很割裂，希望可以添加阅读PDF的功能；

**描述您考虑过的替代方案**
类似于Windows上的知云，目前macOS与Linux上的知云体验较为拉垮；

**附加背景**
![某软件Mac版截图](https://pic.imgdb.cn/item/606d70fe8322e6675cdd2c8e.png)

**Comment by elliottzheng** [comment]
copytranslator不是一个PDF阅读器，也不打算做成一个PDF阅读器。
