### ISSUE TITLE
 双击复制功能不管用

### ISSUE THREAD

**Issue by godefy** [CopyTranslator/CopyTranslator#359]
在设置里有个双击复制,打开后,发现没作用。
在各种界面中都试了,都无法实现。

我对这个功能的理解是,开启这个选项后,我在任意位置双击选中文本,就会自动进行复制,并触发CopyTranslator和复制相关的后续翻译操作。不知道是不是对这个功能理解有误。其实我对这个功能的使用需求还是蛮高的。

**Comment by elliottzheng** [comment]
这个功能目前需要同时打开拖拽复制后才有用
