### ISSUE TITLE
[Features] 希望能设置翻译框的背景色和字体色

### ISSUE THREAD

**Issue by ZhuBaohe** [CopyTranslator/CopyTranslator#36]
**您的功能请求是否与问题有关？请描述一下.**
长时间看英文pdf书籍，白底黑字比较刺激眼睛。希望能设置翻译框的背景色和字体色，比如黑底白字，灰底黑字等，以缓解视力疲劳。

**描述您想要的解决方案**
增加两个按钮，分别设置背景色和字体色。点击按钮，会弹出颜色选择框。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
颜色选择框可以如下所示
![1](https://user-images.githubusercontent.com/35796307/51730740-94407d80-20b3-11e9-8f4d-c29efdf3174f.jpg)

**Comment by elliottzheng** [comment]
您好，下个版本，各种颜色的配置将以配置文件的方式提供，如果您需要的话，可以自行修改配置文件。
下下版本才会考虑提供调色板。

**Comment by elliottzheng** [comment]
下一版本提供了 `style.css` 可以自定义基本上所有的样式，请查看 [自定义指南](https://github.com/CopyTranslator/CopyTranslator/wiki/Customization-%E8%87%AA%E5%AE%9A%E4%B9%89)
