### ISSUE TITLE
谷歌翻译，必应翻译，有道翻译不能正常工作

### ISSUE THREAD

**Issue by PengfeiM** [CopyTranslator/CopyTranslator#364]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v10.0.0
 - 出现问题时的模式：所有模式均出现此问题
 - 操作系统：win10 64位 专业教育版20H2
 - 安装路径: d:\copytranslator\copytranslator.exe
 - 额外配置：补充一些问题相关的配置如 双屏，4K屏，字体缩放尺寸等。

### 如何复现这个问题： 
详细描述问题的现象：如上所说，除了百度翻译其他翻译无法正常工作。

详细描述重现问题的步骤：

1. 打开copytranslator
2. 复制一段pdf中的英文
3. 出现问题

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/6390011/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by cloudpanl** [comment]
出现同样的问题，Google翻译正常使用的情况下，有时会出现 “翻译完成  undefined->undefined “，此时原文区是空白的，但是粘贴板是有英文内容的，粘贴到记事本可以看到自己复制的内容，此时切换到百度翻译又是正常的，重启软件也没用，但是网页访问“https://translate.google.cn/” 是正常的，版本 V10.0.0 破晓 beta.3

**Comment by VagetabIeBird** [comment]
出现同样的问题，复制的内容在剪贴板可以看到并不会自动格式化，仅有原文，翻译栏同样出现”翻译完成undefined->undefined “但是两栏均无内容。本来早期（2020年10月）安装的beta2版本没有问题，在今天（2021年5月8日）升级beta3版本后出现问题，卸载beta3版本再次安装beta2版本后问题仍然存在。

**Comment by elliottzheng** [comment]
能不能提供一个PDF或者是一段文字复制之后能够稳定复现这个问题

**Comment by PengfeiM** [comment]
前几天卸载了10.0 beta3装了9还有这个问题，但是今天想复现这个问题，重装了10.0 beta3，暂时好像没这个问题了。   
后续如果碰到这个问题我将及时上传pdf。
