### ISSUE TITLE
拖拽翻译灵敏度过高，大多数时候单纯的点击都会弹出模拟复制的提示，附一个晓bug反馈。

### ISSUE THREAD

**Issue by xishizhe** [CopyTranslator/CopyTranslator#371]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**

- 此请求和拖拽翻译的灵敏度过高和误识别有关，拖拽翻译会识别出单纯的点击动作，且总是会弹出”模拟复制“的提示，并且，若是无意的拖拽，并未选中任何文本，也会被识别到。

**描述您想要的解决方案**

- 降低灵敏度，不要识别点击或者空文本；软件的操作提示，如”模拟复制“等设置开启或关闭的开关，关闭提示并不影响软件的使用。

**描述您考虑过的替代方案**

1. 关于拖拽复制，可以设置触发阈值，比如拖拽长度大于多少才会触发（例如三个英文字母的长度），同时可以设置不翻译空白的复制结果；

1. 关于操作提示，建议增强其自定义性，例如，可以选择开启或关闭提示；

1. 最后，希望能增加翻译结果和原文的居中显示功能，会更加美观，也是强迫症患者的福音。

**附加背景**

- 最后再反馈一个小bug

- 如图，在对照模式下，不论垂直还是水平对照，英译汉的时候，翻译结果会自动添加空格，汉译英是正常的。

- 以上所有，都是对于最新版本 v10.0.0 beta.3 而言的。

![2021-05-17 (6)](https://user-images.githubusercontent.com/55939287/118488507-6254f880-b74e-11eb-918f-abbc3915f0c7.png)

![2021-05-17 (7)](https://user-images.githubusercontent.com/55939287/118488541-697c0680-b74e-11eb-9517-f37178cc20a9.png)

![2021-05-17 (8)](https://user-images.githubusercontent.com/55939287/118488671-8ca6b600-b74e-11eb-9ec1-2c94de658ff5.png)

- PS：这个软件太棒了，我很喜欢，所以我希望它能变得越来越好，感谢作者！

**Comment by elliottzheng** [comment]
#475

**Comment by elliottzheng** [comment]
10.2.4后可以启用拖拽复制白名单，仅白名单内的程序会触发拖拽复制，待新版本发布后可以尝试
