### ISSUE TITLE
请求增加关闭操作提示的按钮[Features]

### ISSUE THREAD

**Issue by panxiang126** [CopyTranslator/CopyTranslator#373]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。
CopyTranslator每次操作之后后会在最下方提示操作的内容，比如，“模拟复制”， “翻译完成”等等，如下图所示。在阅读文献时，这种动态的提示很影响观感。
![QQ截图20210519100236](https://user-images.githubusercontent.com/68883727/118755864-43fd1300-b89c-11eb-8b8b-5c31354d1760.png)
![QQ截图20210519100222](https://user-images.githubusercontent.com/68883727/118755866-452e4000-b89c-11eb-971e-64570ce7142b.png)

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
增加一个按钮可以开启/关闭这种提示

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by isyinun** [comment]
unsubscribe



Closed #373.
