### ISSUE TITLE
把多引擎结果从布局中独立出来

### ISSUE THREAD

**Issue by fireattack** [CopyTranslator/CopyTranslator#376]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**

点布局按钮，似乎有一个模式是同时显示多个翻译引擎的结果（我在用户手册里没找到，可能是新加的？）。
我想使用这个模式，但是使用上下对照或者关注布局。

**描述您想要的解决方案**

感觉这个功能应该单独列出来，而不是加在布局切换按钮里。

**附加背景**

![image](https://user-images.githubusercontent.com/4130991/119442029-bb8fcf80-bcec-11eb-8a8a-5149c6164948.png)

**Comment by elliottzheng** [comment]
你的描述很不清楚，你其实是想说在任何布局，都应该能看到多引擎的结果是吧

**Comment by fireattack** [comment]
是的，就是说这个应该是个单独的选项，而不是在布局切换里。
