### ISSUE TITLE
[Features] 请添加关闭快捷键的设置, 工作软件的快捷键无法使用了.

### ISSUE THREAD

**Issue by gool123456** [CopyTranslator/CopyTranslator#381]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
请添加关闭快捷键的设置, 或者不要用全局的快捷键, 工作软件的快捷键无法使用了.

**描述您想要的解决方案**
 其他工作软件的快捷键无法使用了.

**描述您考虑过的替代方案**
使用软件快捷键 或者添加关闭快捷键的设置开关.

**附加背景**
无

**Comment by elliottzheng** [comment]
哪个快捷键

--------------原始邮件--------------
发件人："gool123456 ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 上午9:28
收件人："CopyTranslator/CopyTranslator" ***@***.***&gt;;
抄送："Elliott Zheng ***@***.***&gt;;"Assign ***@***.***&gt;;
主题：[CopyTranslator/CopyTranslator] [Features] 请添加关闭快捷键的设置, 工作软件的快捷键无法使用了. (#381)
-----------------------------------

 

  
重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
  
前言：
 请务必详细阅读使用指南和项目的project并在Issuse中查找您问题的关键词，您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了，CopyTranslator经过多次迭代，功能越来越丰富（复杂），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。
 
您的功能请求是否与问题有关？请描述一下.
 请添加关闭快捷键的设置, 或者不要用全局的快捷键, 工作软件的快捷键无法使用了.
 
描述您想要的解决方案
 其他工作软件的快捷键无法使用了.
 
描述您考虑过的替代方案
 使用软件快捷键 或者添加关闭快捷键的设置开关.
 
附加背景
 无

**Comment by gool123456** [comment]
> 哪个快捷键
> […](#)
> --------------原始邮件-------------- 发件人："gool123456 ***@***.***&gt;; 发送时间：2021年6月9日(星期三) 上午9:28 收件人："CopyTranslator/CopyTranslator" ***@***.***&gt;; 抄送："Elliott Zheng ***@***.***&gt;;"Assign ***@***.***&gt;; 主题：[CopyTranslator/CopyTranslator] [Features] 请添加关闭快捷键的设置, 工作软件的快捷键无法使用了. (#381) ----------------------------------- 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。 前言： 请务必详细阅读使用指南和项目的project并在Issuse中查找您问题的关键词，您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了，CopyTranslator经过多次迭代，功能越来越丰富（复杂），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。 您的功能请求是否与问题有关？请描述一下. 请添加关闭快捷键的设置, 或者不要用全局的快捷键, 工作软件的快捷键无法使用了. 描述您想要的解决方案 其他工作软件的快捷键无法使用了. 描述您考虑过的替代方案 使用软件快捷键 或者添加关闭快捷键的设置开关. 附加背景 无 — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

Shift + F1 和 Shift + F2

**Comment by elliottzheng** [comment]
https://copytranslator.gitee.io/guide/10.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE 参考这里，把shortcut.json里对应的记录删掉就行了
