### ISSUE TITLE
[Features] 希望可以提供辅助编写style.css的html文件

### ISSUE THREAD

**Issue by xenonz95** [CopyTranslator/CopyTranslator#397]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。
我看到默认的文字排版很拥挤，所以尝试改了一下style文件，但是发现不管是加boarder还是加margin都无法让右侧留白，而且左侧留白之后把整个文本内容挤出软件界面了（我是mac）。同时，我每次修改style.css都需要重新退出并打开整个软件，就挺不方便的。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
考虑到你们使用的开发语言似乎是一种可以生成html文件或仅在内存中生成的html页面，并将其用于显示的工具，所以我想如果你们能提供一个与最终用于显示的页面相一致的html文件（不一定完整，修改它的样式表与最终效果类似就行），那么根据这个html去使用其他的第三方网页编辑工具去修改样式会更方便一些。这样应该也会有更多人上传样式文件吧（不过样式文件去哪里上传？我没找到入口）

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。
上面提到了。此外我在最后贴上我现在自己正在用的style.css，专注模式下勉强有了空行和留白，但对比模式直接没法用了
如果你们直接通过修改软件本身实现留白也可以，主要是左右两侧对称的半个到一个字符的留白，与下方为了不与图标重叠的留白

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
附一个如果在 focusText 内部设置 margin 的效果图
![image](https://user-images.githubusercontent.com/16556163/128278705-a9cda4c4-a514-4310-91fa-27561c732b46.png)

```CSS
.application{ /*在这里设置整个应用的字体*/
    font-family: "华文黑体","PingHei";
    font-size: medium;
    margin: 0.5em 1.5em 2em 1em !important;
}
.focusText {
    line-height:200%;
    border-color: white;
}
.contrastText {
    line-height:200%;
}

**Comment by elliottzheng** [comment]
v10 没有这种结构了应该不需要了
