### ISSUE TITLE
翻译出现undefined-undefined，无法正常使用

### ISSUE THREAD

**Issue by wynynw** [CopyTranslator/CopyTranslator#405]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：10.0.0-beta3
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位 专业版
 - 安装路径: D:/copytranslator
 - 额外配置：无

### 如何复现这个问题

详细描述问题的现象：
复制PDF论文进行翻译时，突然出现无法读取剪切板内容，复制内容粘贴之后也无法翻译的现象。删除配置文件夹/重装之后现象仍然存在，软件显示 翻译完成 Undefined -> undefined
只有百度翻译引擎可以正常使用
【坐标在北美，不存在google需要翻墙的问题】

详细描述重现问题的步骤：

1. 我不知道如何重现这个问题，它是突然发生的
2. 
4. 

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/7175136/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
与软件无关
QQ，微信，AcrobatDC，Word均无冲突

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
与阅读器无关
AcrobatDC, Chrome, Word, 直接键入都不能翻译，显示信息都是Undefined-undefined

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
百度翻译可以使用，腾讯翻译只能读取剪切板，不能翻译，这两个引擎的显示信息都是正常的
其余两个引擎无法读取剪切板也无法翻译，显示信息为Undefined-undefined

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
与文档无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
安装了9.1.0版本进行测试，只有百度翻译是可以正常使用的

**Comment by wyn0325** [comment]
翻译出现问题时正在使用的论文为专业课材料，不方便贴出来

**Comment by lafayatte** [comment]
翻译接口好像又有问题了，反应很慢

**Comment by Jason0200047** [comment]
复制到界面后，时而可以翻译，时而不能。。。
非常感谢作者的工作。您的想法可以节约很多研究者的时间！：）

**Comment by silverdew49** [comment]
同样的问题，刚打开软件能翻译2-3次，后面不管怎么复制内容都翻译不了，需要关闭重新开启软件。

**Comment by Ctozzzzz** [comment]
遇到了同样的问题，使用福昕pdf reader读论文，之前还能正常翻译，突然出现undefined->undefined，重启软件也没用。测试不同的翻译引擎，只有Baidu可以，但是baidu翻译效果太拉.......

**Comment by S-atanail** [comment]
同样的问题，现在重启软件、重启电脑都没用。

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢

**Comment by wzy011030** [comment]
这是一封来自QQ邮箱的自动回复邮件。 您好，您的邮件我已收到，谢谢您的来信。
