### ISSUE TITLE
[Features]能否增加网络代理功能，即一个支持socks5的接口？

### ISSUE THREAD

**Issue by opptimus** [CopyTranslator/CopyTranslator#406]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
由于众所周知的原因，网络连接谷歌往往不流畅，能否增加网络代理功能，即一个支持socks5的接口？

**描述您想要的解决方案**
增加网络代理功能，即一个支持socks5的接口

**描述您考虑过的替代方案**
使用全局代理覆盖本地运行所有软件

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
最新版里google是走系统代理的，以前会绕过，可以试一下

https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.2.2

**Comment by FLCA** [comment]
> 

希望可以内嵌代理功能以提升Google以及DeepL的响应速度。

**Comment by elliottzheng** [comment]
DeepL和谷歌都是跟浏览器一样走的系统代理，因为deepl本质就是在后台开了个网页
