### ISSUE TITLE
复制翻译，剪切板监听不灵敏

### ISSUE THREAD

**Issue by HYGitHub1997** [CopyTranslator/CopyTranslator#416]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

## 描述问题
复制翻译，剪切板监听不灵敏
### 系统环境（请填写以下信息）

 - CopyTranslator版本：9.1.0-win和10.0.0-beta.5-win
 - 出现问题时的模式：专注模式
 - 操作系统：Windows 11 家庭中文版 22000.282
 - 安装路径: C:\Program Files\copytranslator-10.0.0-beta.5-win
 - 额外配置：2K屏幕，175%缩放。

### 如何复现这个问题

详细描述问题的现象：
首次复制翻译正常，然后失灵6次左右后，能够正常翻译一次。然后重复失灵6、7次后再次翻译正常

详细描述重现问题的步骤：

1. 打开软件
2. 复制了一个单词，正常翻译
3. 再复制一个新单词，没有反应
4. 再复制一个新单词，没有反应
5. 再复制一个新单词，没有反应
6. 失败很多次后，再复制一个新单词，正常翻译。
7. 重复以上步骤

### 请回答以下问题

- [ ] 问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

新解压的软件包，默认配置，没有更改

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
在测试软件的时候一共开了edge浏览器，drawboard pdf，vs code。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
再浏览器的网页上复制测试过，再VS code上复制测试过，在drawboard PDF 上复制测试过，问题都存在。

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
有道、必应、谷歌都有这种问题。

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
问题和特定文档无关。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by iamqiz** [comment]
我以为就只有我遇到这个问题嘞
我本来是谷歌翻译, 会出现这个问题,
刚才换成百度翻译,就好了
不知道过段时间会不会再出现这个问题

**Comment by YLDS-X** [comment]
+1

**Comment by cosncosn** [comment]
艰难中找到了这里，可以反馈问题了。上面描述的问题的确存在，我在用Ditto的剪切板工具，从这个软件里面提取复制的内容，应该可以解决复制不稳定的问题。

**Comment by ForyoungYu** [comment]
确实，有时复制几次就翻译不了了，需要重启一次，这样就很麻烦，而且翻译的速度也不是很快。

**Comment by cosncosn** [comment]
新年快乐，我尝试的结果是肯定会出现。

发自我的iPhone

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢
