### ISSUE TITLE
支持ubuntu系统

### ISSUE THREAD

**Issue by xuefliang** [CopyTranslator/CopyTranslator#42]
ubuntu 系统，用源码如何编译？

**Comment by elliottzheng** [comment]
您好，您的issue 与#21 重复。如果您指的是python实现的话（master分支），由于使用了win32 api，估计没办法直接在unbuntu编译。如果指的是新版本的electron实现（phoenix分支，也是本仓库默认分支），由于当前仅完成了部分功能，编译的意义不大。如果后续发布后，您想要自行编译，可以查看[这里](https://github.com/CopyTranslator/CopyTranslator/wiki/Contributing-%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE#build-from-source)

**Comment by nicken** [comment]
你好 可以提供一个简单的`electron实现`的编译教程么？在ubuntu下的
这样可以自行进行编译，虽然做不到协助产品的多平台发布，但也有个自行动手编译方式

**Comment by nicken** [comment]
> 你好 可以提供一个简单的`electron实现`的编译教程么？在ubuntu下的 这样可以自行进行编译，虽然做不到协助产品的多平台发布，但也有个自行动手编译方式

sorry 原来是有的 
https://copytranslator.gitee.io/support/contributing.html#build-from-source

**Comment by elliottzheng** [comment]
事实上我确实没有编写最新版的编译指南，大概流程是这样的，nodejs12, 然后yarn, yarn rebuild,&nbsp;
调试命令npm run electron:serve
编译命令 npm run electron:build
后两个命令不要用yarn

--------------原始邮件--------------
发件人："nicken ***@***.***&gt;;
发送时间：2022年10月4日(星期二) 下午2:59
收件人："CopyTranslator/CopyTranslator" ***@***.***&gt;;
抄送："Elliott Zheng ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [CopyTranslator/CopyTranslator] 支持ubuntu系统 (#42)
-----------------------------------

 

  
你好 可以提供一个简单的electron实现的编译教程么？在ubuntu下的 这样可以自行进行编译，虽然做不到协助产品的多平台发布，但也有个自行动手编译方式
  
sorry 原来是有的
 https://copytranslator.gitee.io/support/contributing.html#build-from-source

**Comment by nicken** [comment]
好的 感谢  我这边试一下
期待后续能有个编译指南！
