### ISSUE TITLE
[Features] 添加DeepL翻译选项

### ISSUE THREAD

**Issue by Eric-lxy** [CopyTranslator/CopyTranslator#422]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。
在我使用过程中，我发现只有百度，Google，caiyun，腾讯等翻译选项，没有DeepL的选项。然而，DeepL远远强于它们，它的翻译更自然地道，更贴近母语者说话方式，强烈建议添加DeepL的翻译选项。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。
希望能添加DeepL的翻译选项。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
Duplicate of #237
