### ISSUE TITLE
[Features]希望增加记忆窗口大小和位置的功能

### ISSUE THREAD

**Issue by wq130308** [CopyTranslator/CopyTranslator#426]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
程序设置为专注模式，目前每次完全退出后重新打开程序，窗口的大小和位置都会恢复到默认值，不能直接恢复上一次退出时的大小和位置，每次都需要手动调整，感觉很不方便。

**描述您想要的解决方案**
希望能添加记住窗口大小和位置的功能，这次每次打开就可以直接使用了，不需要再手动调整了。

**描述您考虑过的替代方案**
没有替代方案。

**附加背景**
在全新系统中安装10.0.0-beta5，首次运行，设置为专注模式，完全退出重新运行即存在不能记住窗口大小和位置的问题，排除是系统问题。
另外我看作者很久都没发布新版本了。我觉得可以出一个收费版，我愿意付费，谢谢作者。

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢

**Comment by happyTonakai** [comment]
CopyTranslator v10.0.0 stable，有同样的问题，每次调整窗口的大小之后，退出再次打开又会恢复默认的窗口大小，每次退出时，配置文件conpytranlator.json中的
```
    "horizontal": {
        "fontSize": 26,
        "x": 535,
        "y": 186,
        "height": 600,
        "width": 1094
    },
    "vertical": {
        "fontSize": 20,
        "x": 1906,
        "y": 139,
        "height": 600,
        "width": 1094
    },
    "focus": {
        "fontSize": 15,
        "x": 1906,
        "y": 154,
        "height": 600,
        "width": 1094
    },
```
字段都会自动恢复

**Comment by happyTonakai** [comment]
```
    "contrast": {
        "x": 535,
        "y": 186,
        "height": 600,
        "width": 694
    },
    "settings": {
        "x": 1390,
        "y": 133,
        "height": 787,
        "width": 415
    },
```
这两个似乎也是

**Comment by elliottzheng** [comment]
找到问题了，我一直是使用右键窗口右上角的缩小按钮来退出程序的，这个退出是能够记忆窗口位置的，但是通过托盘的菜单退出确实没办法记住，会在下个版本修复，您可以暂时使用窗口右上角的缩小按钮来退出程序。

**Comment by happyTonakai** [comment]
实测ok，通过右键右上角缩小按钮退出一次之后，再通过托盘退出也能够记忆了
