### ISSUE TITLE
[Features]考虑增加deepl作为翻译引擎么

### ISSUE THREAD

**Issue by Ultrasty** [CopyTranslator/CopyTranslator#441]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
deepl比谷歌翻译和百度翻译翻译的更准确

**描述您想要的解决方案**
添加deepl作为翻译引擎

**描述您考虑过的替代方案**
添加deepl作为翻译引擎

**附加背景**
deepl比谷歌翻译和百度翻译翻译的更准确，举例如下，画红框处为错误翻译

<img width="1145" alt="feffb515112edc599fb3b3ab0661926" src="https://user-images.githubusercontent.com/51046846/166487632-92acf00c-5b5b-49b0-9b47-98a485837d28.png">
<img width="1112" alt="686d1a3a0ea1334ef2496193017611e" src="https://user-images.githubusercontent.com/51046846/166487646-2816e41b-64b0-4b2d-a223-1d32b528e301.png">
<img width="1000" alt="280453f0bd21ab1c91056ca56204316" src="https://user-images.githubusercontent.com/51046846/166487657-9e995b98-2419-4025-83c5-fb018ef07679.png">

**Comment by elliottzheng** [comment]
Duplicate of #237
