### ISSUE TITLE
标题栏图标不显示

### ISSUE THREAD

**Issue by lc461184174** [CopyTranslator/CopyTranslator#448]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：10.0.1
 - 出现问题时的模式：所有模式
 - 操作系统：win11beta 专业版  64位
 - 安装路径: E:\\Copytranslator
 - 额外配置：1080p屏幕

### 如何复现这个问题

详细描述问题的现象：
每次打开都不显示图标
![1](https://user-images.githubusercontent.com/17529380/169104888-bed1caf0-f270-48d4-a1e2-cc5219588f8f.jpg)

详细描述重现问题的步骤：
只要打开就是这样，最近两天出现的，所有10的版本都是这样，9的没问题

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/8718628/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
已经关闭安全管家软件等

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
无关

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
无关

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
最近两天出现的，所有10的版本都是这样，9的没问题

**Comment by elliottzheng** [comment]
这个是因为使用了在线的cdn加速的css，我昨天有时候也会加载不出来，跟网络有关系。我会尝试解决

**Comment by hanliren** [comment]
最主要的还不是这个不能显示的问题，而是这个软件，现在打开非常卡慢，不如前两天用流畅了，不知道是不是我开了vpn的原因。但是，VPN关了也还是这样，我现在两个10的版本都用过了，发现反复这样，基本上能够复现这个问题。

**Comment by Pecuer** [comment]
我也是这样 不过还好 不影响使用

**Comment by fuliti** [comment]
> 这个是因为使用了在线的cdn加速的css，我昨天有时候也会加载不出来，跟网络有关系。我会尝试解决

同样，我也是这样，第一次打开主界面会全是白色，设置页面也是这样，第一次打开会是白色。需要过一段时间，才会加载出来。不过如楼上一样，不影响使用。我用的是copytranslator.Setup.10.0.1安装版，系统是win10

**Comment by Guan-t7** [comment]
> 这个是因为使用了在线的cdn加速的css，我昨天有时候也会加载不出来，跟网络有关系。我会尝试解决

是有什么原因吗？在线渲染标题栏实在不make sense，离线状态如果是新用户岂不是都无法进行导航

**Comment by SaraKale** [comment]
我也是无法显示图标，我还以为是我的系统问题，原来大家都一样。我记得当时下10.0初版还能显示，现在更新了10.0.3图标就不显示了，虽然还能用，但是忘记原本是个啥样了……希望能恢复_(:з)∠)_
