### ISSUE TITLE
“记忆专注模式的窗口大小，位置”这一功能在多屏下不能正确使用

### ISSUE THREAD

**Issue by 578123043** [CopyTranslator/CopyTranslator#45]
**描述问题**
“记忆专注模式的窗口大小，位置”这一功能在多屏下不能正确使用

另外有两个小建议：
 取消自动隐藏模式，也就是双击任务栏图标也不会讲窗口隐藏
只能有一个窗口存在，减少不必要的api访问

自动隐藏也太不方便了，怎么想的加的这个功能啊

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：最新版
 - 出现问题时的模式：专注模式
 - 操作系统：如win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 多屏，将屏幕切换至副屏幕
2. 关闭多屏
3. 专注模式窗口消失

**Comment by elliottzheng** [comment]
> 取消自动隐藏模式，也就是双击任务栏图标也不会讲窗口隐藏
>只能有一个窗口存在，减少不必要的api访问
自动隐藏也太不方便了，怎么想的加的这个功能啊

我不知道你在这里说的自动隐藏是什么，copytranslator只有贴边隐藏这个功能，但是与你描述的并不一样。
![image](https://user-images.githubusercontent.com/22427645/52933779-5d4a4880-338f-11e9-9d34-2e77c756028e.png)

**原有的python实现对于多屏的支持并不好，我不会尝试修复这个问题。 如果新版本electron的实现发布后仍有此问题，欢迎重新打开issue.**

**Comment by 578123043** [comment]
我问题是无法找到专注模式的窗口。重新安装软件无效。

我曾经使用过扩展屏幕，因此怀疑专注模式的窗口被记忆在了一个显示器之外的区域。

自动隐藏指的是窗体最小化时，任务栏中的图标也会被隐藏。
类似的功能我只在退出杀毒软件中见过，我觉得意义不大。

为了解决这个问题，**能否告诉我“记忆专注模式的窗口大小，位置”相关的文件在哪里**，我删除一下。


另外，我认为确认每次只有一个软件正在运行是一个非常好的建议

非常感谢您的软件！

**Comment by 578123043** [comment]
我找到了一个Clean.bat文件，现在可以正确使用了
再次感谢您的软件
