### ISSUE TITLE
添加Microsoft Translator 以及DeepL 

### ISSUE THREAD

**Issue by everxq** [CopyTranslator/CopyTranslator#450]
您的功能请求是否与问题有关？请描述一下.
### 添加Microsoft Translator 以及DeepL

描述您想要的解决方案
### 这两个机器翻译的质量应该是目前业界最佳的了。而且Qtranslate和Omega CAT中都成功添加，Copytranslator应该也可以实现吧

附加背景

**Comment by kirayuta** [comment]
请求添加deepl

**Comment by hjie** [comment]
请求添加微软

**Comment by elliottzheng** [comment]
尝试 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.2.0
