### ISSUE TITLE
[Features] 尝试一下离线OCR文字识别？

### ISSUE THREAD

**Issue by Wind-stormger** [CopyTranslator/CopyTranslator#451]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
目前在线OCR都不太好弄了，但要不要考虑一下离线OCR文字识别?

**描述您想要的解决方案**
可以尝试引入[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 。

**描述您考虑过的替代方案**
暂无考虑过的替代方案。

**附加背景**
[PP-OCR系列模型列表](https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md) 。

**Comment by elliottzheng** [comment]
我最近正有此意，感谢您提供的参考链接

**Comment by elliottzheng** [comment]
可以试下这个 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.1.0

**Comment by Wind-stormger** [comment]
好的哦~
