### ISSUE TITLE
双语对照标记

### ISSUE THREAD

**Issue by everxq** [CopyTranslator/CopyTranslator#459]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：

**### 在腾讯翻译的前期版本中，如果原文是一整段，将鼠标移动到某一句英文上，会同时高亮单句原文和对应的译文。腾讯翻译在迭代之后，增加了双语模式。**

您的功能请求是否与问题有关？请描述一下.

**### 如果文本较多（比如整段），通过高亮的形式来对应单句原文和译文，能够更快速地比对不同引擎的译文。毕竟机翻的译文，不同引擎准确度不尽相同差异，进行比对十分有必要。**

描述您想要的解决方案

**### 在多引擎的情况下，我觉得可以参考腾讯的高亮模式，在选定单句原文时，对应的译文同时也出现高亮，便于直观地进行比对**

描述您考虑过的替代方案

**### 也许可以考虑双语模式（似乎更复杂了）**

附加背景

**### 腾讯翻译在译文对话框的右下角有“双语模式” https://fanyi.qq.com/ 
在多译app中,有个”高亮差异“：显示翻译引擎结果的不同之处，方便比对。还可以点击高亮，复制差异内容。但是我觉得实用性并不大。 https://duoyiapp.com/**

**Comment by elliottzheng** [comment]
Duplicate of #198
