### ISSUE TITLE
我已经在ubuntu系统下的docker环境成功安装，但是我建议官方可以在后续开发中增添pdf功能，这将会带来很大的受众和好处。

### ISSUE THREAD

**Issue by KangChou** [CopyTranslator/CopyTranslator#463]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：

我已经在ubuntu系统下的docker环境成功安装，但是我建议官方可以在后续开发中增添pdf功能，这将会带来很大的受众和好处。
![image](https://user-images.githubusercontent.com/36963108/188898237-ad2e12f8-2937-44fa-8c16-d1a69986eaf7.png)

**您的功能请求是否与问题有关？请描述一下.**
我已经在ubuntu系统下的docker环境成功安装，但是我建议官方可以在后续开发中增添pdf功能，这将会带来很大的受众和好处。
**描述您想要的解决方案**
我已经在ubuntu系统下的docker环境成功安装，但是我建议官方可以在后续开发中增添pdf功能，这将会带来很大的受众和好处。
**描述您考虑过的替代方案**
我已经在ubuntu系统下的docker环境成功安装，但是我建议官方可以在后续开发中增添pdf功能，这将会带来很大的受众和好处。

**附加背景**
![image](https://user-images.githubusercontent.com/36963108/188897545-5c14e099-bcc3-4f65-85f3-6d43cdb6d7ce.png)

**Comment by elliottzheng** [comment]
pdf解析以及全文翻译功能是copytranslator在创造出来的时候就不打算做的，您可以使用其他的软件进行pdf的全文翻译或者解析
