### ISSUE TITLE
[将WORD文档做中英双语按段落对照翻译，另存为”translate-文件名“新word文档]

### ISSUE THREAD

**Issue by luyiaya** [CopyTranslator/CopyTranslator#468]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。

将WORD文档做中英双语按段落对照翻译，另存为”translate-文件名“新word文档。
因为很多pdf可以直接转换成word文档，而对word文档的内容可以较容易实现复制和追加翻译内容，所以可以做中英对照翻译的结果，并以段落为基本单元来进行排版。翻译过程可以一句一句的来，显示结果为一段一段的中英文对照 。是否可以实现。谢谢！

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by luyiaya** [comment]
我之前一直用的一个网友开发的word翻译软件，但采用的是baidu的翻译API，最近百度翻译API开始收费，用不了了，现在googleAIP是否可用？

**Comment by elliottzheng** [comment]
全文翻译功能与copytranslator的对照翻译的用法可以说背道而驰，在创造出来的时候就不打算做的，您可以使用其他的软件进行pdf的全文翻译或者解析。

关于谷歌api的可用性，可以参照这里 
https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.3
