### ISSUE TITLE
这个软件不是开源的吗？有网站在收费，我已经举报了，请更多人参与一起举报

### ISSUE THREAD

**Issue by yongqianxiao** [CopyTranslator/CopyTranslator#469]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
感谢大神们写的这个软件，为我们菜鸟阅读英文资料提供了极大的方便，但这个软件目前不是开源的吗？我今天搜索下载的时候，发现一个网站正在售卖 CopyTranslator，还打出正版的旗号，顿时感觉各位贡献者的辛勤付出，却被人拿去赚钱，感觉极其离谱，但我不知道怎么举报，因此上这里来告诉大家，望大家查证，一起举报

**您的功能请求是否与问题有关？请描述一下.**
网站的网址为：http://zj56.yingxunsz.cn/copytranslator/

**描述您想要的解决方案**
有懂法的人能知道该怎么举报吗

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
![image](https://user-images.githubusercontent.com/51198586/192126872-92c2a2c3-9f4c-48b7-a362-a65f257988b4.png)

**Comment by elliottzheng** [comment]
感谢您的支持，这个页面已经404了
