### ISSUE TITLE
[Features] 请求增加自定义主界面背景颜色功能或加入深色模式

### ISSUE THREAD

**Issue by lengmo1996** [CopyTranslator/CopyTranslator#472]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
白色背景在长时间工作时会比较刺眼。

**描述您想要的解决方案**
能够自定义主界面背景颜色，或加入深色模式

**描述您考虑过的替代方案**
背景颜色如果不能自定义，可以出几个较为护眼的主题颜色做为替代。

**附加背景**
![image](https://user-images.githubusercontent.com/40485465/192211421-466370cf-6d3c-42ee-b360-4987afcdeeed.png)

**Comment by elliottzheng** [comment]
软件是有深色模式（夜间模式）的，你可以在设置开关页面打开
