### ISSUE TITLE
您好，我的copy无法使用谷歌翻译，上面谷歌标志显示是红色。复制的文本无法翻译。

### ISSUE THREAD

**Issue by ZXEQzzg** [CopyTranslator/CopyTranslator#473]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：如 v8.4.0
 - 出现问题时的模式：对照模式或专注模式
 - 操作系统：如win10 64位 专业版/win 7 32位 
 - 安装路径: 请确保安装路径中不含有中文或空格
 - 额外配置：补充一些问题相关的配置如 双屏，4K屏，字体缩放尺寸等。

### 如何复现这个问题

详细描述问题的现象：

详细描述重现问题的步骤：

1. 
2. 
4. 

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by luyiaya** [comment]
你用浏览器直接使用translate.google.cn会发现根本无法连接，这不是本软件的问题，网络问题，马上要开两会，所以对防火墙又加高了，你的问题根源在这

**Comment by ZXEQzzg** [comment]
> 你用浏览器直接使用translate.google.cn会发现根本无法连接，这不是本软件的问题，网络问题，马上要开两会，所以对防火墙又加高了，你的问题根源在这

应该不是，因为我在韩国，现在谷歌可以正常使用。我下了9版本是可以使用谷歌的，但是10版本我研究了几回都不能使用（不响应）

**Comment by ZXEQzzg** [comment]
请问还有什么方法可以解决嘛？

**Comment by zyZYqwer** [comment]
我也是这样，前几天还好好地，近两天谷歌也显示红点，用不了

**Comment by Darren-greenhand** [comment]
Google Translate's website has been changed recently. Maybe the APIs have been changed too. Please check this

**Comment by ZhangQingsen** [comment]
我也是这样的问题，应该是9月下旬开始的，同时人在国内，translate.google.cn可以访问。

> 你用浏览器直接使用translate.google.cn会发现根本无法连接，这不是本软件的问题，网络问题，马上要开两会，所以对防火墙又加高了，你的问题根源在这

**Comment by AbandonSSR** [comment]
translate.google.cn停止服务了，打开后让使用translate.google.com.hk

**Comment by SagacityPuppy** [comment]
> translate.google.cn停止服务了，打开后让使用translate.google.com.hk

10月1号后出现的情况，说是谷歌翻译的cn域名都转为了静态网页，香港服务器可以访问而且只提供繁体中文服务（无论英译中、中译英），还不知道是不是两会的原因，感觉关系不大。

**Comment by elliottzheng** [comment]
感谢反馈，我会调查一下

**Comment by kunagisa9** [comment]
我也是这个情况，但我人在国外，用的国外的网，不需要翻墙可以直连，但谷歌翻译也是红的，用不了，应该不是墙的问题

**Comment by Pull256** [comment]
我尝试使用proxifier对copytranslator的流量进行代理，但日志显示copytranslator并没有走这边的代理，用抓包软件fidder classic抓包也完全无法抓到copytranslator发送的数据包，以至于不能定位copytranslator的请求连接，就似乎copytranslator和uwp应用一样根本不会走系统的代理一样。

**Comment by 1363279100** [comment]
美国谷歌公司星期一(10月3日)宣布，因使用率低而终止了在中国大陆的谷歌翻译服务，这一变化将影响一直以来中国大陆用户还可以使用的谷歌翻译以及Chrome的内置翻译功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CopyTranslator/CopyTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 上午6:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CopyTranslator/CopyTranslator] 您好，我的copy无法使用谷歌翻译，上面谷歌标志显示是红色。复制的文本无法翻译。 (Issue #473)





 
我也是这个情况，但我人在国外，用的国外的网，不需要翻墙可以直连，但谷歌翻译也是红的，用不了，应该不是墙的问题

**Comment by 1363279100** [comment]
美国谷歌公司星期一(10月3日)宣布，因使用率低而终止了在中国大陆的谷歌翻译服务，这一变化将影响一直以来中国大陆用户还可以使用的谷歌翻译以及Chrome的内置翻译功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月4日(星期二) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [CopyTranslator/CopyTranslator] 您好，我的copy无法使用谷歌翻译，上面谷歌标志显示是红色。复制的文本无法翻译。 (Issue #473)





 
我尝试使用proxifier对copytranslator的流量进行代理，但日志显示copytranslator并没有走这边的代理，用抓包软件fidder classic抓包也完全无法抓到copytranslator发送的数据包，以至于不能定位copytranslator的请求连接，就似乎copytranslator和uwp应用一样根本不会走系统的代理一样。

**Comment by elliottzheng** [comment]
有没有一种可能，我已经发布了新版本来解决这个问题，您试过新版本了吗？

--------------原始邮件--------------
发件人："GeekSnail ***@***.***&gt;;
发送时间：2022年10月7日(星期五) 凌晨4:58
收件人："CopyTranslator/CopyTranslator" ***@***.***&gt;;
抄送："Elliott Zheng ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [CopyTranslator/CopyTranslator] 您好，我的copy无法使用谷歌翻译，上面谷歌标志显示是红色。复制的文本无法翻译。 (Issue #473)
-----------------------------------

 

 
前几天chrome翻译不能用，今天尝试开启全局代理，浏览器google翻译又能用了；但打开此软件google翻译还是不能用，是不是没有使用系统代理？

**Comment by ZXEQzzg** [comment]
> 有没有一种可能，我已经发布了新版本来解决这个问题，您试过新版本了吗？
> […](#)
> --------------原始邮件-------------- 发件人："GeekSnail ***@***.***&gt;; 发送时间：2022年10月7日(星期五) 凌晨4:58 收件人："CopyTranslator/CopyTranslator" ***@***.***&gt;; 抄送："Elliott Zheng ***@***.***&gt;;"State change ***@***.***&gt;; 主题：Re: [CopyTranslator/CopyTranslator] 您好，我的copy无法使用谷歌翻译，上面谷歌标志显示是红色。复制的文本无法翻译。 (Issue #473) ----------------------------------- 前几天chrome翻译不能用，今天尝试开启全局代理，浏览器google翻译又能用了；但打开此软件google翻译还是不能用，是不是没有使用系统代理？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

立马去试

**Comment by ryanpan** [comment]
修改 hosts 的方式疑似失效了,谷歌翻译无法使用
https://hcfy.app/blog/2022/09/28/ggg
