### ISSUE TITLE
[Features]拥有焦点的进程切换后自动关闭/打开拖曳复制

### ISSUE THREAD

**Issue by OnlyOneHeroism** [CopyTranslator/CopyTranslator#475]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
打开拖曳复制后总是忘记关掉。

**描述您想要的解决方案**
监听当前拥有焦点的进程名，设置仅在某个进程拥有焦点时启用拖曳复制。

**描述您考虑过的替代方案**
监听到alt+tab或者win+tab时关闭拖曳复制。
**附加背景**
无。

**Comment by elliottzheng** [comment]
很有帮助的建议 https://github.com/sindresorhus/active-win

**Comment by elliottzheng** [comment]
10.2.4后可以启用拖拽复制白名单，仅白名单内的程序会触发拖拽复制，待新版本发布后可以尝试，也启用拖拽复制黑名单，把某些程序列入黑名单不触发。
