### ISSUE TITLE
谷歌翻译国内停止服务，但是win10系统，安装后自动设置HOSTS时报错

### ISSUE THREAD

**Issue by elliottzheng** [CopyTranslator/CopyTranslator#481]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

 windows10系统，安装后设置HOSTS时出现这个问题，我卸载后重试了无数遍，还是出现这个问题。但是另一台的win7电脑安装后就没问题，可以用google翻译了，而win10的这个就一直不行。求助！谢谢！
![image](https://user-images.githubusercontent.com/49467246/195021893-25a6de7a-7f73-437b-b8be-0d687252166f.png)

_Originally posted by @MrGongqi in https://github.com/CopyTranslator/CopyTranslator/issues/235#issuecomment-1274203206_

**Comment by elliottzheng** [comment]
@MrGongqi

如果自动设置失败的话，只能麻烦你先自己设置一下hosts
```
180.163.151.162 translate.googleapis.com 
```
加上这条然后刷新一下dns，更具体的可以参考这个链接 https://hcfy.app/blog/2022/09/28/ggg

**Comment by MrGongqi** [comment]
谢谢，，按照你推荐的方法，已经处理好了。非常感谢！！
