### ISSUE TITLE
按Ctrl调整字体大小

### ISSUE THREAD

**Issue by Huia29** [CopyTranslator/CopyTranslator#483]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
目前无法调整Copytranslator中字体的大小，会给阅读带来部分障碍

**描述您想要的解决方案**
希望可以通过笔记本触控板和按Ctrl调整字体大小，实现缩放

**描述您考虑过的替代方案**
目前没考虑过，抱歉

**附加背景**
<img width="416" alt="image" src="https://user-images.githubusercontent.com/115720467/195623779-b8d336d6-dddf-45be-b7eb-4c3333a40a53.png">字体只能锁定在一个大小，在长时间阅读时会产生疲惫感

**Comment by elliottzheng** [comment]
我非常奇怪，为什么您有空提issue，没有空看一下使用指南呢，我花了很大精力写的使用指南。
![image](https://user-images.githubusercontent.com/22427645/195625669-8b6d34af-ed9a-4f73-84c6-30b3c37a1da3.png)

在提出issue的时候，我的关于issue的提示写了这么一大段就直接忽略？

关于字体大小的issue别人也提了近十个，建议您搜索一下看下？
![image](https://user-images.githubusercontent.com/22427645/195625854-66564d0f-c941-45fc-aedb-b9d7dabee002.png)

![image](https://user-images.githubusercontent.com/22427645/195626075-38db88f0-05d5-487a-aee2-8ef7fae7602e.png)


建议您认真学习一下[GitHub-Issue 正确的提问方式](https://zhuanlan.zhihu.com/p/75691927)，当然并不是针对您，只是这个想想比较普遍了

**Comment by elliottzheng** [comment]
Duplicate of #374

**Comment by Huia29** [comment]
抱歉，我第一次使用这个平台，很多东西还在学习。抱歉给您造成了麻烦
