### ISSUE TITLE
[Bug]长文翻译结果的自动换行丢失部分字符

### ISSUE THREAD

**Issue by tyde7** [CopyTranslator/CopyTranslator#484]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：10.1.0
 - 出现问题时的模式：所有模式
 - 操作系统：win11 64位
 - 安装路径: D:\Copy Translator
 - 额外配置：双屏幕，一个屏幕4K

### 如何复现这个问题

详细描述问题的现象：

详细描述重现问题的步骤：

1. 复制一段长文，例如
> As companies utilize data to improve their user experiences and operations, it becomes increasingly important that [the infrastructure supporting the creation and maintenance of machine learning models](https://doordash.engineering/2020/04/23/doordash-ml-platform-the-beginning/) is scalable and will enable high productivity. DoorDash recently faced this issue concerning its search scoring and ranking models: the high demands on CPU and memory resources caused new model production to be unscalable. Specifically, the growth in feature numbers per added model would have been unsustainable, forcing us to reach our maximum CPU and/or RAM constraints too quickly.
2. 中文翻译部分自动换行有问题，行末丢失字符
<img width="689" alt="image" src="https://user-images.githubusercontent.com/32335591/196030902-934fceea-5754-407c-aef8-e4d233db7241.png">

实际上复制出来的翻译文本（加粗部分没有正确被换行~）
> 随着公司利用数据来改善用户体验和运营，[支持创建和维护机器学习模型的基础设施]（https://doordash.engineerin**g/2020/04/23/doordash-**ml-platform）变得越来越重要 -the-beginning/) 是可扩展的，可以提高生产力。  DoorDash 最近在搜索评分和排名模型方面遇到了这个问题：对 CP**U 和内存资源的高****要求导致**新模型生产无法扩展。 具体来说，每个添加模型的特征数量增长将是不可持续的，迫使我们过快地达到最大 CPU 和/或 RAM 限制。
### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**

[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/9794231/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

无关

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**

无关

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

无关

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

长文

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
第一次使用

**Comment by elliottzheng** [comment]
这个是谷歌翻译的问题，跟copytranslator没关系，我把那段文字直接直接放到网页版谷歌翻译里，得到的就是跟你发出来的一模一样的结果，你也可以自己试试，谷歌翻译本来就有问题的话我是没有办法解决的，我这软件只负责帮你调用谷歌翻译。
![image](https://user-images.githubusercontent.com/22427645/196033179-74943ab7-3f9a-4e30-aa37-1ba635391b91.png)
