### ISSUE TITLE
谷歌translate和deepl翻译均失效

### ISSUE THREAD

**Issue by Frankma75** [CopyTranslator/CopyTranslator#486]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

### 系统环境（请填写以下信息）

 - CopyTranslator版本：V10.1.0;V10.2.0;V10.2.1
 - 出现问题时的模式：对照布局、专注模式、垂直布局
 - 操作系统：win11 64位 专业版 版本 21H2 操作系统版本	22000.1098 
 - 安装路径: C:\Program Files\copytranslator
 - 额外配置：无。

### 如何复现这个问题

详细描述问题的现象：
使用谷歌翻译时，短暂可以正常使用，但是翻译1-2次后会翻译失败，需要重新其中软件
其中已经使用自动和手动Hosts尝试，均为相同的故障；
Deepl翻译模式下，会提示正在翻译（黄色标记）很久，之后报错（红色标记）
多源对照下仅有Bing、Baidu、caiyun源。

详细描述重现问题的步骤：

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/9832277/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
未开启任何可能冲突软件；

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
在任何途径复制的文本均无法翻译。

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by Frankma75** [comment]
by the way，请问大佬能不能增加一个可以使用科学上网的方法访问谷歌翻译的功能，我不是相关专业的，不太清楚难度，如果方便的化望开发者解答！

**Comment by ryanpan** [comment]
我也发现同样的问题
操作系统：win10 64位 专业版 版本 22H2 19045.2130
CopyTranslator版本 v10.1.0

**Comment by elliottzheng** [comment]
试一下最新版本的
https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.2.2
应该是只要网页代理就可以上了

**Comment by ryanpan** [comment]
新版本，可以用了，谢谢

**Comment by Frankma75** [comment]
已经可以使用了，感谢开发者的用心，感谢！

**Comment by Jf710001011** [comment]
又失效了吗

**Comment by Jf710001011** [comment]
又失效了

**Comment by laoliloal** [comment]
又失效了。

### 描述问题
系统环境（请填写以下信息）
CopyTranslator版本：V10.0.1;V11.0.0（一直使用v10，出现故障后升级至v11，故障依然存在）
出现问题时的模式：对照布局、专注模式、垂直布局
操作系统：win10 64位
安装路径: C:\Program Files\copytranslator
额外配置：无。
### 如何复现这个问题

使用谷歌翻译时，会提示正在翻译（黄色标记）很久，之后报错（红色标记）。
Deepl翻译模式表现同理，但代理软件出现以下内容：
```
2023/04/07 14:05:23 127.0.0.1::xxx accepted //www.deepl.com:443 [proxy]
2023/04/07 14:05:25 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
2023/04/07 14:05:25 127.0.0.1:xxx accepted //w.deepl.com:443 [proxy]
2023/04/07 14:05:26 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
2023/04/07 14:05:26 127.0.0.1::xxx accepted //w.deepl.com:443 [proxy]
```
使用代理v2rayN，尝试打开&关闭代理软件，故障不变。网页可正常访问deepL。



### 详细描述重现问题的步骤：

请回答以下问题
已知软件可能在某些环境下与某些软件存在冲突，请逐个退出其他非必要软件，测试问题是否仍然存在。
无，前几天还好用，今天突然不行了，上面也有人提到这个问题；

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？请多测试几个阅读器。
在任何途径复制的文本均无法翻译。

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
否，百度可用

问题与特定文档有关么？如果是特定句子或文件相关，请务必附上文档文件，并说明出问题的段落。
否

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
不清楚

**Comment by Jf710001011** [comment]
> 又失效了。
> 
> ### 描述问题
> 系统环境（请填写以下信息） CopyTranslator版本：V10.0.1;V11.0.0（一直使用v10，出现故障后升级至v11，故障依然存在） 出现问题时的模式：对照布局、专注模式、垂直布局 操作系统：win10 64位 安装路径: C:\Program Files\copytranslator 额外配置：无。
> 
> ### 如何复现这个问题
> 使用谷歌翻译时，会提示正在翻译（黄色标记）很久，之后报错（红色标记）。 Deepl翻译模式表现同理，但代理软件出现以下内容：
> 
> ```
> 2023/04/07 14:05:23 127.0.0.1::xxx accepted //www.deepl.com:443 [proxy]
> 2023/04/07 14:05:25 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
> 2023/04/07 14:05:25 127.0.0.1:xxx accepted //w.deepl.com:443 [proxy]
> 2023/04/07 14:05:26 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
> 2023/04/07 14:05:26 127.0.0.1::xxx accepted //w.deepl.com:443 [proxy]
> ```
> 
> 使用代理v2rayN，尝试打开&关闭代理软件，故障不变。网页可正常访问deepL。
> 
> ### 详细描述重现问题的步骤：
> 请回答以下问题 已知软件可能在某些环境下与某些软件存在冲突，请逐个退出其他非必要软件，测试问题是否仍然存在。 无，前几天还好用，今天突然不行了，上面也有人提到这个问题；
> 
> **问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？请多测试几个阅读器。 在任何途径复制的文本均无法翻译。
> 
> 问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？ 否，百度可用
> 
> 问题与特定文档有关么？如果是特定句子或文件相关，请务必附上文档文件，并说明出问题的段落。 否
> 
> 之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号 不清楚

描述问题
系统环境（请填写以下信息）
CopyTranslator版本：最近从v11.0.0出现deepl和google翻译均失效，升级至V11.0.2,仍然存在问题
出现问题时的模式：专注模式、垂直布局
操作系统：win11 professional workstation 64位
安装路径: D:\Copytranslator v11.0.2
额外配置：无。

如何复现这个问题
使用谷歌翻译时，会提示正在翻译（黄色标记）很久，之后报错（红色标记）。
Deepl翻译模式表现同理，但代理软件出现以下内容：

2023/04/07 14:05:23 127.0.0.1::xxx accepted //www.deepl.com:443 [proxy]
2023/04/07 14:05:25 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
2023/04/07 14:05:25 127.0.0.1:xxx accepted //w.deepl.com:443 [proxy]
2023/04/07 14:05:26 127.0.0.1::xxx accepted //s.deepl.com:443 [proxy]
2023/04/07 14:05:26 127.0.0.1::xxx accepted //w.deepl.com:443 [proxy]
使用代理v2rayN，尝试打开&关闭代理软件，故障不变。网页可正常访问deepL。

详细描述重现问题的步骤：
请回答以下问题
已知软件可能在某些环境下与某些软件存在冲突，请逐个退出其他非必要软件，测试问题是否仍然存在。
无，前几天还好用，今天突然不行了，上面也有人提到这个问题；

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？请多测试几个阅读器。
在任何途径复制的文本均无法翻译。

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
否，百度可用

问题与特定文档有关么？如果是特定句子或文件相关，请务必附上文档文件，并说明出问题的段落。
否

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
不清楚

### 2022-04-07

**Comment by SDZZGNDRC** [comment]
遇到同样的问题

**Comment by 8877zang** [comment]
我也是，为什么现在deepl都用不了呀

**Comment by illyasiviliss** [comment]
Mac用的11.0版本，我确认我的梯子是好用的，2023年5月还是用不了deepl，谷歌的话直接走proxy不用镜像就好，请问如何解决用不了deepl引擎的问题呢？

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by XiaoSenLuo** [comment]
deepl新改版之后API发生变化了, 需要key了, 设置里没法设置key

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by toprak** [comment]
@elliottzheng I think adding DeepLx support would be awesome.

**Comment by UnsleepingCat** [comment]
> deepl新改版之后API发生变化了, 需要key了, 设置里没法设置key

我也是，deepl无法使用，求作者更新啊！

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by shirleen702** [comment]
deepl google和keyan无法使用，怎么办呢

**Comment by ZhenhongDu** [comment]
同样是deepl和google不能用，但在浏览器里面科学上网能打开谷歌翻译网站的

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by Y-hang-wang** [comment]
使用最新的软件，google翻译一直无法翻译。

**Comment by styuanqn2022** [comment]
2023.11.25 无论是否开代理，Google翻译均无法使用。尝试更改谷歌翻译源（设置），仍然无效。

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by huangyimingnb** [comment]
如果挂了梯子的话 可以参考
解决方案4-使用网络代理
需要将在copytranslator设置界面把谷歌翻译镜像置空，使其回退到使用原版谷歌翻译APIhttps://translate.googleapis.com。

然后在梯子内将 translate.googleapis.com 设为走代理（PROXY）即可。不同的软件有不同的设置方式，你需要阅读你所使用的软件的文档或者通过搜索引擎查询该如何设置。

你也可以给梯子开全局模式，也就是所有域名都走国外IP。但是，国内网站的访问速度会因此变慢，所以还是建议花点时间研究下如何添加代理规则。 然后你需要按照这里的说明[测试谷歌翻译是否恢复正常](https://copytranslator.github.io/guide/questions.html#%E6%B5%8B%E8%AF%95%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%98%AF%E5%90%A6%E6%81%A2%E5%A4%8D%E6%AD%A3%E5%B8%B8)
然后就可以了 我使用的版本是11.0 
![image](https://github.com/CopyTranslator/CopyTranslator/assets/61530232/de3b139b-0332-4973-b699-8fca1976a519)
这是我的设置

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by UnsleepingCat** [comment]
> 如果挂了梯子的话 可以参考 解决方案4-使用网络代理 需要将在copytranslator设置界面把谷歌翻译镜像置空，使其回退到使用原版谷歌翻译APIhttps://translate.googleapis.com。
> 
> 然后在梯子内将 translate.googleapis.com 设为走代理（PROXY）即可。不同的软件有不同的设置方式，你需要阅读你所使用的软件的文档或者通过搜索引擎查询该如何设置。
> 
> 你也可以给梯子开全局模式，也就是所有域名都走国外IP。但是，国内网站的访问速度会因此变慢，所以还是建议花点时间研究下如何添加代理规则。 然后你需要按照这里的说明[测试谷歌翻译是否恢复正常](https://copytranslator.github.io/guide/questions.html#%E6%B5%8B%E8%AF%95%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%98%AF%E5%90%A6%E6%81%A2%E5%A4%8D%E6%AD%A3%E5%B8%B8) 然后就可以了 我使用的版本是11.0 ![image](https://private-user-images.githubusercontent.com/61530232/289407017-de3b139b-0332-4973-b699-8fca1976a519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODY5MTksIm5iZiI6MTcwMjI4NjYxOSwicGF0aCI6Ii82MTUzMDIzMi8yODk0MDcwMTctZGUzYjEzOWItMDMzMi00OTczLWI2OTktOGZjYTE5NzZhNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA5MjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZGQ1NWZkZDQ5Y2ZjNWRlYzQ1MDAzNjAyNTE2YWYyOWVlODU2MDcwZWIwYzlkOGE5ZjNkNjUzNmNmODViMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCMJvipLWBl31KlrzQaoUDpJRe1HchDbhEQva3yRWjo) 这是我的设置

讲真已经不……想折腾了，我对比过医学翻译这块，整体上国内的百度翻译和有道翻译交替使用是能满足我的需求的。Google翻译不能用……唉也就算了吧。

**Comment by PutongK** [comment]
> 如果挂了梯子的话 可以参考 解决方案4-使用网络代理 需要将在copytranslator设置界面把谷歌翻译镜像置空，使其回退到使用原版谷歌翻译APIhttps://translate.googleapis.com。
> 
> 然后在梯子内将 translate.googleapis.com 设为走代理（PROXY）即可。不同的软件有不同的设置方式，你需要阅读你所使用的软件的文档或者通过搜索引擎查询该如何设置。
> 
> 你也可以给梯子开全局模式，也就是所有域名都走国外IP。但是，国内网站的访问速度会因此变慢，所以还是建议花点时间研究下如何添加代理规则。 然后你需要按照这里的说明[测试谷歌翻译是否恢复正常](https://copytranslator.github.io/guide/questions.html#%E6%B5%8B%E8%AF%95%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%98%AF%E5%90%A6%E6%81%A2%E5%A4%8D%E6%AD%A3%E5%B8%B8) 然后就可以了 我使用的版本是11.0 ![image](https://private-user-images.githubusercontent.com/61530232/289407017-de3b139b-0332-4973-b699-8fca1976a519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzk0NDcsIm5iZiI6MTcwNTM3OTE0NywicGF0aCI6Ii82MTUzMDIzMi8yODk0MDcwMTctZGUzYjEzOWItMDMzMi00OTczLWI2OTktOGZjYTE5NzZhNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZWM1MTQyNTExODE2Mzc3ZGZlZjRlMjFhMDM5ZTJlMGI0YWIxYmNlZDZkN2ZkY2I2OGFkMjVkZjhjZjVlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijMTrf4OqsJ795YI0qw1ERSgOkkfIhkc6xwlvI161o8) 这是我的设置

感谢，可以用Google了但Deepl还是有问题。。

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by fanke-zeng** [comment]
> 如果挂了梯子的话 可以参考 解决方案4-使用网络代理 需要将在copytranslator设置界面把谷歌翻译镜像置空，使其回退到使用原版谷歌翻译APIhttps://translate.googleapis.com。
> 
> 然后在梯子内将 translate.googleapis.com 设为走代理（PROXY）即可。不同的软件有不同的设置方式，你需要阅读你所使用的软件的文档或者通过搜索引擎查询该如何设置。
> 
> 你也可以给梯子开全局模式，也就是所有域名都走国外IP。但是，国内网站的访问速度会因此变慢，所以还是建议花点时间研究下如何添加代理规则。 然后你需要按照这里的说明[测试谷歌翻译是否恢复正常](https://copytranslator.github.io/guide/questions.html#%E6%B5%8B%E8%AF%95%E8%B0%B7%E6%AD%8C%E7%BF%BB%E8%AF%91%E6%98%AF%E5%90%A6%E6%81%A2%E5%A4%8D%E6%AD%A3%E5%B8%B8) 然后就可以了 我使用的版本是11.0 ![图像](https://private-user-images.githubusercontent.com/61530232/289407017-de3b139b-0332-4973-b699-8fca1976a519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODE2ODQsIm5iZiI6MTcyOTA4MTM4NCwicGF0aCI6Ii82MTUzMDIzMi8yODk0MDcwMTctZGUzYjEzOWItMDMzMi00OTczLWI2OTktOGZjYTE5NzZhNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyMjMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNzJkZWIwYWEyMGQyMTQ0ODczZWEwODg5MjlmMjUzN2E4NzgxNDRiOWUzNDhiNTU4Y2FjMzg1ZDMyOWE4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lLEyxQ0w_a7pYsyfej1oCzWta8vOH4kl_y3Z1Y7TmL4) 这是我的设置

还是没有用，每次开机后谷歌翻译10分钟正常，然后突然就不翻译了。换全局代理也无效。

**Comment by 8877zang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已收到，谢谢。

**Comment by anleyang** [comment]
我是小洋洋呀，邮件已收到，辛苦啦~我会尽快回复的，mua~
