### ISSUE TITLE
修改“双Ctrl+C”翻译快捷键

### ISSUE THREAD

**Issue by cfikt** [CopyTranslator/CopyTranslator#498]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

#### 须知

1. 反馈前请先查看官网的使用指南，查看使用指南能够解决您90%的疑惑。
2. 请先在Issue中搜索是否有相关issue，重复的issue会直接被关闭。
3. 确保您使用的是最新的稳定版，如果您使用的是旧版本的软件，issue也会直接被关闭，请先尝试最新版。
4. 所有不按照模板填写的issue，我们将不会处理。
5. 请尝试关闭软件后删除[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))重启软件，看看问题是否仍存在。

## 描述问题
由于经常使用SHELL，使用Ctrl+C翻译实现不了，想要修改该快捷键

### 系统环境（请填写以下信息）
 - CopyTranslator版本：v10.2.3

**Comment by elliottzheng** [comment]
这个想要自定义有点困难，因为是写死在程序里的，你是想要翻译shell里的内容还是只是因为shell里触发了拖拽复制会导致程序退出？
