### ISSUE TITLE
待翻译内容较多时会有一定概率出现无响应状况（即等待很久不见翻译结果出现，对照模式下翻译结果栏为空白，专注模式则一直是黄条无内容）

### ISSUE THREAD

**Issue by roison** [CopyTranslator/CopyTranslator#50]
**描述问题**
之前我在如下问题中描述了这种现象
（即等待很久不见翻译结果出现，对照模式下翻译结果栏为空白，专注模式则一直是黄条无内容）。
https://github.com/CopyTranslator/CopyTranslator/issues/49
现在发现，这种情况可能同时和待翻译文本的数量相关。在确保小于谷歌限制的5000字符的条件下，待翻译文字较多时（比如大于1000字符）问题可能出现的概率会更大。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：0.0.7-RC1
 - 出现问题时的模式：对照模式及专注模式
 - 操作系统：win10 64位
 - 阅读器：应该与阅读器无关，我使用notepad++复制TXT文件中的文字也是如此
 - 出现问题的文档：与特定文档无关
 - 出现问题的段落：与特定文档无关

**如何复现这个问题**
重现行为的步骤：
1. 复制一大段英文文字
2. 等待翻译结果，会有一定概率刷新不出来
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
欢迎试用 [0.0.8 尝鲜版](https://github.com/CopyTranslator/CopyTranslator/releases/tag/0.0.8-alpha-win)，虽然他貌似并不能翻译更多，但是他失败得蛮快。。。。旧版本的问题不再处理。如何增加翻译字数限制是一个大问题，我后面会再研究。

**Comment by roison** [comment]
> 欢迎试用 [0.0.8 尝鲜版](https://github.com/CopyTranslator/CopyTranslator/releases/tag/0.0.8-alpha-win)，虽然他貌似并不能翻译更多，但是他失败得蛮快。。。。旧版本的问题不再处理。如何增加翻译字数限制是一个大问题，我后面会再研究。

感谢，新版似乎没有再出现这个问题了，并且新增加了重试翻译功能，点赞！
给新版的两个小建议：
①拷贝TXT文本翻译时多段文本未换行（我想作者您这么做的原因，可能是考虑到从PDF拷贝过来的文本，较难以判断换行是否为同一段落还是新开段落，因此求稳起见都放一起）。可以考虑增加开关决定是否换行。
②字体默认宋体，若能手动指定字体那是最好不过了。

**Comment by elliottzheng** [comment]
你好，自定义字体挺容易的，不过您需要懂一点css， 参看这里 https://github.com/CopyTranslator/CopyTranslator/wiki/Customization-%E8%87%AA%E5%AE%9A%E4%B9%89#stylization，如果对于自定义有疑问的话，可以在gitter发言。

**Comment by roison** [comment]
> 你好，自定义字体挺容易的，不过您需要懂一点css， 参看这里 https://github.com/CopyTranslator/CopyTranslator/wiki/Customization-%E8%87%AA%E5%AE%9A%E4%B9%89#stylization
> 如果对于自定义有疑问的话，可以在gitter发言。

OK，非常感谢
