### ISSUE TITLE
翻译时文字无法自适应窗口大小，导致一部分文字看不到。

### ISSUE THREAD

**Issue by SAYAKA-Konami** [CopyTranslator/CopyTranslator#503]
### 系统环境（请填写以下信息）

 - CopyTranslator版本： 10.2.4
 - 出现问题时的模式：专注模式
 - 操作系统：win11，64位
 - 安装路径: Scoop自动安装

### 如何复现这个问题

详细描述问题的现象：
翻译内容显示不全。
![image](https://user-images.githubusercontent.com/84509280/204115919-8d942570-0870-4bd9-9b5e-28fcf9d36961.png)
且不论如何扩展UI窗口的大小。只要翻译内容过长需要换行就会出现此类情况。
 
白屏：
![image](https://user-images.githubusercontent.com/84509280/204115834-9863bfc7-d06b-47c8-a0d3-6c1ef199600d.png)
目前可以通过切换模式来重置翻译页面

详细描述重现问题的步骤：
白屏：
1. 单机翻译内容所在窗口。按End键即会产生该效果。

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
**这是我的配置文件**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/10097363/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。
A: 是

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
A: 都会出现

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
A: 与翻译引擎无关。

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
A: 无关

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号
A: 我只用过最新版😥

**Comment by elliottzheng** [comment]
感谢反馈，我之前也短暂遇到类似问题，我会调查一下

**Comment by elliottzheng** [comment]
这个问题一般出现在，你切换了配色模式之后，临时的解决方案是如果出现该问题，你可以重启一下软件

**Comment by SAYAKA-Konami** [comment]
你好！我回忆起我刚用的时候似乎没有出现过第一种情况。
我也确实是更改过配色。
现在的情况是重启后第一种情况还是会发生。我会尝试着重装一下看看能否正常使用。
PS: 这仍然是我用过体验最好的一个翻译软件！为开发者的热情点赞！！

**Comment by elliottzheng** [comment]
其实不需要重装，我已经修复了，不过要等下一次更新再一起发布，理论上你开关一下drawer就可以了，这个问题是因为一个数值只有监听到旁边的抽屉的状态变化，才会更新一个东西，但是drawer状态从没变化过的时候这个数值会是错误的，所以你只要打开，关闭一下抽屉就可以了，下面是有问题的，因为那个数值初始化的时候认为抽屉是关闭的，但是其实抽屉是打开的，所以就不对的。
![image](https://user-images.githubusercontent.com/22427645/204207005-ce5313d9-134f-46a0-b562-d0947fba6b8d.png)
这个时候你只要把抽屉关上，这个问题就不再会出现了，之后不管你是否打开抽屉都不会有问题
![image](https://user-images.githubusercontent.com/22427645/204207091-c2213f01-2818-4b92-8efe-95c22b79f307.png)

**Comment by SAYAKA-Konami** [comment]
这个做法确实可以修复~感谢你的耐心👍
