### ISSUE TITLE
[字体放大功能]

### ISSUE THREAD

**Issue by daydayupzhang** [CopyTranslator/CopyTranslator#504]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
使用时感觉字体过小，从文档到翻译眼睛转换时不宜流畅地定位到要看的地方

**描述您想要的解决方案**
增加翻译文本字体放大的设置，因为放大后的字体比较醒目，使用体验会好很多
参考这个的效果：
https://www.bilibili.com/video/BV1e3411A7gS/?spm_id_from=333.337.search-card.all.click&vd_source=5b208114ae32f324c7db75c5e24b1dff
**描述您考虑过的替代方案**
1.手机外挂翻译  https://www.bilibili.com/video/BV1e3411A7gS/?spm_id_from=333.337.search-card.all.click&vd_source=5b208114ae32f324c7db75c5e24b1dff
2. 更改屏幕的分辨率

**附加背景**
![image](https://user-images.githubusercontent.com/16831626/205031477-b46c3ebf-8af6-4c7e-b662-b055f1eab38c.png)

**Comment by elliottzheng** [comment]
字体大小本来就是可以调节的，参见这里 https://github.com/CopyTranslator/CopyTranslator/issues/483#issuecomment-1277721109

另外，在下一个版本，原文和译文的字体大小将能独立调节，因此可以这样
![image](https://user-images.githubusercontent.com/22427645/205036312-b2f34b7e-c795-4708-9d98-658b888f6d96.png)

**Comment by elliottzheng** [comment]
Duplicate of #374

**Comment by daydayupzhang** [comment]
非常棒，非常感谢，下次先仔细看看文档再提issue哈哈
