### ISSUE TITLE
似乎被贩卖

### ISSUE THREAD

**Issue by ETOemperor** [CopyTranslator/CopyTranslator#505]
<a href="http://jsx.njcyt88.com/h-col-349.html">去看下</a>

**Comment by elliottzheng** [comment]
感谢您的反馈，对于软件被贩卖这个事，我也没有啥好的办法，我在软件里面也加了相关的说明，要维权非常困难，我并不想花精力去处理。像这种平台也就骗骗小白，同时他侵权的可太多了，光脚的不怕穿鞋的。
Duplicate of #469
