### ISSUE TITLE
翻译后失去光标

### ISSUE THREAD

**Issue by AnYu798** [CopyTranslator/CopyTranslator#522]
### 系统环境（请填写以下信息）

 - CopyTranslator版本： v11.0
 - 出现问题时的模式：
 - 操作系统：如win10 64位 LTSC
 - 安装路径: D:\App\copytranslator
 - 额外配置：无

### 如何复现这个问题

详细描述问题的现象：
正常在编辑文档时,复制一段需要翻译的词,copyTranslator上的翻译图标会变黄色 代表正在翻译, 重新变化绿色即翻译完成.在翻译完成后 文档编辑器失去光标, 需要再次点击一下编辑器才能继续编辑

详细描述重现问题的步骤：

1. 设置copyTranslator置顶/鼠标穿透 打开任意文本编辑器
2. 点击文本编辑器,复制一段需要翻译的文本
4. copyTranslator上的翻译图标会变黄色 代表正在翻译, 重新变化绿色即翻译完成.在翻译完成后 文档编辑器失去光标, 需要再次点击一下编辑器才能继续编辑

### 请回答以下问题

问题出现时，当时的CopyTranslator的设置是怎么样的？**请将[配置文件夹]([https://copytranslator.gitee.io/guide/questions.html#copytranslator%E7%9A%84%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C](https://copytranslator.gitee.io/guide/questions.html#copytranslator的配置目录在哪里))打包为压缩包并上传到此处。**
[copytranslator.zip](https://github.com/CopyTranslator/CopyTranslator/files/10335127/copytranslator.zip)

已知软件可能在某些环境下与某些软件存在冲突，**请逐个退出其他非必要软件，测试问题是否仍然存在**。

**问题与特定阅读器有关吗？**还是在浏览器及其他的阅读器也不可以使用？**请多测试几个阅读器。**
word/notepad++/notepad/Intelli Idea

问题与特定翻译引擎有关吗？**请务必测试其他翻译引擎是否有类似问题？**如果是不能翻译，是不是全部都不能用呢？
无

问题与特定文档有关么？如果是特定句子或文件相关，**请务必附上文档文件**，并说明出问题的段落。
word/notepad++/notepad/Intelli Idea

之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该问题的版本号

**Comment by elliottzheng** [comment]
您试试关闭自动显示功能？

**Comment by AnYu798** [comment]
关闭自动显示后,使用编辑器复制需要翻译的词,编辑器没有失去光标了
