### ISSUE TITLE
如何设置快捷键能迅速打开和隐藏窗口呢

### ISSUE THREAD

**Issue by toiaz** [CopyTranslator/CopyTranslator#523]
希望能够增加快捷键。谢谢。感谢。

**Comment by elliottzheng** [comment]
参考这里设置全局快捷键
https://copytranslator.github.io/guide/11.0.0.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE
在下面的例子里，我把显示窗口设置为shift+F1，隐藏窗口设置为shift+F2
```json
{
    "showWindow": "Shift+F1",
    "hideWindow": "Shift+F2",
    "simulateCopy": "Super+`",
    "simulateIncrementCopy": "Super+Shift+`",
    "version": "v11.0.1 破晓"
}
```

**Comment by toiaz** [comment]
I see.谢谢
