### ISSUE TITLE
[Features]增量复制功能键的改进

### ISSUE THREAD

**Issue by MrGongqi** [CopyTranslator/CopyTranslator#527]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

我建议将增量复制这个功能键放在最外层的界面上，就在布局切换键的旁边。因为翻译的时候随时要打开增量复制和关闭它，放在界面上操作起来才更方便。

前言：
请务必详细阅读[使用指南](https://copytranslator.gitee.io/guide/)和项目的[project](https://github.com/CopyTranslator/CopyTranslator/projects)并在Issuse中查找您问题的关键词，**您想要的特性有很大的可能已经被实现/已经在计划中/由其他人提出了**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完上述内容，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
布局按钮：可以在三种[布局](https://copytranslator.github.io/guide/11.0.0.html#%E5%88%87%E6%8D%A2%E5%B8%83%E5%B1%80)中切换（[水平对比模式，垂直对比模式](https://copytranslator.github.io/guide/11.0.0.html#%E5%AF%B9%E7%85%A7%E6%A8%A1%E5%BC%8F-%E6%B0%B4%E5%B9%B3%E5%B8%83%E5%B1%80-%E5%9E%82%E7%9B%B4%E5%B8%83%E5%B1%80)，[专注模式](https://copytranslator.github.io/guide/11.0.0.html#%E4%B8%93%E6%B3%A8%E6%A8%A1%E5%BC%8F)）。v11后，右键[单次增量复制](https://copytranslator.github.io/guide/11.0.0.html#%E5%8D%95%E6%AC%A1%E5%A2%9E%E9%87%8F%E5%A4%8D%E5%88%B6)。

https://copytranslator.github.io/guide/11.0.0.html#%E5%8D%95%E6%AC%A1%E5%A2%9E%E9%87%8F%E5%A4%8D%E5%88%B6
