### ISSUE TITLE
希望缩放的时候能够将原文和翻译同时缩放

### ISSUE THREAD

**Issue by WonderfulUnknown** [CopyTranslator/CopyTranslator#53]
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
缩放的时候并不是缩放，只是单纯地减少译文的部分

**描述您想要的解决方案**
希望能够将原文和译文等比例缩放，方便自己调成小窗口使用

**附加背景**
![image](https://user-images.githubusercontent.com/40764322/53721090-4f231e80-3e9d-11e9-8958-0e0373c6c90a.png)

**Comment by elliottzheng** [comment]
欢迎试用 [0.0.8 尝鲜版](https://github.com/CopyTranslator/CopyTranslator/releases/tag/0.0.8-alpha-win)，在新版中他们已经是等比例缩放的了 。。。。旧版本的问题不再处理。
