### ISSUE TITLE
0.0.8版本  有两问题：

### ISSUE THREAD

**Issue by ariagecheney** [CopyTranslator/CopyTranslator#55]
**描述问题**
1   ：win10 64bits    扩展屏使用，软件界面莫名其妙变得很大很大，而且鼠标拖拽移动 ，竟然出现欲往哪边移动，反而向另外一方向移动，鼠标在很远处（并未在  绿色  那个标题栏上）就会有 拖拽不准的迹象，十分别扭，鼠标停在绿色标题栏，单击鼠标，整个界面都突然间往右下角偏移了0.8分米左右；但是在    没有扩展屏的情况下，则正常。
2   ：接入扩展屏，还有掉帧，卡卡的那种感觉，选择【自动隐藏】，一帧一帧的画面 才会消失。；比如说两个屏幕，软件翻译完成后，并不能在同一个屏幕中做到完全显示，即使强行拖拽到一个屏幕中去，反而还是会【缺胳膊少腿，根本显示不完全】。取消扩展屏后，在笔记本的自己的屏幕中，反而正常。
3    ：看了下 点按复制， 选中所需要字体后，再将鼠标悬停，【再单击鼠标左键并且长按，那不就是原来的选中的  都消失啦，这里一直很疑问。】
 - CopyTranslator版本：如v0.0.8   x64版
 - 出现问题时的模式：对照模式或专注模式  都有
 - 操作系统：如win10 64位/win 7 32位
 - 阅读器：zhizhi阅读器    http://www.zhizhireader.com/
 - 出现问题的文档：应该说哪个文档都是会出现上面的问题
![copytranslatebugs](https://user-images.githubusercontent.com/35078844/53774964-8e984c00-3f2b-11e9-88c2-19c6aab07c24.jpg)
。
 - 出现问题的段落：全文

**如何复现这个问题**
重现行为的步骤：
1. windows 10  接入扩展屏，就会出现鼠标拖拽不准，偏移的厉害，
2. 点按复制，我还是没有入门。是需要更换pdf浏览器啊
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

换了  microsoft edge   虽然选中后，鼠标放在上面悬停，再点击，不会取消【已选中】，但仍然无法翻译。

第一次使用issue上传图片 ，不知道格式对不对

**Comment by elliottzheng** [comment]
点按复制的兼容性不好，很经常不能使用，这挺正常的。点按动作会触发模拟ctrl+c但是并不一定会复制到内容，这我也很无奈。
拓展屏的问题，我会再看看。

**Comment by ZhuBaohe** [comment]
@elliottzheng  我的问题是尝鲜版界面想点击移动就消失了，再也不出现了，无论是对照还是专注模式。win10的64位系统。

**Comment by roison** [comment]
> @elliottzheng win10的64位系统，3840*2160分辨率显示屏，在win10的“系统”->“显示”->“缩放与布局”选择缩放“200%”时，尝鲜版界面点击移动就消失了，再也不出现了，无论是对照还是专注模式。 缩放改为“100%”，则正常显示。
> 希望能解决这问题，让软件在缩放“200%”时能用。0.0.7版一切正常，没有这个问题。

Win10的缩放修改一般都要注销才可以的。我是27寸的4K屏幕，175%缩放，使用正常。

**Comment by ZhuBaohe** [comment]
> > @elliottzheng win10的64位系统，3840*2160分辨率显示屏，在win10的“系统”->“显示”->“缩放与布局”选择缩放“200%”时，尝鲜版界面点击移动就消失了，再也不出现了，无论是对照还是专注模式。 缩放改为“100%”，则正常显示。
> > 希望能解决这问题，让软件在缩放“200%”时能用。0.0.7版一切正常，没有这个问题。
> 
> Win10的缩放修改一般都要注销才可以的。我是27寸的4K屏幕，175%缩放，使用正常。

我是笔记本4k屏，缩放到175%或者注销都没有用，尝鲜版界面长按并移动就消失。0.0.7版没这个问题。

**Comment by roison** [comment]
> > > @elliottzheng win10的64位系统，3840*2160分辨率显示屏，在win10的“系统”->“显示”->“缩放与布局”选择缩放“200%”时，尝鲜版界面点击移动就消失了，再也不出现了，无论是对照还是专注模式。 缩放改为“100%”，则正常显示。
> > > 希望能解决这问题，让软件在缩放“200%”时能用。0.0.7版一切正常，没有这个问题。
> > 
> > 
> > Win10的缩放修改一般都要注销才可以的。我是27寸的4K屏幕，175%缩放，使用正常。
> 
> 我是笔记本4k屏，缩放到175%或者注销都没有用，尝鲜版界面长按并移动就消失。0.0.7版没这个问题。

我尝试了一下，确实有问题；不过并不完全是消失，而是软件界面脱离鼠标，飘移到其他位置甚至屏幕之外了（你按住鼠标各种移动后还是能把界面拽出来的，同时界面在不断放大）。。
作者修复之前，临时解决办法是通过用win+方向键来调整软件界面的大小和位置（可以调整为屏幕的1/2或1/4面积），然后再通过调整边框来调整大小即可。
（PS：实际上我自己因为一直使用这种方法来调整软件界面实现多窗口工作，所以之前没发现有这个问题）

**Comment by roison** [comment]
> 可以先更新到[alpha3](https://github.com/CopyTranslator/CopyTranslator/releases/0.0.8-alpha-win)
> 贫穷的我没有测试高分屏的环境，我两个1920*1080的屏幕，没有遇到那个鼠标漂移的问题，但是拓展屏的问题，以及隐藏后无法打开的问题稍微改了一点。后面会把贴侧边隐藏捅到另一个屏幕的问题处理掉。

。。新版本启动后报错，见我新开的贴子：https://github.com/CopyTranslator/CopyTranslator/issues/57

**Comment by M1ddlzh** [comment]
也是win10，64位，更新后点击界面，画面会莫名其妙变大，界面后面还有黑影，很难受！
![image](https://user-images.githubusercontent.com/45971465/55313905-8b956a80-549b-11e9-818f-82e3157d0c77.png)

**Comment by elliottzheng** [comment]
现在的问题比较多的集中在界面的闪烁，变大，消失等情况，我大概知道原因，但是没空修复，后面我会再排查，
