### ISSUE TITLE
0.0.8-pre-release-alpha3 版本无法启动

### ISSUE THREAD

**Issue by roison** [CopyTranslator/CopyTranslator#57]
**描述问题**
0.0.8-pre-release-alpha3启动后直接报错，如图所示。
先前的0.0.7、0.0.8的alpha和alpha2版本都是正常使用的

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：0.0.8-pre-release-alpha3
 - 出现问题时的模式：双击启动时即出现
 - 操作系统：win10 1809 64位
 - 阅读器：
 - 出现问题的文档：
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 安装并启动0.0.8-pre-release-alpha3
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**
![8c0c1bda-ca2e-4522-9617-55c04d80713a](https://user-images.githubusercontent.com/33749821/53894908-e4740d80-406b-11e9-89b5-8c40254e3082.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
先前的0.0.7、0.0.8的alpha和alpha2版本都是正常使用的。卸载后重装alpha2版本也是正常的。

**Comment by elliottzheng** [comment]
试下 [alpha4](https://github.com/CopyTranslator/CopyTranslator/releases/tag/0.0.8-alpha-win)
