### ISSUE TITLE
按下Switch Mode後 沒有出現專注模式介面

### ISSUE THREAD

**Issue by syokujinau** [CopyTranslator/CopyTranslator#59]
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.7-RC1 x86 版
 - 出现问题时的模式：FocusMode 
 - 操作系统：win10 64位 
 

**如何复现这个问题**
重现行为的步骤：
1. 在MainMode按下Switch Mode 

之後介面就不見了，如下圖
![image](https://user-images.githubusercontent.com/12937401/54015147-d59b7100-41b9-11e9-960e-cea928fcd6e0.png)

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
您提供的信息太少了，我没有办法复现这个问题。你可以试下点击状态栏/任务栏图标。也许就出来了？

**Comment by syokujinau** [comment]
重新下載，可以了  感謝作者提供這麼方便的工具 萬分感謝
另外想問，什麼時候會新增介面語言(我看到已經有zh-tw.json了) 
以及，是否能把Youdao的結果再轉換成繁體呢?
期待更新，想必會增加很多繁體字用戶

**Comment by elliottzheng** [comment]
感谢 @s8321414 的努力，CopyTranslator发布即附带繁体中文的界面，现在0.0.8 的尝鲜版已经可以在设置中切换到繁体中文界面，不过尚不完善。敬请期待
