### ISSUE TITLE
征集神奇生物版本代号(Call for version nickname)

### ISSUE THREAD

**Issue by elliottzheng** [CopyTranslator/CopyTranslator#6]
CopyTranslator 每个大版本会有一个神奇生物版本代号，大家可以来出谋划策，要求是：
1. 神奇生物
2. 最好有比较合适的英文表达。
3. 不限国籍
如 v0.0.7-麒麟/Kylin

**Comment by elliottzheng** [comment]
驺吾/Zouwu

**Comment by elliottzheng** [comment]
感谢设计师Mārtiņš Zemlickis的出色设计，新的图标将在几天后发布。
![image](https://user-images.githubusercontent.com/22427645/50773452-d738dd80-12cb-11e9-9b7c-45e5d7f74c8a.png)

**Comment by Vixb1122** [comment]
獬豸/Haetae

**Comment by dourgey** [comment]
独角兽 / Unicorn
飞马 / Pegasus

**Comment by windghoul** [comment]
貔貅/Pixiu

**Comment by ryuzheng** [comment]
Why not Goose?
https://marvelcinematicuniverse.fandom.com/wiki/Goose
漫威《惊奇队长》里的橘猫，噬元兽（Flerken）
![image](https://user-images.githubusercontent.com/5512323/54409402-902ef480-4721-11e9-96dc-51e484b0931c.png)

**Comment by elliottzheng** [comment]
@ryuzheng  Goose is so cute

**Comment by ryuzheng** [comment]
> @ryuzheng Goose is so cute

不能同意更多。但Goose也算是电影角色了，有点担心版权问题。

**Comment by elliottzheng** [comment]
不能同意更多 也太秀了。。，应该没事，毕竟不是商业用途

**Comment by AglaiaChan** [comment]
这都已经驺吾了...那接下来用什么...Buckbeak/巴克比克？Phoenix？虽然很喜欢Bowtruckle/护树罗锅但是不太符合...

**Comment by elliottzheng** [comment]
@AglaiaChan 挺有趣的，不过以这个版本进度得老久了，后面换的勤快点

**Comment by zhfanrui** [comment]
[中国妖怪列表](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9C%8B%E5%A6%96%E6%80%AA%E5%88%97%E8%A1%A8)，[山海经](https://zh.wikipedia.org/wiki/%E5%B1%B1%E6%B5%B7%E7%BB%8F)，这些可能比较有用。

**Comment by elliottzheng** [comment]
@zhfanrui 要找名字很多，只是我想让大家有参与感，比较有趣

**Comment by xxxxx-qin** [comment]
Octocat

**Comment by xxxxx-qin** [comment]
软件开源在Github上，所以Octocat正好对应，再加上好萌！

**Comment by elliottzheng** [comment]
哈哈，我的上一个头像就是octocat

**Comment by bujianbusan** [comment]
推介使用 地质年代表里面的的古生物命名，而且那些古生物是按照时间顺序排列好的，词汇有些是希腊语，非常固定，也不存在歧义。

**Comment by elliottzheng** [comment]
Mimicat ![](https://gss1.bdstatic.com/9vo3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike92%2C5%2C5%2C92%2C30/sign=4a5acb24d80735fa85fd46ebff3864d6/6a63f6246b600c336606b7f7164c510fd9f9a196.jpg)
