### ISSUE TITLE
0.0.8 alpha4 版 自动粘贴问题

### ISSUE THREAD

**Issue by ZhuBaohe** [CopyTranslator/CopyTranslator#60]
**描述问题**
alpha4 的“自动复制”和“自动粘贴”功能，对多行内容有bug。
例如，选中“自动复制”和“自动粘贴”，不选”检测语言“
记事本输入下面两行内容：
”
Hard case: The changes are not the same.
Easy case: The changes are the same.
“
选择并复制， 替换结果为
”
硬案例：变化不一样。 简单案例：变化是一样的。Hard case: The change is different. Simple case: The change is the same.
"
有两个问题：
1 中文翻译没有换行
2 中文翻译后又加了不需要的中翻英结果。

如果是对单行翻译，则正常。

**系统环境（请填写以下信息）： 
 - CopyTranslator版本：如v0.0.8 alpha4 版
 - 出现问题时的模式：对照模式
 - 操作系统：win10 64位

**Comment by elliottzheng** [comment]
感谢反馈
