### ISSUE TITLE
能否为复制原文增加一个快捷键，例如shift+ctrl+v

### ISSUE THREAD

**Issue by windghoul** [CopyTranslator/CopyTranslator#61]
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
在使用中，如果软件常驻后台，会自动翻译复制的英文，有时候会想使用原文，但是已经被翻译成中文。这样很不方便。
**描述您想要的解决方案**
添加快捷键之后，可以方便的在自动翻译的情况下进行原文的粘贴，并且可以使软件常驻系统后台

**Comment by elliottzheng** [comment]
新版CopyTranslator强大的动作系统，使得几乎所有的操作都可以绑定全局快捷键。可以看这里

https://copytranslator.gitee.io/guide/advance.html#自定义全局快捷键

**Comment by windghoul** [comment]
> 新版CopyTranslator强大的动作系统，使得几乎所有的操作都可以绑定全局快捷键。可以看这里
> 
> [https://copytranslator.gitee.io/guide/advance.html#自定义全局快捷键](https://copytranslator.gitee.io/guide/advance.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE)

thanks
