### ISSUE TITLE
0.0.8-pre-release-alpha5版本的翻译分段问题，及软件卸载不完全版本间相互影响问题

### ISSUE THREAD

**Issue by roison** [CopyTranslator/CopyTranslator#62]
**描述问题**
在0.0.8较早版本中（如alpha2），原文若为多段文字，翻译结果则无分段，全部挤在一段里。0.0.8-pre-release-alpha5似乎将其矫枉过正了，不仅原文多段文字将断行，连句号也大概率会断行，具体见图。
此外，安装alpha5版本后若想更换回alpha2，直接卸载alpha5后重装alpha2是不可以的，会造成软件使用时报错。必须在卸载alpha5后，使用everything之类的软件把找到的C盘下4个以copytranslator打头的文件夹手动删除，再重新安装alpha2方可成功。估计应该卸载后残留的设置在版本间互相不兼容导致的，很可能今后其他版本更新也可能会有类似问题，可以考虑增加说明。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：0.0.8-pre-release-alpha5版
 - 出现问题时的模式：对照模式、专注模式
 - 操作系统：win10 64位
 - 阅读器：与阅读器无关
 - 出现问题的文档：与具体文字无关
 - 出现问题的段落：与具体文字无关

**如何复现这个问题**
重现行为的步骤：
1. 复制一段英文文本，我们以从维基百科英文版复制“葛底斯堡演说”为例。（https://en.wikipedia.org/wiki/Gettysburg_Address）
2. 如图所示，原文为三段，alpha2版本翻译结果未分段，而alpha5版本翻译结果为十段。
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**
![alpha2](https://user-images.githubusercontent.com/33749821/54083610-a5420700-4360-11e9-90c6-aa0e4b6616db.png)
![alpha5](https://user-images.githubusercontent.com/33749821/54083611-aa06bb00-4360-11e9-9e44-97e5a3fcb660.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
与浏览器/阅读器无关

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by ZhuBaohe** [comment]
装了alpha5，托盘右键点击出错。安装楼主说的，搜索C盘所有的copytranslator目录和文件，并删除重装，现在终于正常了。

**Comment by elliottzheng** [comment]
现在copytranslator的设置全都是在 {userdir}/copytranslator文件夹，其中{userdir}在windows指的是c:\users\{你的用户名}。
分段的问题已经定位了，尚待修复。

**Comment by elliottzheng** [comment]
在这里记录一下分段问题产生的原因，因为Youdao，Google,Baidu所使用的翻译引擎 translation.js 返回的结果是句子的列表，失去了原本的分段。
![图片](https://user-images.githubusercontent.com/22427645/55133038-456c9e00-515f-11e9-884e-5739a71cf08d.png)


可以看到，在使用不同实现的Sogou引擎后，不会出现这个情况
![图片](https://user-images.githubusercontent.com/22427645/55133113-79e05a00-515f-11e9-8d3c-767c8018ee25.png)
后面就是要换翻译引擎了
