### ISSUE TITLE
0.0.8-pre-release-alpha5 选项记忆问题

### ISSUE THREAD

**Issue by ZhuBaohe** [CopyTranslator/CopyTranslator#64]
**描述问题**
“对照模式”，无法记忆“检测语言”和“监听剪切板”的**关闭**选择。
在“对照模式”面板上，关闭“检测语言”和“监听剪切板”的选择，然后关闭软件，再重新打开，“检测语言”和“监听剪切板”选项仍旧选中。
希望软件能记忆上一次退出时的所有选项的选择。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：0.0.8-pre-release-alpha5 
 - 出现问题时的模式：对照模式
 - 操作系统：如win10 64位

**Comment by elliottzheng** [comment]
alpha6了解一下
