### ISSUE TITLE
[Features]希望增加OCR取词功能，就像有道词典的OCR取词功能

### ISSUE THREAD

**Issue by redstoneleo** [CopyTranslator/CopyTranslator#67]
希望增加OCR取词功能，就像有道词典的OCR取词功能，主要是方便查询陌生单词。
这个功能我尝试做过，我的步骤是

1. 截取到仅仅包含鼠标箭头下面的单词
2. 把图片送给OCR引擎转出单词文本

我的难点是不知道如何截取到仅仅包含鼠标箭头下面的单词的矩形图片，也就是如何确定这个矩形，我目前的笨办法是截取一个差不多大的矩形框（足够能包含鼠标箭头下面的单词），这种做法的问题是这个矩形图片可能包含太多内容以至于OCR引擎转出单词文本的时间稍长，也就导致OCR取词过程速度上不来。
阁下似乎对计算机图形学很有研究，你有么有什么好方法呢？希望多多指教。

**Comment by elliottzheng** [comment]
你好，这个特性可以考虑，但优先级不高，后面再来处理

**Comment by elliottzheng** [comment]
我测试了一下，有道可以在图片上取词，而且文字的大小不会影响到取词的成功与否，且其CPU占用率很小，大约只有百分之0.1~0.3，可以说是非常牛，应该确实是用ocr来取词的，而不是用hook，当然划译那是另一回事。我猜测
1. 他使用了某种搜索策略，矩形框会逐渐变大和移动，直到发现一个有意义的词
2. 同时弄出多个矩形框进行检测。
我没有尝试过离线ocr，不知道这个性能算是怎么样，这个问题值得进一步研究。

**Comment by redstoneleo** [comment]
对，hook的适用范围有局限性，做起来也比较难，据我的测评来看，现在的桌面软件基本都是用ocr技术。
离线ocr按我目前采用的笨办法基本上要1s才能出结果，这速度还是要等等才会出结果，不是太理想，还是没有有道快。
找到单词矩形框的功能可能是用了“OCR膨胀腐蚀”算法，你谷歌一下。我小白基本上对计算机图形学没什么了解，只能靠大大加油了！

**Comment by lucky-top** [comment]
之前一直使用0.0.7-RC1版本，然后现在直接跳到了9.0.0版本，看到设置里面有OCR设置，申请了百度的接口之后，如何使用呢？

**Comment by silencer404** [comment]
可否由用户来决定矩形框的大小呢？就像截图一样

**Comment by elliottzheng** [comment]
启用[离线OCR](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.1.0)/百度OCR之后截图复制到剪贴板即可翻译
