### ISSUE TITLE
0.0.8-alpha8版 有道翻译问题

### ISSUE THREAD

**Issue by ZhuBaohe** [CopyTranslator/CopyTranslator#70]
**描述问题**
 0.0.8-alpha8版 有道翻译，如果复制一大段英文，只能翻译一句中文。alpha6版 没这个问题。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：0.0.8-alpha8 
 - 出现问题时的模式： 对照模式和专注模式
 - 操作系统： win10 64位

**Comment by elliottzheng** [comment]
老哥太勤奋了，忠实用户，感谢反馈

**Comment by elliottzheng** [comment]
我检查了一下，应该是用的开源库的问题，看这里 https://github.com/Selection-Translator/translation.js/issues/35， 等他修复吧，暂时先用其他的翻译引擎吧
