### ISSUE TITLE
我最终还是选择了 QTranslate

### ISSUE THREAD

**Issue by baozhilv** [CopyTranslator/CopyTranslator#71]
1. 我明明只是想翻译几个单词，一点击翻译就给我拉成一行了，很烦
2.QTranslate 好歹有自动翻译，这个居然没有，我是很烦动鼠标的，好歹也给个快捷键吧，pass

**Comment by elliottzheng** [comment]
慢走不送，没有看文档想当然就觉得啥都没有，然后发个issue彰显优越感我也没有办法。
文档在[这里 ](https://copytranslator.github.io/guide/#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8)
![image](https://user-images.githubusercontent.com/22427645/54877989-ec4ff200-4e60-11e9-8f2e-3d806979f0f7.png)

![image](https://user-images.githubusercontent.com/22427645/54877984-e0643000-4e60-11e9-8851-7d1823b2ab13.png)
