### ISSUE TITLE
我按了一个switch这个按钮，然后整个界面就消失在右边了，调整不回来，系统是win10

### ISSUE THREAD

**Issue by cibiluozu** [CopyTranslator/CopyTranslator#74]
我按了一个switch这个按钮，然后整个界面就消失在右边了，调整不回来，系统是win10

**Comment by elliottzheng** [comment]
>大哥，配合一下，麻烦提issue的时候用模板。不然你看我们现在交流的效率就很低。我不知道你说的是哪个版本，因为我现在用v0.0.7 Kylin RC1用得好好的，我不知道你是不是用这个版本，你有没有更新，你用的什么系统，我啥也不知道，得全部重新问一遍，一问一答的效率很低

#13 

明明在new issue的时候这么大两个按钮，为什么您非得不按模板，然后选择regular issue呢？
![图片](https://user-images.githubusercontent.com/22427645/55285833-c62cd380-53c5-11e9-8ba8-a32cc8f1d7ad.png)

**Comment by fengrussell** [comment]
我今天更新了0.8，现象和他描述的一样，窗口闪动一下，然后就不见了

**Comment by elliottzheng** [comment]
出现闪烁的用户可以试下这个 我试着修复了 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v0.0.8-Zouwu-RC2

**Comment by cibiluozu** [comment]
抱歉，下次一定注意，谢谢。

**Comment by elliottzheng** [comment]
@cibiluozu @fengrussell  https://github.com/CopyTranslator/CopyTranslator/releases/tag/v0.0.8-Zouwu-RC3 可以试下这个

**Comment by elliottzheng** [comment]
I'm closing this issue because it has been inactive for days.
