### ISSUE TITLE
翻译一段话好奇怪的结果

### ISSUE THREAD

**Issue by tt3736035** [CopyTranslator/CopyTranslator#78]
![QQ图片20190402170918](https://user-images.githubusercontent.com/38688389/55390607-1a70b880-556a-11e9-96b1-30d3ea4977c4.png)

Herein, an ultra-sensitive colorimetric assay called magnetic nano(e)zyme - linked immunosorbent assay (MagLISA) is suggested, in which silica-shelled magnetic nanobeads (MagNBs) and gold nanoparticles are combined to monitor influenza A virus up to femtogram per milliliter concentration
此软件的所有接口均是这个错误结果，但搜狗翻译网页上结果是正确的。
所以，是不是搜狗翻译接口有问题呢？

**Comment by elliottzheng** [comment]
![图片](https://user-images.githubusercontent.com/22427645/55404585-c924f100-558a-11e9-97be-cd11f112381c.png)

**Comment by elliottzheng** [comment]
![image](https://user-images.githubusercontent.com/22427645/55536753-25078b00-56ed-11e9-9a27-6bad877d1af8.png)
![image](https://user-images.githubusercontent.com/22427645/55536833-5c763780-56ed-11e9-91f0-12e2741befab.png)

不清楚你截图当中的翻译结果是copytranslator的翻译结果还是搜狗的翻译结果，我测试的时候这两句基本是一样的。或许您可以提提供这段话的pdf版本给我测试

**Comment by elliottzheng** [comment]
I'm closing this issue because it has been inactive for days.
