### ISSUE TITLE
软件主界面能不能把windows右上角的缩小-放大-关闭按钮添加上去

### ISSUE THREAD

**Issue by svbing** [CopyTranslator/CopyTranslator#80]
1.请求增加windows窗口右上角的缩小+放大+关闭功能。
2.请求增加一键清除页面内容按钮。

**Comment by elliottzheng** [comment]
![图片](https://user-images.githubusercontent.com/22427645/55572776-f3b5ac00-573a-11e9-82a3-d8c940e52859.png)
1. 会考虑
2. 已经有了，叫清空，在右键菜单里

**Comment by elliottzheng** [comment]
I'm closing this issue because it has been inactive for days.
