### ISSUE TITLE
按了几下复制的快捷键，整个软件都卡死了，重新打开软件也直接卡死

### ISSUE THREAD

**Issue by xlgforever** [CopyTranslator/CopyTranslator#81]
原因是我在用PDF看文献时，选中了一段文字，然后按ctrl+c，但是没反应，后来发现是因为选中文字之后，当前激活窗口切换到了copytranslator软件，然后再按的ctrl+c，然后软件卡死，重新启动软件也直接卡死，在使用Windows命令清空了剪贴板后软件恢复正常。

猜测是因为使用control+c复制了copytranslator这个软件本身，因为数据庞大，导致软件直接卡死？或者是导致了死循环。

**Comment by elliottzheng** [comment]
![image](https://user-images.githubusercontent.com/22427645/55602727-969d1300-5799-11e9-9ed4-d0bede2958dd.png)
明明在new issue的时候这么大两个按钮，为什么您非得不按模板，然后选择regular issue呢？
