### ISSUE TITLE
[Features]

### ISSUE THREAD

**Issue by sternacht** [CopyTranslator/CopyTranslator#83]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
前一個用的版本(忘記幾號了不好意思)可以用ctrl+enter來執行翻譯，現在這個(v0.0.8-RC3)好像不行。

**描述您想要的解决方案**
是否按鍵組合有改動，或是可以把這樣的組合加回去，因為有時候需要一直打字就不太會去碰滑鼠，用鍵盤比較快。

**描述您考虑过的替代方案**
無

**附加背景**
無

**Comment by elliottzheng** [comment]
没有变化，依然可以使用

**Comment by elliottzheng** [comment]
只不过稍微有点问题，就是在显示单词词组详细释义的时候，不能用，后面会修复的

**Comment by elliottzheng** [comment]
已经修复了，可以试下这个 https://github.com/CopyTranslator/CopyTranslator/releases/tag/v0.0.8-Zouwu-RC4

**Comment by sternacht** [comment]
謝謝你，效率真好
