### ISSUE TITLE
请求支持彩云小译翻译接口

### ISSUE THREAD

**Issue by sfantree** [CopyTranslator/CopyTranslator#94]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
希望能添加 彩云小译 接口，个人觉得学术性技术类文章翻译质量比机翻更好，可以参考相关 [chrome扩展](https://chrome.google.com/webstore/detail/lingocloud-interpreter/jmpepeebcbihafjjadogphmbgiffiajh) 的评价

**描述您想要的解决方案**
彩云小译 [API文档](https://open.caiyunapp.com/%E4%BA%94%E5%88%86%E9%92%9F%E5%AD%A6%E4%BC%9A%E5%BD%A9%E4%BA%91%E5%B0%8F%E8%AF%91_API#.E4.B8.80.E5.88.86.E9.92.9F.E4.BB.8B.E7.BB.8D) 附带白嫖 token

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
Duplicate of #93 
最主要问题是不能保证测试TOKEN的可用性。翻译量很大。我先简单测试一下，再做答复

**Comment by sfantree** [comment]
感谢

**Comment by elliottzheng** [comment]
花了一点时间搞了下，试下这个 https://www.lanzous.com/b389683
