### ISSUE TITLE
为什么还是不能用，整个卡住了

### ISSUE THREAD

**Issue by 123fengye741** [CopyTranslator/CopyTranslator#95]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
（反馈前请先查看wiki中的使用指南，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，查看使用指南能够解决您90%的疑惑，如果看完使用指南，疑问仍然存在，请到下载页面看看有没有最新预览版，并下载试用，如果最新版的问题解决了，那就不用再反馈问题了）

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.6.1 x86 版
 - 出现问题时的模式：MainMode/ FocusMode或者说对照模式或专注模式
 - 操作系统：如win10 64位/win 7 32位
 - 阅读器：如 chrome浏览器/福昕阅读器，最好附上下载地址
 - 出现问题的文档：附上文档文件
 - 出现问题的段落：第五段，第二句话

**如何复现这个问题**
重现行为的步骤：
1. 
2. 整个界面卡住了，从0008开始基本都不能使用，全部卡主不动。
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

> [**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**]([url](url))

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
Duplicate of #91 
你什么信息也不提供，我怎么知道为什么别人电脑能用你电脑不能用

**Comment by 123fengye741** [comment]
我上传图片 上传不成功的。软件装完之后就自动跑到最右边，怎么也拉不回来。而且没有任何按钮显示。








------------------ 原始邮件 ------------------
发件人: "Elliott Zheng"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 下午2:51
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com>;
抄送: "fengye"<1165480684@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CopyTranslator/CopyTranslator] 为什么还是不能用，整个卡住了 (#95)




Duplicate of #91
 你什么信息也不提供，我怎么知道为什么别人电脑能用你电脑不能用

**Comment by elliottzheng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    按照模板填写好吗，上面提供了模板，没有这些信息，我根本就没办法跟你讨论这个问题，不用模板交流的效率就很低。我不知道你说的是哪个版本，因为现在最新的是用v0.0.7 Zouwu RC5 用得好好的，我不知道你是不是用这个版本，你有没有更新，你用的什么系统，我啥也不知道，得全部重新问一遍，一问一答的效率很低试下删除 c:/users/你的用户名/copytranslator文件夹，再重新打开
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                admin
                            
                    
                        
                            
                                    admin@hypercube.top
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年4月11日 14:55，123fengye741<notifications@github.com> 写道： 


我上传图片 上传不成功的。软件装完之后就自动跑到最右边，怎么也拉不回来。而且没有任何按钮显示。

















------------------ 原始邮件 ------------------

发件人: "Elliott Zheng"<notifications@github.com>;

发送时间: 2019年4月11日(星期四) 下午2:51

收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com>;

抄送: "fengye"<1165480684@qq.com>; "Author"<author@noreply.github.com>; 

主题: Re: [CopyTranslator/CopyTranslator] 为什么还是不能用，整个卡住了 (#95)









Duplicate of #91

 你什么信息也不提供，我怎么知道为什么别人电脑能用你电脑不能用

 

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 123fengye741** [comment]
我把那个删除之后。现在可以用了。谢了






------------------ 原始邮件 ------------------
发件人: "Elliott Zheng"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 下午3:24
收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com>;
抄送: "fengye"<1165480684@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CopyTranslator/CopyTranslator] 为什么还是不能用，整个卡住了 (#95)



 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     按照模板填写好吗，上面提供了模板，没有这些信息，我根本就没办法跟你讨论这个问题，不用模板交流的效率就很低。我不知道你说的是哪个版本，因为现在最新的是用v0.0.7 Zouwu RC5 用得好好的，我不知道你是不是用这个版本，你有没有更新，你用的什么系统，我啥也不知道，得全部重新问一遍，一问一答的效率很低试下删除 c:/users/你的用户名/copytranslator文件夹，再重新打开
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 admin
                             
                     
                         
                             
                                     admin@hypercube.top
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     在2019年4月11日 14:55，123fengye741<notifications@github.com> 写道： 
 
 
 我上传图片 上传不成功的。软件装完之后就自动跑到最右边，怎么也拉不回来。而且没有任何按钮显示。
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------
 
 发件人: "Elliott Zheng"<notifications@github.com>;
 
 发送时间: 2019年4月11日(星期四) 下午2:51
 
 收件人: "CopyTranslator/CopyTranslator"<CopyTranslator@noreply.github.com>;
 
 抄送: "fengye"<1165480684@qq.com>; "Author"<author@noreply.github.com>; 
 
 主题: Re: [CopyTranslator/CopyTranslator] 为什么还是不能用，整个卡住了 (#95)
 
 
 
 
 
 
 
 
 
 Duplicate of #91
 
  你什么信息也不提供，我怎么知道为什么别人电脑能用你电脑不能用
 
  
 
 —
 
 You are receiving this because you authored the thread.
 
 Reply to this email directly, view it on GitHub, or mute the thread.
 
 —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
