### ISSUE TITLE
已经选择源语言和目标语言后，仍然对非选中源语言的语言进行翻译

### ISSUE THREAD

**Issue by yangzirui** [CopyTranslator/CopyTranslator#96]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
设置的源语言是英文，目标语言是英文，但是我复制中文的时候，软件会自动将中文翻译成英文，并且显示出来。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如.v0.0.8-Zouwu-RC5
 - 出现问题时的模式：专注模式
 - 操作系统：win10 64位
 - 阅读器：chrome浏览器、福昕阅读器
 - 出现问题的文档：所有
 - 出现问题的段落：所有

**如何复现这个问题**
重现行为的步骤：
1. 选择专注模式、自动隐藏、自动显示、监听剪贴板、总是置顶
2. 打开chrome或者用福晰阅读器打开一段中文文本，然后选中复制
3. 软件就会自动显示中文对应的英文翻译。 

**问题出现时，当时的CopyTranslator的设置截图**
![image](https://user-images.githubusercontent.com/23444836/56073029-81933600-5dd0-11e9-9c40-3c3dddacb7c2.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
都不可以。

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
以前没有用过。

**Comment by elliottzheng** [comment]
这是一个特性。。。。。
![图片](https://user-images.githubusercontent.com/22427645/56073055-cdde7600-5dd0-11e9-9e26-d371fa08ab98.png)
建议您先阅读[使用指南](https://copytranslator.gitee.io/guide/)

**Comment by yangzirui** [comment]
您好，我选择了检测语言，出现了同样的结果
![image](https://user-images.githubusercontent.com/23444836/56073351-d46eec80-5dd4-11e9-963e-c326edceaf1b.png)

**Comment by elliottzheng** [comment]
这段描述有点过期，现在检测语言不太会影响到智能互译
我觉得这个问题意义不是很大。你们是期待看到什么样的结果呢

**Comment by elliottzheng** [comment]
上面截图的因为我检测到你正好是目标语言，所以我就翻译成源语言，这个我逻辑我觉得没问题

**Comment by yangzirui** [comment]
我的目的就是想关闭源语言和目标语言互译这个功能，根据您的文档中的说明
![image](https://user-images.githubusercontent.com/23444836/56073478-2ca6ee00-5dd7-11e9-804e-986225f639f1.png)
如果我打开了“检测语言”这个功能，就相当于关闭了“智能互译”功能，所以我打开了“检测语言”这个功能，此时我的源语言是英文，目标语言是中文，这是不是就代表了，现在如果我复制了英文，就会自动帮我翻译成中文，但是如果我复制了中文，软件就不会帮我翻译，因为我打开了“检测语言”这个功能，相当于关闭了“智能互译”这个功能。但是现在的问题是，我打开了“检测语言”这个功能，“智能互译”这个功能并没有关闭。
![image](https://user-images.githubusercontent.com/23444836/56073524-26fdd800-5dd8-11e9-8b2a-77ca5a4915ba.png)

**Comment by elliottzheng** [comment]
智能互译现在不能关闭，后面考虑可以关闭，可以说下您要关闭智能互译的应用场景吗

**Comment by yangzirui** [comment]
您好，我就是在平时学习的时候，有时需要翻译英文，但是同时我可能也会因为一些其他的事情偶尔复制一下中文。复制英文时自动弹出软件并且显示中文翻译，然后又会自动隐藏，这个功能真的非常棒，但是偶尔我复制中文的时候，也会弹出软件窗口这就又有点影响体验了。
感谢您的回复。
