### ISSUE TITLE
打开后顶层栏一直为红色，无法翻译

### ISSUE THREAD

**Issue by AglaiaChan** [CopyTranslator/CopyTranslator#98]
>重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。
**描述问题**
打开后顶层栏一直为红色，无法翻译，无论是对照模式还是专注模式都一样的结果。网络没有问题，浏览器谷歌翻译也能打开。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：v0.0.8-Zouwu-RC1
 - 出现问题时的模式：均有
 - 操作系统：win10 64位
 - 阅读器：chrome浏览器以及360安全浏览器
 - 出现问题的文档：随便一句话都有这种问题
 - 出现问题的段落：***

**如何复现这个问题**
重现行为的步骤：
1. 直接打开copytranslator，任意复制一段话看是否有此问题（不明原因）

**问题出现时，当时的CopyTranslator的设置截图**
截图如下：
![360截图20190418100353930](https://user-images.githubusercontent.com/45378864/56332184-e3cdab80-61c1-11e9-97c4-d7572dd680f5.png)

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**
均不可

**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**
忘记之前的有没有了，不过这个问题我遇到过两次，上一次好像是重新打开后就好了，这一次重启好几次依然存在该问题。

**Comment by AglaiaChan** [comment]
well, 重启电脑后没有该问题了，一切OK

**Comment by AglaiaChan** [comment]
下午又出问题了...

**Comment by elliottzheng** [comment]
下RC5的

**Comment by elliottzheng** [comment]
然后切换翻译器
